version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: omc-erp-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: omc_erp_dev
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/01-init.sql
    networks:
      - omc-erp-network

  # TimescaleDB for time-series data
  timescaledb:
    image: timescale/timescaledb:latest-pg15
    container_name: omc-erp-timescaledb
    environment:
      POSTGRES_USER: timescale
      POSTGRES_PASSWORD: timescale
      POSTGRES_DB: omc_erp_timeseries
    ports:
      - '5433:5432'
    volumes:
      - timescale_data:/var/lib/postgresql/data
    networks:
      - omc-erp-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: omc-erp-redis
    command: redis-server --appendonly yes
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - omc-erp-network

  # MongoDB for document storage
  mongodb:
    image: mongo:6
    container_name: omc-erp-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: omc_erp_docs
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    networks:
      - omc-erp-network

  # Kafka for event streaming
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: omc-erp-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - omc-erp-network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: omc-erp-kafka
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - omc-erp-network

  # MinIO for S3-compatible storage
  minio:
    image: minio/minio:latest
    container_name: omc-erp-minio
    command: server /data --console-address ":9001"
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    networks:
      - omc-erp-network

  # Adminer for database management
  adminer:
    image: adminer:latest
    container_name: omc-erp-adminer
    ports:
      - '8080:8080'
    networks:
      - omc-erp-network

networks:
  omc-erp-network:
    driver: bridge

volumes:
  postgres_data:
  timescale_data:
  redis_data:
  mongo_data:
  minio_data: