import { ConfigurationModule, ConfigurationType, ConfigurationDataType } from './entities/configuration.entity';

// Complete configuration schema for ALL ERP modules
export const AllModulesConfigurationSchema = [
  // ===== FINANCIAL MANAGEMENT MODULES =====

  // ACCOUNTING MODULE
  ...require('./schemas/accounting-config.schema').AccountingConfigurationSchema,

  // FIXED ASSETS MODULE
  {
    key: 'fixed_assets.depreciation.default_method',
    name: 'Default Depreciation Method',
    description: 'Default method for asset depreciation calculation',
    module: ConfigurationModule.FIXED_ASSETS,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.STRING,
    defaultValue: 'STRAIGHT_LINE',
    allowedValues: ['STRAIGHT_LINE', 'DOUBLE_DECLINING', 'SUM_OF_YEARS', 'UNITS_OF_PRODUCTION'],
    uiComponent: 'SELECT',
    uiGroup: 'Depreciation',
    uiOrder: 1,
  },
  {
    key: 'fixed_assets.ifrs16.lease_accounting_enabled',
    name: 'Enable IFRS 16 Lease Accounting',
    description: 'Apply IFRS 16 standards for lease accounting',
    module: ConfigurationModule.FIXED_ASSETS,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.BOOLEAN,
    defaultValue: 'true',
    uiComponent: 'CHECKBOX',
    uiGroup: 'IFRS Compliance',
    uiOrder: 1,
  },
  {
    key: 'fixed_assets.numbering.auto_generate',
    name: 'Auto Generate Asset Numbers',
    description: 'Automatically generate asset numbers',
    module: ConfigurationModule.FIXED_ASSETS,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.BOOLEAN,
    defaultValue: 'true',
    uiComponent: 'CHECKBOX',
    uiGroup: 'Asset Management',
    uiOrder: 1,
  },

  // TAX MANAGEMENT MODULE
  {
    key: 'tax.ghana.vat_rate',
    name: 'Ghana VAT Rate',
    description: 'Current VAT rate for Ghana',
    module: ConfigurationModule.TAX_MANAGEMENT,
    type: ConfigurationType.SYSTEM,
    dataType: ConfigurationDataType.NUMBER,
    defaultValue: '12.5',
    minValue: 0,
    maxValue: 50,
    uiComponent: 'NUMBER',
    uiGroup: 'Ghana Tax Rates',
    uiOrder: 1,
  },
  {
    key: 'tax.ghana.nhil_rate',
    name: 'NHIL Rate',
    description: 'National Health Insurance Levy rate',
    module: ConfigurationModule.TAX_MANAGEMENT,
    type: ConfigurationType.SYSTEM,
    dataType: ConfigurationDataType.NUMBER,
    defaultValue: '2.5',
    minValue: 0,
    maxValue: 10,
    uiComponent: 'NUMBER',
    uiGroup: 'Ghana Tax Rates',
    uiOrder: 2,
  },
  {
    key: 'tax.ghana.getfund_rate',
    name: 'GETFund Rate',
    description: 'Ghana Education Trust Fund levy rate',
    module: ConfigurationModule.TAX_MANAGEMENT,
    type: ConfigurationType.SYSTEM,
    dataType: ConfigurationDataType.NUMBER,
    defaultValue: '2.5',
    minValue: 0,
    maxValue: 10,
    uiComponent: 'NUMBER',
    uiGroup: 'Ghana Tax Rates',
    uiOrder: 3,
  },
  {
    key: 'tax.gra.auto_filing_enabled',
    name: 'Enable GRA Auto Filing',
    description: 'Automatically file tax returns with GRA',
    module: ConfigurationModule.TAX_MANAGEMENT,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.BOOLEAN,
    defaultValue: 'true',
    uiComponent: 'CHECKBOX',
    uiGroup: 'GRA Integration',
    uiOrder: 1,
  },

  // BUDGET AND PLANNING MODULE
  {
    key: 'budget.planning.default_periods',
    name: 'Default Budget Periods',
    description: 'Number of periods in budget planning',
    module: ConfigurationModule.BUDGET_PLANNING,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.NUMBER,
    defaultValue: '12',
    minValue: 1,
    maxValue: 60,
    uiComponent: 'NUMBER',
    uiGroup: 'Budget Planning',
    uiOrder: 1,
  },
  {
    key: 'budget.variance.alert_threshold',
    name: 'Budget Variance Alert Threshold',
    description: 'Percentage variance to trigger alerts',
    module: ConfigurationModule.BUDGET_PLANNING,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.NUMBER,
    defaultValue: '10',
    minValue: 1,
    maxValue: 50,
    uiComponent: 'SLIDER',
    uiGroup: 'Variance Analysis',
    uiOrder: 1,
  },

  // ===== HUMAN RESOURCES MODULES =====

  // HUMAN RESOURCES MODULE
  {
    key: 'hr.employee.probation_period_months',
    name: 'Default Probation Period (Months)',
    description: 'Standard probation period for new employees',
    module: ConfigurationModule.HUMAN_RESOURCES,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.NUMBER,
    defaultValue: '6',
    minValue: 1,
    maxValue: 24,
    uiComponent: 'NUMBER',
    uiGroup: 'Employee Management',
    uiOrder: 1,
  },
  {
    key: 'hr.leave.annual_leave_days',
    name: 'Annual Leave Days',
    description: 'Default annual leave days per year',
    module: ConfigurationModule.HUMAN_RESOURCES,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.NUMBER,
    defaultValue: '15',
    minValue: 10,
    maxValue: 30,
    uiComponent: 'NUMBER',
    uiGroup: 'Leave Management',
    uiOrder: 1,
  },
  {
    key: 'hr.ghana.minimum_wage',
    name: 'Ghana Minimum Wage (Daily)',
    description: 'Current minimum wage per day in Ghana',
    module: ConfigurationModule.HUMAN_RESOURCES,
    type: ConfigurationType.SYSTEM,
    dataType: ConfigurationDataType.NUMBER,
    defaultValue: '18.15',
    minValue: 0,
    uiComponent: 'NUMBER',
    uiGroup: 'Ghana Labour Compliance',
    uiOrder: 1,
  },

  // PAYROLL MODULE
  {
    key: 'payroll.ghana.ssnit_employee_rate',
    name: 'SSNIT Employee Contribution Rate',
    description: 'Employee SSNIT contribution rate',
    module: ConfigurationModule.PAYROLL,
    type: ConfigurationType.SYSTEM,
    dataType: ConfigurationDataType.NUMBER,
    defaultValue: '5.5',
    minValue: 0,
    maxValue: 20,
    uiComponent: 'NUMBER',
    uiGroup: 'Ghana SSNIT',
    uiOrder: 1,
  },
  {
    key: 'payroll.ghana.ssnit_employer_rate',
    name: 'SSNIT Employer Contribution Rate',
    description: 'Employer SSNIT contribution rate',
    module: ConfigurationModule.PAYROLL,
    type: ConfigurationType.SYSTEM,
    dataType: ConfigurationDataType.NUMBER,
    defaultValue: '13.0',
    minValue: 0,
    maxValue: 20,
    uiComponent: 'NUMBER',
    uiGroup: 'Ghana SSNIT',
    uiOrder: 2,
  },
  {
    key: 'payroll.auto_calculation',
    name: 'Enable Auto Payroll Calculation',
    description: 'Automatically calculate payroll on schedule',
    module: ConfigurationModule.PAYROLL,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.BOOLEAN,
    defaultValue: 'true',
    uiComponent: 'CHECKBOX',
    uiGroup: 'Payroll Processing',
    uiOrder: 1,
  },

  // ===== SUPPLY CHAIN MODULES =====
  ...require('./schemas/supply-chain-config.schema').SupplyChainConfigurationSchema,

  // PROCUREMENT MODULE
  {
    key: 'procurement.approval_workflow',
    name: 'Enable Approval Workflow',
    description: 'Require approval workflow for procurement',
    module: ConfigurationModule.PROCUREMENT,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.BOOLEAN,
    defaultValue: 'true',
    uiComponent: 'CHECKBOX',
    uiGroup: 'Workflow Management',
    uiOrder: 1,
  },
  {
    key: 'procurement.rfq_minimum_suppliers',
    name: 'Minimum Suppliers for RFQ',
    description: 'Minimum number of suppliers for Request for Quotation',
    module: ConfigurationModule.PROCUREMENT,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.NUMBER,
    defaultValue: '3',
    minValue: 1,
    maxValue: 10,
    uiComponent: 'NUMBER',
    uiGroup: 'RFQ Process',
    uiOrder: 1,
  },

  // VENDOR MANAGEMENT MODULE
  {
    key: 'vendor.performance.rating_frequency',
    name: 'Vendor Performance Rating Frequency',
    description: 'How often to rate vendor performance',
    module: ConfigurationModule.VENDOR_MANAGEMENT,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.STRING,
    defaultValue: 'QUARTERLY',
    allowedValues: ['MONTHLY', 'QUARTERLY', 'SEMI_ANNUALLY', 'ANNUALLY'],
    uiComponent: 'SELECT',
    uiGroup: 'Performance Management',
    uiOrder: 1,
  },
  {
    key: 'vendor.onboarding.auto_approval',
    name: 'Auto-Approve Vendor Onboarding',
    description: 'Automatically approve vendor applications',
    module: ConfigurationModule.VENDOR_MANAGEMENT,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.BOOLEAN,
    defaultValue: 'false',
    uiComponent: 'CHECKBOX',
    uiGroup: 'Vendor Onboarding',
    uiOrder: 1,
  },

  // FLEET MANAGEMENT MODULE
  {
    key: 'fleet.maintenance.preventive_enabled',
    name: 'Enable Preventive Maintenance',
    description: 'Schedule preventive maintenance for fleet vehicles',
    module: ConfigurationModule.FLEET_MANAGEMENT,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.BOOLEAN,
    defaultValue: 'true',
    uiComponent: 'CHECKBOX',
    uiGroup: 'Maintenance Management',
    uiOrder: 1,
  },
  {
    key: 'fleet.tracking.gps_enabled',
    name: 'Enable GPS Tracking',
    description: 'Track fleet vehicles using GPS',
    module: ConfigurationModule.FLEET_MANAGEMENT,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.BOOLEAN,
    defaultValue: 'true',
    uiComponent: 'CHECKBOX',
    uiGroup: 'Vehicle Tracking',
    uiOrder: 1,
  },
  {
    key: 'fleet.fuel.efficiency_threshold',
    name: 'Fuel Efficiency Alert Threshold',
    description: 'Fuel efficiency below which to send alerts (km/L)',
    module: ConfigurationModule.FLEET_MANAGEMENT,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.NUMBER,
    defaultValue: '10',
    minValue: 1,
    maxValue: 50,
    uiComponent: 'NUMBER',
    uiGroup: 'Fuel Management',
    uiOrder: 1,
  },

  // ===== RISK AND COMPLIANCE MODULES =====

  // RISK MANAGEMENT MODULE
  {
    key: 'risk.assessment.frequency',
    name: 'Risk Assessment Frequency',
    description: 'How often to conduct risk assessments',
    module: ConfigurationModule.RISK_MANAGEMENT,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.STRING,
    defaultValue: 'QUARTERLY',
    allowedValues: ['MONTHLY', 'QUARTERLY', 'SEMI_ANNUALLY', 'ANNUALLY'],
    uiComponent: 'SELECT',
    uiGroup: 'Risk Assessment',
    uiOrder: 1,
  },
  {
    key: 'risk.tolerance.default_level',
    name: 'Default Risk Tolerance Level',
    description: 'Default risk tolerance for the organization',
    module: ConfigurationModule.RISK_MANAGEMENT,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.STRING,
    defaultValue: 'MEDIUM',
    allowedValues: ['LOW', 'MEDIUM', 'HIGH'],
    uiComponent: 'SELECT',
    uiGroup: 'Risk Tolerance',
    uiOrder: 1,
  },
  {
    key: 'risk.reporting.board_threshold',
    name: 'Board Reporting Risk Threshold',
    description: 'Risk level that requires board reporting',
    module: ConfigurationModule.RISK_MANAGEMENT,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.STRING,
    defaultValue: 'HIGH',
    allowedValues: ['MEDIUM', 'HIGH', 'CRITICAL'],
    uiComponent: 'SELECT',
    uiGroup: 'Risk Reporting',
    uiOrder: 1,
  },

  // AUDIT AND CONTROLS MODULE
  {
    key: 'audit.internal.frequency',
    name: 'Internal Audit Frequency',
    description: 'Frequency of internal audits',
    module: ConfigurationModule.AUDIT_CONTROLS,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.STRING,
    defaultValue: 'QUARTERLY',
    allowedValues: ['MONTHLY', 'QUARTERLY', 'SEMI_ANNUALLY', 'ANNUALLY'],
    uiComponent: 'SELECT',
    uiGroup: 'Audit Planning',
    uiOrder: 1,
  },
  {
    key: 'audit.findings.auto_assignment',
    name: 'Auto-Assign Audit Findings',
    description: 'Automatically assign findings to responsible parties',
    module: ConfigurationModule.AUDIT_CONTROLS,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.BOOLEAN,
    defaultValue: 'true',
    uiComponent: 'CHECKBOX',
    uiGroup: 'Finding Management',
    uiOrder: 1,
  },

  // CONTRACT MANAGEMENT MODULE
  {
    key: 'contract.renewal.alert_days',
    name: 'Contract Renewal Alert Days',
    description: 'Days before expiry to send renewal alerts',
    module: ConfigurationModule.CONTRACT_MANAGEMENT,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.NUMBER,
    defaultValue: '90',
    minValue: 1,
    maxValue: 365,
    uiComponent: 'NUMBER',
    uiGroup: 'Contract Lifecycle',
    uiOrder: 1,
  },
  {
    key: 'contract.approval.required',
    name: 'Require Contract Approval',
    description: 'All contracts require approval before execution',
    module: ConfigurationModule.CONTRACT_MANAGEMENT,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.BOOLEAN,
    defaultValue: 'true',
    uiComponent: 'CHECKBOX',
    uiGroup: 'Approval Workflow',
    uiOrder: 1,
  },
  {
    key: 'contract.ghana.stamp_duty_rate',
    name: 'Ghana Stamp Duty Rate',
    description: 'Stamp duty rate for contracts in Ghana',
    module: ConfigurationModule.CONTRACT_MANAGEMENT,
    type: ConfigurationType.SYSTEM,
    dataType: ConfigurationDataType.NUMBER,
    defaultValue: '0.5',
    minValue: 0,
    maxValue: 5,
    uiComponent: 'NUMBER',
    uiGroup: 'Ghana Compliance',
    uiOrder: 1,
  },

  // IFRS COMPLIANCE MODULE
  {
    key: 'ifrs.auto_classification',
    name: 'Enable Auto IFRS Classification',
    description: 'Automatically classify transactions per IFRS standards',
    module: ConfigurationModule.IFRS_COMPLIANCE,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.BOOLEAN,
    defaultValue: 'true',
    uiComponent: 'CHECKBOX',
    uiGroup: 'Auto Classification',
    uiOrder: 1,
  },
  {
    key: 'ifrs.reporting.frequency',
    name: 'IFRS Reporting Frequency',
    description: 'Frequency of IFRS compliance reporting',
    module: ConfigurationModule.IFRS_COMPLIANCE,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.STRING,
    defaultValue: 'MONTHLY',
    allowedValues: ['DAILY', 'WEEKLY', 'MONTHLY', 'QUARTERLY'],
    uiComponent: 'SELECT',
    uiGroup: 'Compliance Reporting',
    uiOrder: 1,
  },

  // ===== CUSTOMER AND SALES MODULES =====
  ...require('./schemas/crm-config.schema').CRMConfigurationSchema,

  // CUSTOMER SERVICE MODULE
  {
    key: 'customer_service.ticket.auto_assignment',
    name: 'Auto-Assign Support Tickets',
    description: 'Automatically assign tickets to available agents',
    module: ConfigurationModule.CUSTOMER_SERVICE,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.BOOLEAN,
    defaultValue: 'true',
    uiComponent: 'CHECKBOX',
    uiGroup: 'Ticket Management',
    uiOrder: 1,
  },
  {
    key: 'customer_service.sla.default_response_hours',
    name: 'Default SLA Response Hours',
    description: 'Default response time for support tickets',
    module: ConfigurationModule.CUSTOMER_SERVICE,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.NUMBER,
    defaultValue: '24',
    minValue: 1,
    maxValue: 168,
    uiComponent: 'NUMBER',
    uiGroup: 'SLA Management',
    uiOrder: 1,
  },

  // ===== TECHNOLOGY MODULES =====

  // IOT MONITORING MODULE
  {
    key: 'iot.tank.monitoring_interval',
    name: 'Tank Monitoring Interval (Minutes)',
    description: 'How often to read tank sensor data',
    module: ConfigurationModule.IOT_MONITORING,
    type: ConfigurationType.SYSTEM,
    dataType: ConfigurationDataType.NUMBER,
    defaultValue: '5',
    minValue: 1,
    maxValue: 60,
    uiComponent: 'NUMBER',
    uiGroup: 'Tank Monitoring',
    uiOrder: 1,
  },
  {
    key: 'iot.alerts.low_level_threshold',
    name: 'Low Level Alert Threshold (%)',
    description: 'Tank level percentage to trigger low level alerts',
    module: ConfigurationModule.IOT_MONITORING,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.NUMBER,
    defaultValue: '20',
    minValue: 5,
    maxValue: 50,
    uiComponent: 'SLIDER',
    uiGroup: 'Alert Thresholds',
    uiOrder: 1,
  },
  {
    key: 'iot.environmental.monitoring_enabled',
    name: 'Enable Environmental Monitoring',
    description: 'Monitor environmental parameters',
    module: ConfigurationModule.IOT_MONITORING,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.BOOLEAN,
    defaultValue: 'true',
    uiComponent: 'CHECKBOX',
    uiGroup: 'Environmental Monitoring',
    uiOrder: 1,
  },

  // ANALYTICS MODULE
  {
    key: 'analytics.dashboard.refresh_interval',
    name: 'Dashboard Refresh Interval (Minutes)',
    description: 'How often to refresh dashboard data',
    module: ConfigurationModule.ANALYTICS,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.NUMBER,
    defaultValue: '15',
    minValue: 1,
    maxValue: 60,
    uiComponent: 'NUMBER',
    uiGroup: 'Dashboard Settings',
    uiOrder: 1,
  },
  {
    key: 'analytics.reporting.auto_generation',
    name: 'Enable Auto Report Generation',
    description: 'Automatically generate scheduled reports',
    module: ConfigurationModule.ANALYTICS,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.BOOLEAN,
    defaultValue: 'true',
    uiComponent: 'CHECKBOX',
    uiGroup: 'Report Generation',
    uiOrder: 1,
  },

  // PAYMENT PROCESSING MODULE
  {
    key: 'payment.mobile_money.enabled',
    name: 'Enable Mobile Money Payments',
    description: 'Accept mobile money payments',
    module: ConfigurationModule.PAYMENT_PROCESSING,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.BOOLEAN,
    defaultValue: 'true',
    uiComponent: 'CHECKBOX',
    uiGroup: 'Payment Methods',
    uiOrder: 1,
  },
  {
    key: 'payment.mtn_momo.enabled',
    name: 'Enable MTN Mobile Money',
    description: 'Accept MTN Mobile Money payments',
    module: ConfigurationModule.PAYMENT_PROCESSING,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.BOOLEAN,
    defaultValue: 'true',
    uiComponent: 'CHECKBOX',
    uiGroup: 'Mobile Money Providers',
    uiOrder: 1,
  },
  {
    key: 'payment.vodafone_cash.enabled',
    name: 'Enable Vodafone Cash',
    description: 'Accept Vodafone Cash payments',
    module: ConfigurationModule.PAYMENT_PROCESSING,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.BOOLEAN,
    defaultValue: 'true',
    uiComponent: 'CHECKBOX',
    uiGroup: 'Mobile Money Providers',
    uiOrder: 2,
  },
  {
    key: 'payment.airteltigo_money.enabled',
    name: 'Enable AirtelTigo Money',
    description: 'Accept AirtelTigo Money payments',
    module: ConfigurationModule.PAYMENT_PROCESSING,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.BOOLEAN,
    defaultValue: 'true',
    uiComponent: 'CHECKBOX',
    uiGroup: 'Mobile Money Providers',
    uiOrder: 3,
  },

  // ===== SYSTEM MODULES =====

  // AUTHENTICATION MODULE
  {
    key: 'auth.mfa.required',
    name: 'Require Multi-Factor Authentication',
    description: 'Require MFA for all user logins',
    module: ConfigurationModule.AUTHENTICATION,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.BOOLEAN,
    defaultValue: 'true',
    uiComponent: 'CHECKBOX',
    uiGroup: 'Security Settings',
    uiOrder: 1,
  },
  {
    key: 'auth.session.timeout_minutes',
    name: 'Session Timeout (Minutes)',
    description: 'User session timeout duration',
    module: ConfigurationModule.AUTHENTICATION,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.NUMBER,
    defaultValue: '60',
    minValue: 5,
    maxValue: 480,
    uiComponent: 'NUMBER',
    uiGroup: 'Session Management',
    uiOrder: 1,
  },
  {
    key: 'auth.password.min_length',
    name: 'Minimum Password Length',
    description: 'Minimum required password length',
    module: ConfigurationModule.AUTHENTICATION,
    type: ConfigurationType.SYSTEM,
    dataType: ConfigurationDataType.NUMBER,
    defaultValue: '8',
    minValue: 6,
    maxValue: 20,
    uiComponent: 'NUMBER',
    uiGroup: 'Password Policy',
    uiOrder: 1,
  },

  // NOTIFICATION MODULE
  {
    key: 'notification.email.enabled',
    name: 'Enable Email Notifications',
    description: 'Send notifications via email',
    module: ConfigurationModule.NOTIFICATION,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.BOOLEAN,
    defaultValue: 'true',
    uiComponent: 'CHECKBOX',
    uiGroup: 'Notification Channels',
    uiOrder: 1,
  },
  {
    key: 'notification.sms.enabled',
    name: 'Enable SMS Notifications',
    description: 'Send notifications via SMS',
    module: ConfigurationModule.NOTIFICATION,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.BOOLEAN,
    defaultValue: 'true',
    uiComponent: 'CHECKBOX',
    uiGroup: 'Notification Channels',
    uiOrder: 2,
  },
  {
    key: 'notification.whatsapp.enabled',
    name: 'Enable WhatsApp Notifications',
    description: 'Send notifications via WhatsApp',
    module: ConfigurationModule.NOTIFICATION,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.BOOLEAN,
    defaultValue: 'false',
    uiComponent: 'CHECKBOX',
    uiGroup: 'Notification Channels',
    uiOrder: 3,
  },

  // DOCUMENT MANAGEMENT MODULE
  {
    key: 'document.storage.cloud_enabled',
    name: 'Enable Cloud Storage',
    description: 'Store documents in cloud storage',
    module: ConfigurationModule.DOCUMENT_MANAGEMENT,
    type: ConfigurationType.SYSTEM,
    dataType: ConfigurationDataType.BOOLEAN,
    defaultValue: 'true',
    uiComponent: 'CHECKBOX',
    uiGroup: 'Storage Settings',
    uiOrder: 1,
  },
  {
    key: 'document.versioning.enabled',
    name: 'Enable Document Versioning',
    description: 'Track document versions',
    module: ConfigurationModule.DOCUMENT_MANAGEMENT,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.BOOLEAN,
    defaultValue: 'true',
    uiComponent: 'CHECKBOX',
    uiGroup: 'Version Control',
    uiOrder: 1,
  },
  {
    key: 'document.retention.default_years',
    name: 'Default Retention Period (Years)',
    description: 'Default document retention period',
    module: ConfigurationModule.DOCUMENT_MANAGEMENT,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.NUMBER,
    defaultValue: '7',
    minValue: 1,
    maxValue: 50,
    uiComponent: 'NUMBER',
    uiGroup: 'Retention Policy',
    uiOrder: 1,
  },

  // ===== GHANA SPECIFIC MODULES =====

  // NPA COMPLIANCE MODULE
  {
    key: 'npa.license.auto_renewal_reminder',
    name: 'Auto NPA License Renewal Reminder',
    description: 'Send automatic reminders for license renewal',
    module: ConfigurationModule.NPA_COMPLIANCE,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.BOOLEAN,
    defaultValue: 'true',
    uiComponent: 'CHECKBOX',
    uiGroup: 'License Management',
    uiOrder: 1,
  },
  {
    key: 'npa.reporting.daily_stock_time',
    name: 'Daily Stock Report Time',
    description: 'Time to submit daily stock reports to NPA',
    module: ConfigurationModule.NPA_COMPLIANCE,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.STRING,
    defaultValue: '23:30',
    regexPattern: '^([0-1]?[0-9]|2[0-3]):[0-5][0-9]$',
    uiComponent: 'TIME',
    uiGroup: 'Stock Reporting',
    uiOrder: 1,
  },

  // EPA COMPLIANCE MODULE
  {
    key: 'epa.monitoring.air_quality_enabled',
    name: 'Enable Air Quality Monitoring',
    description: 'Monitor air quality parameters',
    module: ConfigurationModule.EPA_COMPLIANCE,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.BOOLEAN,
    defaultValue: 'true',
    uiComponent: 'CHECKBOX',
    uiGroup: 'Environmental Monitoring',
    uiOrder: 1,
  },
  {
    key: 'epa.reporting.quarterly_enabled',
    name: 'Enable Quarterly EPA Reporting',
    description: 'Submit quarterly reports to EPA',
    module: ConfigurationModule.EPA_COMPLIANCE,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.BOOLEAN,
    defaultValue: 'true',
    uiComponent: 'CHECKBOX',
    uiGroup: 'EPA Reporting',
    uiOrder: 1,
  },

  // GRA INTEGRATION MODULE
  {
    key: 'gra.auto_filing.vat_enabled',
    name: 'Auto VAT Return Filing',
    description: 'Automatically file VAT returns with GRA',
    module: ConfigurationModule.GRA_INTEGRATION,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.BOOLEAN,
    defaultValue: 'true',
    uiComponent: 'CHECKBOX',
    uiGroup: 'Tax Filing',
    uiOrder: 1,
  },
  {
    key: 'gra.integration.api_enabled',
    name: 'Enable GRA API Integration',
    description: 'Use GRA API for real-time integration',
    module: ConfigurationModule.GRA_INTEGRATION,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.BOOLEAN,
    defaultValue: 'true',
    uiComponent: 'CHECKBOX',
    uiGroup: 'API Integration',
    uiOrder: 1,
  },

  // BOG REPORTING MODULE
  {
    key: 'bog.forex.reporting_enabled',
    name: 'Enable Forex Reporting to BOG',
    description: 'Submit foreign exchange reports to Bank of Ghana',
    module: ConfigurationModule.BOG_REPORTING,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.BOOLEAN,
    defaultValue: 'true',
    uiComponent: 'CHECKBOX',
    uiGroup: 'Forex Reporting',
    uiOrder: 1,
  },

  // UPPF MANAGEMENT MODULE
  {
    key: 'uppf.claims.auto_submission',
    name: 'Auto Submit UPPF Claims',
    description: 'Automatically submit claims to UPPF',
    module: ConfigurationModule.UPPF_MANAGEMENT,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.BOOLEAN,
    defaultValue: 'true',
    uiComponent: 'CHECKBOX',
    uiGroup: 'Claims Management',
    uiOrder: 1,
  },
  {
    key: 'uppf.pricing.auto_update',
    name: 'Auto Update UPPF Pricing',
    description: 'Automatically update pricing from UPPF',
    module: ConfigurationModule.UPPF_MANAGEMENT,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.BOOLEAN,
    defaultValue: 'true',
    uiComponent: 'CHECKBOX',
    uiGroup: 'Price Management',
    uiOrder: 1,
  },

  // LOCAL CONTENT MODULE
  {
    key: 'local_content.tracking.enabled',
    name: 'Enable Local Content Tracking',
    description: 'Track local content percentage compliance',
    module: ConfigurationModule.LOCAL_CONTENT,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.BOOLEAN,
    defaultValue: 'true',
    uiComponent: 'CHECKBOX',
    uiGroup: 'Content Tracking',
    uiOrder: 1,
  },
  {
    key: 'local_content.minimum_percentage',
    name: 'Minimum Local Content Percentage',
    description: 'Required minimum local content percentage',
    module: ConfigurationModule.LOCAL_CONTENT,
    type: ConfigurationType.SYSTEM,
    dataType: ConfigurationDataType.NUMBER,
    defaultValue: '10',
    minValue: 0,
    maxValue: 100,
    uiComponent: 'SLIDER',
    uiGroup: 'Compliance Requirements',
    uiOrder: 1,
  },

  // ===== SECURITY AND AUDIT =====

  // SECURITY MODULE
  {
    key: 'security.encryption.enabled',
    name: 'Enable Data Encryption',
    description: 'Encrypt sensitive data at rest',
    module: ConfigurationModule.SECURITY,
    type: ConfigurationType.SYSTEM,
    dataType: ConfigurationDataType.BOOLEAN,
    defaultValue: 'true',
    uiComponent: 'CHECKBOX',
    uiGroup: 'Data Protection',
    uiOrder: 1,
    isSensitive: true,
  },
  {
    key: 'security.backup.frequency',
    name: 'Backup Frequency',
    description: 'How often to backup system data',
    module: ConfigurationModule.SECURITY,
    type: ConfigurationType.SYSTEM,
    dataType: ConfigurationDataType.STRING,
    defaultValue: 'DAILY',
    allowedValues: ['HOURLY', 'DAILY', 'WEEKLY'],
    uiComponent: 'SELECT',
    uiGroup: 'Backup Management',
    uiOrder: 1,
  },

  // AUDIT LOGGING MODULE
  {
    key: 'audit.logging.level',
    name: 'Audit Logging Level',
    description: 'Level of detail for audit logging',
    module: ConfigurationModule.AUDIT_LOGGING,
    type: ConfigurationType.SYSTEM,
    dataType: ConfigurationDataType.STRING,
    defaultValue: 'DETAILED',
    allowedValues: ['MINIMAL', 'STANDARD', 'DETAILED', 'COMPREHENSIVE'],
    uiComponent: 'SELECT',
    uiGroup: 'Logging Configuration',
    uiOrder: 1,
  },
  {
    key: 'audit.retention.years',
    name: 'Audit Log Retention (Years)',
    description: 'How long to retain audit logs',
    module: ConfigurationModule.AUDIT_LOGGING,
    type: ConfigurationType.SYSTEM,
    dataType: ConfigurationDataType.NUMBER,
    defaultValue: '7',
    minValue: 1,
    maxValue: 20,
    uiComponent: 'NUMBER',
    uiGroup: 'Data Retention',
    uiOrder: 1,
  },
];