"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.AccountingConfigurationSchema = void 0;
const configuration_entity_1 = require("../entities/configuration.entity");
exports.AccountingConfigurationSchema = [
    // General Ledger Configuration
    {
        key: 'accounting.gl.fiscal_year_start',
        name: 'Fiscal Year Start Month',
        description: 'The month when the fiscal year starts (1-12)',
        module: configuration_entity_1.ConfigurationModule.ACCOUNTING,
        type: configuration_entity_1.ConfigurationType.SYSTEM,
        dataType: configuration_entity_1.ConfigurationDataType.NUMBER,
        defaultValue: '1',
        minValue: 1,
        maxValue: 12,
        isRequired: true,
        uiComponent: 'SELECT',
        uiGroup: 'General Ledger',
        uiOrder: 1,
        allowedValues: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12'],
    },
    {
        key: 'accounting.gl.auto_posting_enabled',
        name: 'Enable Automatic Journal Posting',
        description: 'Automatically post journal entries when approved',
        module: configuration_entity_1.ConfigurationModule.ACCOUNTING,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.BOOLEAN,
        defaultValue: 'true',
        uiComponent: 'CHECKBOX',
        uiGroup: 'General Ledger',
        uiOrder: 2,
    },
    {
        key: 'accounting.gl.multi_currency_enabled',
        name: 'Enable Multi-Currency',
        description: 'Allow transactions in multiple currencies',
        module: configuration_entity_1.ConfigurationModule.ACCOUNTING,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.BOOLEAN,
        defaultValue: 'true',
        uiComponent: 'CHECKBOX',
        uiGroup: 'General Ledger',
        uiOrder: 3,
    },
    {
        key: 'accounting.gl.base_currency',
        name: 'Base Currency',
        description: 'Primary currency for financial reporting',
        module: configuration_entity_1.ConfigurationModule.ACCOUNTING,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.STRING,
        defaultValue: 'GHS',
        allowedValues: ['GHS', 'USD', 'EUR', 'GBP'],
        isRequired: true,
        uiComponent: 'SELECT',
        uiGroup: 'General Ledger',
        uiOrder: 4,
    },
    {
        key: 'accounting.gl.decimal_places',
        name: 'Decimal Places for Amounts',
        description: 'Number of decimal places for monetary amounts',
        module: configuration_entity_1.ConfigurationModule.ACCOUNTING,
        type: configuration_entity_1.ConfigurationType.SYSTEM,
        dataType: configuration_entity_1.ConfigurationDataType.NUMBER,
        defaultValue: '2',
        minValue: 0,
        maxValue: 4,
        uiComponent: 'NUMBER',
        uiGroup: 'General Ledger',
        uiOrder: 5,
    },
    // Chart of Accounts
    {
        key: 'accounting.coa.account_code_length',
        name: 'Account Code Length',
        description: 'Standard length for account codes',
        module: configuration_entity_1.ConfigurationModule.ACCOUNTING,
        type: configuration_entity_1.ConfigurationType.SYSTEM,
        dataType: configuration_entity_1.ConfigurationDataType.NUMBER,
        defaultValue: '6',
        minValue: 4,
        maxValue: 20,
        uiComponent: 'NUMBER',
        uiGroup: 'Chart of Accounts',
        uiOrder: 1,
    },
    {
        key: 'accounting.coa.account_code_structure',
        name: 'Account Code Structure',
        description: 'Structure for account codes (e.g., AA-BBBB for 6 digits)',
        module: configuration_entity_1.ConfigurationModule.ACCOUNTING,
        type: configuration_entity_1.ConfigurationType.SYSTEM,
        dataType: configuration_entity_1.ConfigurationDataType.STRING,
        defaultValue: 'NNNNNN',
        regexPattern: '^[AN-]+$',
        uiComponent: 'INPUT',
        uiGroup: 'Chart of Accounts',
        uiOrder: 2,
    },
    {
        key: 'accounting.coa.ifrs_classification_mandatory',
        name: 'Mandatory IFRS Classification',
        description: 'Require IFRS classification for all accounts',
        module: configuration_entity_1.ConfigurationModule.ACCOUNTING,
        type: configuration_entity_1.ConfigurationType.SYSTEM,
        dataType: configuration_entity_1.ConfigurationDataType.BOOLEAN,
        defaultValue: 'true',
        uiComponent: 'CHECKBOX',
        uiGroup: 'Chart of Accounts',
        uiOrder: 3,
    },
    // Journal Entry Rules
    {
        key: 'accounting.journal.auto_numbering',
        name: 'Auto Journal Entry Numbering',
        description: 'Automatically generate journal entry numbers',
        module: configuration_entity_1.ConfigurationModule.ACCOUNTING,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.BOOLEAN,
        defaultValue: 'true',
        uiComponent: 'CHECKBOX',
        uiGroup: 'Journal Entries',
        uiOrder: 1,
    },
    {
        key: 'accounting.journal.number_prefix',
        name: 'Journal Entry Number Prefix',
        description: 'Prefix for journal entry numbers',
        module: configuration_entity_1.ConfigurationModule.ACCOUNTING,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.STRING,
        defaultValue: 'JE',
        uiComponent: 'INPUT',
        uiGroup: 'Journal Entries',
        uiOrder: 2,
    },
    {
        key: 'accounting.journal.require_approval',
        name: 'Require Journal Entry Approval',
        description: 'All journal entries must be approved before posting',
        module: configuration_entity_1.ConfigurationModule.ACCOUNTING,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.BOOLEAN,
        defaultValue: 'true',
        uiComponent: 'CHECKBOX',
        uiGroup: 'Journal Entries',
        uiOrder: 3,
    },
    {
        key: 'accounting.journal.approval_threshold',
        name: 'Approval Threshold Amount',
        description: 'Minimum amount requiring approval (in base currency)',
        module: configuration_entity_1.ConfigurationModule.ACCOUNTING,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.NUMBER,
        defaultValue: '10000',
        minValue: 0,
        uiComponent: 'NUMBER',
        uiGroup: 'Journal Entries',
        uiOrder: 4,
    },
    {
        key: 'accounting.journal.allow_future_dates',
        name: 'Allow Future Transaction Dates',
        description: 'Allow journal entries with future dates',
        module: configuration_entity_1.ConfigurationModule.ACCOUNTING,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.BOOLEAN,
        defaultValue: 'false',
        uiComponent: 'CHECKBOX',
        uiGroup: 'Journal Entries',
        uiOrder: 5,
    },
    {
        key: 'accounting.journal.max_future_days',
        name: 'Maximum Future Days',
        description: 'Maximum days in future for transaction dates',
        module: configuration_entity_1.ConfigurationModule.ACCOUNTING,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.NUMBER,
        defaultValue: '30',
        minValue: 1,
        maxValue: 365,
        uiComponent: 'NUMBER',
        uiGroup: 'Journal Entries',
        uiOrder: 6,
    },
    // Period Management
    {
        key: 'accounting.periods.auto_close',
        name: 'Auto-Close Periods',
        description: 'Automatically close accounting periods',
        module: configuration_entity_1.ConfigurationModule.ACCOUNTING,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.BOOLEAN,
        defaultValue: 'false',
        uiComponent: 'CHECKBOX',
        uiGroup: 'Period Management',
        uiOrder: 1,
    },
    {
        key: 'accounting.periods.close_days_after_end',
        name: 'Days to Auto-Close After Period End',
        description: 'Number of days after period end to auto-close',
        module: configuration_entity_1.ConfigurationModule.ACCOUNTING,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.NUMBER,
        defaultValue: '5',
        minValue: 1,
        maxValue: 30,
        uiComponent: 'NUMBER',
        uiGroup: 'Period Management',
        uiOrder: 2,
    },
    {
        key: 'accounting.periods.allow_prior_period_posting',
        name: 'Allow Prior Period Posting',
        description: 'Allow posting to prior accounting periods',
        module: configuration_entity_1.ConfigurationModule.ACCOUNTING,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.BOOLEAN,
        defaultValue: 'true',
        uiComponent: 'CHECKBOX',
        uiGroup: 'Period Management',
        uiOrder: 3,
    },
    // Exchange Rates
    {
        key: 'accounting.exchange.auto_update',
        name: 'Auto-Update Exchange Rates',
        description: 'Automatically update exchange rates from external source',
        module: configuration_entity_1.ConfigurationModule.ACCOUNTING,
        type: configuration_entity_1.ConfigurationType.SYSTEM,
        dataType: configuration_entity_1.ConfigurationDataType.BOOLEAN,
        defaultValue: 'true',
        uiComponent: 'CHECKBOX',
        uiGroup: 'Exchange Rates',
        uiOrder: 1,
    },
    {
        key: 'accounting.exchange.update_frequency',
        name: 'Exchange Rate Update Frequency',
        description: 'How often to update exchange rates',
        module: configuration_entity_1.ConfigurationModule.ACCOUNTING,
        type: configuration_entity_1.ConfigurationType.SYSTEM,
        dataType: configuration_entity_1.ConfigurationDataType.STRING,
        defaultValue: 'DAILY',
        allowedValues: ['REAL_TIME', 'HOURLY', 'DAILY', 'WEEKLY', 'MANUAL'],
        uiComponent: 'SELECT',
        uiGroup: 'Exchange Rates',
        uiOrder: 2,
    },
    {
        key: 'accounting.exchange.source_provider',
        name: 'Exchange Rate Provider',
        description: 'External provider for exchange rates',
        module: configuration_entity_1.ConfigurationModule.ACCOUNTING,
        type: configuration_entity_1.ConfigurationType.SYSTEM,
        dataType: configuration_entity_1.ConfigurationDataType.STRING,
        defaultValue: 'BANK_OF_GHANA',
        allowedValues: ['BANK_OF_GHANA', 'FIXER_IO', 'OPEN_EXCHANGE_RATES', 'MANUAL'],
        uiComponent: 'SELECT',
        uiGroup: 'Exchange Rates',
        uiOrder: 3,
    },
    // Reconciliation
    {
        key: 'accounting.reconciliation.auto_match_tolerance',
        name: 'Auto-Match Tolerance Amount',
        description: 'Tolerance amount for automatic reconciliation matching',
        module: configuration_entity_1.ConfigurationModule.ACCOUNTING,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.NUMBER,
        defaultValue: '0.01',
        minValue: 0,
        uiComponent: 'NUMBER',
        uiGroup: 'Reconciliation',
        uiOrder: 1,
    },
    {
        key: 'accounting.reconciliation.require_approval',
        name: 'Require Reconciliation Approval',
        description: 'All reconciliations must be approved',
        module: configuration_entity_1.ConfigurationModule.ACCOUNTING,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.BOOLEAN,
        defaultValue: 'true',
        uiComponent: 'CHECKBOX',
        uiGroup: 'Reconciliation',
        uiOrder: 2,
    },
    // Reporting
    {
        key: 'accounting.reporting.default_format',
        name: 'Default Report Format',
        description: 'Default format for financial reports',
        module: configuration_entity_1.ConfigurationModule.ACCOUNTING,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.STRING,
        defaultValue: 'PDF',
        allowedValues: ['PDF', 'EXCEL', 'CSV', 'HTML'],
        uiComponent: 'SELECT',
        uiGroup: 'Reporting',
        uiOrder: 1,
    },
    {
        key: 'accounting.reporting.comparative_periods',
        name: 'Comparative Periods in Reports',
        description: 'Number of comparative periods to show in reports',
        module: configuration_entity_1.ConfigurationModule.ACCOUNTING,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.NUMBER,
        defaultValue: '2',
        minValue: 0,
        maxValue: 5,
        uiComponent: 'NUMBER',
        uiGroup: 'Reporting',
        uiOrder: 2,
    },
    {
        key: 'accounting.reporting.zero_balance_accounts',
        name: 'Show Zero Balance Accounts',
        description: 'Include accounts with zero balances in reports',
        module: configuration_entity_1.ConfigurationModule.ACCOUNTING,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.BOOLEAN,
        defaultValue: 'false',
        uiComponent: 'CHECKBOX',
        uiGroup: 'Reporting',
        uiOrder: 3,
    },
    // Integration Settings
    {
        key: 'accounting.integration.bank_feeds_enabled',
        name: 'Enable Bank Feed Integration',
        description: 'Enable automatic bank statement imports',
        module: configuration_entity_1.ConfigurationModule.ACCOUNTING,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.BOOLEAN,
        defaultValue: 'true',
        uiComponent: 'CHECKBOX',
        uiGroup: 'Integration',
        uiOrder: 1,
    },
    {
        key: 'accounting.integration.gra_sync_enabled',
        name: 'Enable GRA Synchronization',
        description: 'Sync transactions with Ghana Revenue Authority',
        module: configuration_entity_1.ConfigurationModule.ACCOUNTING,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.BOOLEAN,
        defaultValue: 'true',
        uiComponent: 'CHECKBOX',
        uiGroup: 'Integration',
        uiOrder: 2,
    },
    {
        key: 'accounting.integration.ifrs_reporting_enabled',
        name: 'Enable IFRS Reporting',
        description: 'Generate IFRS-compliant financial reports',
        module: configuration_entity_1.ConfigurationModule.ACCOUNTING,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.BOOLEAN,
        defaultValue: 'true',
        uiComponent: 'CHECKBOX',
        uiGroup: 'Integration',
        uiOrder: 3,
    },
    // Security and Controls
    {
        key: 'accounting.security.require_2fa_for_posting',
        name: 'Require 2FA for Journal Posting',
        description: 'Require two-factor authentication for posting journal entries',
        module: configuration_entity_1.ConfigurationModule.ACCOUNTING,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.BOOLEAN,
        defaultValue: 'true',
        uiComponent: 'CHECKBOX',
        uiGroup: 'Security',
        uiOrder: 1,
    },
    {
        key: 'accounting.security.audit_all_changes',
        name: 'Audit All Changes',
        description: 'Log all changes to accounting data',
        module: configuration_entity_1.ConfigurationModule.ACCOUNTING,
        type: configuration_entity_1.ConfigurationType.SYSTEM,
        dataType: configuration_entity_1.ConfigurationDataType.BOOLEAN,
        defaultValue: 'true',
        uiComponent: 'CHECKBOX',
        uiGroup: 'Security',
        uiOrder: 2,
        isSystemConfig: true,
    },
    {
        key: 'accounting.security.data_retention_years',
        name: 'Data Retention Period (Years)',
        description: 'Number of years to retain accounting data',
        module: configuration_entity_1.ConfigurationModule.ACCOUNTING,
        type: configuration_entity_1.ConfigurationType.SYSTEM,
        dataType: configuration_entity_1.ConfigurationDataType.NUMBER,
        defaultValue: '7',
        minValue: 5,
        maxValue: 99,
        uiComponent: 'NUMBER',
        uiGroup: 'Security',
        uiOrder: 3,
    },
    // Performance Settings
    {
        key: 'accounting.performance.batch_size',
        name: 'Batch Processing Size',
        description: 'Number of records to process in each batch',
        module: configuration_entity_1.ConfigurationModule.ACCOUNTING,
        type: configuration_entity_1.ConfigurationType.SYSTEM,
        dataType: configuration_entity_1.ConfigurationDataType.NUMBER,
        defaultValue: '1000',
        minValue: 100,
        maxValue: 10000,
        uiComponent: 'NUMBER',
        uiGroup: 'Performance',
        uiOrder: 1,
    },
    {
        key: 'accounting.performance.cache_enabled',
        name: 'Enable Caching',
        description: 'Enable caching for improved performance',
        module: configuration_entity_1.ConfigurationModule.ACCOUNTING,
        type: configuration_entity_1.ConfigurationType.SYSTEM,
        dataType: configuration_entity_1.ConfigurationDataType.BOOLEAN,
        defaultValue: 'true',
        uiComponent: 'CHECKBOX',
        uiGroup: 'Performance',
        uiOrder: 2,
    },
    {
        key: 'accounting.performance.cache_ttl_minutes',
        name: 'Cache TTL (Minutes)',
        description: 'Time-to-live for cached data in minutes',
        module: configuration_entity_1.ConfigurationModule.ACCOUNTING,
        type: configuration_entity_1.ConfigurationType.SYSTEM,
        dataType: configuration_entity_1.ConfigurationDataType.NUMBER,
        defaultValue: '60',
        minValue: 5,
        maxValue: 1440,
        uiComponent: 'NUMBER',
        uiGroup: 'Performance',
        uiOrder: 3,
    },
    // Email Notifications
    {
        key: 'accounting.notifications.approval_required',
        name: 'Email for Approval Required',
        description: 'Send email when journal entries require approval',
        module: configuration_entity_1.ConfigurationModule.ACCOUNTING,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.BOOLEAN,
        defaultValue: 'true',
        uiComponent: 'CHECKBOX',
        uiGroup: 'Notifications',
        uiOrder: 1,
    },
    {
        key: 'accounting.notifications.period_close_reminder',
        name: 'Period Close Reminder',
        description: 'Send reminder emails before period close',
        module: configuration_entity_1.ConfigurationModule.ACCOUNTING,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.BOOLEAN,
        defaultValue: 'true',
        uiComponent: 'CHECKBOX',
        uiGroup: 'Notifications',
        uiOrder: 2,
    },
    {
        key: 'accounting.notifications.reminder_days_before_close',
        name: 'Reminder Days Before Close',
        description: 'Days before period end to send reminder',
        module: configuration_entity_1.ConfigurationModule.ACCOUNTING,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.NUMBER,
        defaultValue: '3',
        minValue: 1,
        maxValue: 10,
        uiComponent: 'NUMBER',
        uiGroup: 'Notifications',
        uiOrder: 3,
    },
];
//# sourceMappingURL=accounting-config.schema.js.map