import { ConfigurationModule, ConfigurationType, ConfigurationDataType } from '../entities/configuration.entity';

export const CRMConfigurationSchema = [
  // Customer Management
  {
    key: 'crm.customer.auto_numbering',
    name: 'Auto Customer Code Generation',
    description: 'Automatically generate customer codes',
    module: ConfigurationModule.CRM,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.BOOLEAN,
    defaultValue: 'true',
    uiComponent: 'CHECKBOX',
    uiGroup: 'Customer Management',
    uiOrder: 1,
  },
  {
    key: 'crm.customer.code_prefix',
    name: 'Customer Code Prefix',
    description: 'Prefix for customer codes',
    module: ConfigurationModule.CRM,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.STRING,
    defaultValue: 'CUS',
    uiComponent: 'INPUT',
    uiGroup: 'Customer Management',
    uiOrder: 2,
  },
  {
    key: 'crm.customer.duplicate_check_fields',
    name: 'Duplicate Check Fields',
    description: 'Fields to check for duplicate customers',
    module: ConfigurationModule.CRM,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.ARRAY,
    defaultValue: '["email", "phone", "tinNumber"]',
    uiComponent: 'MULTI_SELECT',
    uiGroup: 'Customer Management',
    uiOrder: 3,
    allowedValues: ['email', 'phone', 'tinNumber', 'ghanaCardNumber', 'businessRegistrationNumber'],
  },
  {
    key: 'crm.customer.mandatory_fields',
    name: 'Mandatory Customer Fields',
    description: 'Required fields for customer creation',
    module: ConfigurationModule.CRM,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.ARRAY,
    defaultValue: '["firstName", "lastName", "email", "phone", "billingAddress"]',
    uiComponent: 'MULTI_SELECT',
    uiGroup: 'Customer Management',
    uiOrder: 4,
  },

  // Customer Segmentation
  {
    key: 'crm.segmentation.ltv_thresholds',
    name: 'Lifetime Value Segmentation Thresholds',
    description: 'LTV thresholds for customer segmentation (JSON)',
    module: ConfigurationModule.CRM,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.JSON,
    defaultValue: '{"BRONZE": 50000, "SILVER": 100000, "GOLD": 500000, "PLATINUM": 1000000}',
    uiComponent: 'JSON_EDITOR',
    uiGroup: 'Segmentation',
    uiOrder: 1,
  },
  {
    key: 'crm.segmentation.auto_segmentation',
    name: 'Enable Auto Customer Segmentation',
    description: 'Automatically segment customers based on criteria',
    module: ConfigurationModule.CRM,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.BOOLEAN,
    defaultValue: 'true',
    uiComponent: 'CHECKBOX',
    uiGroup: 'Segmentation',
    uiOrder: 2,
  },
  {
    key: 'crm.segmentation.recalculation_frequency',
    name: 'Segmentation Recalculation Frequency',
    description: 'How often to recalculate customer segments',
    module: ConfigurationModule.CRM,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.STRING,
    defaultValue: 'MONTHLY',
    allowedValues: ['DAILY', 'WEEKLY', 'MONTHLY', 'QUARTERLY'],
    uiComponent: 'SELECT',
    uiGroup: 'Segmentation',
    uiOrder: 3,
  },
  {
    key: 'crm.segmentation.key_account_criteria',
    name: 'Key Account Criteria',
    description: 'Criteria for identifying key accounts (JSON)',
    module: ConfigurationModule.CRM,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.JSON,
    defaultValue: '{"minLTV": 500000, "minFleetSize": 50, "minMonthlyConsumption": 100000}',
    uiComponent: 'JSON_EDITOR',
    uiGroup: 'Segmentation',
    uiOrder: 4,
  },

  // Communication Preferences
  {
    key: 'crm.communication.default_preference',
    name: 'Default Communication Preference',
    description: 'Default communication method for new customers',
    module: ConfigurationModule.CRM,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.STRING,
    defaultValue: 'EMAIL',
    allowedValues: ['EMAIL', 'PHONE', 'SMS', 'WHATSAPP', 'IN_PERSON'],
    uiComponent: 'SELECT',
    uiGroup: 'Communication',
    uiOrder: 1,
  },
  {
    key: 'crm.communication.auto_opt_in_marketing',
    name: 'Auto Opt-in for Marketing',
    description: 'Automatically opt-in new customers for marketing communications',
    module: ConfigurationModule.CRM,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.BOOLEAN,
    defaultValue: 'false',
    uiComponent: 'CHECKBOX',
    uiGroup: 'Communication',
    uiOrder: 2,
  },
  {
    key: 'crm.communication.sms_provider',
    name: 'SMS Service Provider',
    description: 'Provider for SMS communications',
    module: ConfigurationModule.CRM,
    type: ConfigurationType.SYSTEM,
    dataType: ConfigurationDataType.STRING,
    defaultValue: 'HUBTEL',
    allowedValues: ['HUBTEL', 'VODAFONE', 'MTN', 'AIRTELTIGO', 'CUSTOM'],
    uiComponent: 'SELECT',
    uiGroup: 'Communication',
    uiOrder: 3,
  },
  {
    key: 'crm.communication.whatsapp_integration',
    name: 'Enable WhatsApp Integration',
    description: 'Enable WhatsApp Business API integration',
    module: ConfigurationModule.CRM,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.BOOLEAN,
    defaultValue: 'true',
    uiComponent: 'CHECKBOX',
    uiGroup: 'Communication',
    uiOrder: 4,
  },

  // Lead Management
  {
    key: 'crm.leads.auto_assignment',
    name: 'Auto-Assign Leads to Sales Reps',
    description: 'Automatically assign new leads to sales representatives',
    module: ConfigurationModule.CRM,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.BOOLEAN,
    defaultValue: 'true',
    uiComponent: 'CHECKBOX',
    uiGroup: 'Lead Management',
    uiOrder: 1,
  },
  {
    key: 'crm.leads.assignment_method',
    name: 'Lead Assignment Method',
    description: 'Method for assigning leads to sales reps',
    module: ConfigurationModule.CRM,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.STRING,
    defaultValue: 'ROUND_ROBIN',
    allowedValues: ['ROUND_ROBIN', 'TERRITORY_BASED', 'WORKLOAD_BASED', 'RANDOM'],
    uiComponent: 'SELECT',
    uiGroup: 'Lead Management',
    uiOrder: 2,
  },
  {
    key: 'crm.leads.qualification_criteria',
    name: 'Lead Qualification Criteria',
    description: 'Criteria for qualifying leads (JSON)',
    module: ConfigurationModule.CRM,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.JSON,
    defaultValue: '{"minBudget": 10000, "hasDecisionMaker": true, "timeframeDays": 90}',
    uiComponent: 'JSON_EDITOR',
    uiGroup: 'Lead Management',
    uiOrder: 3,
  },
  {
    key: 'crm.leads.follow_up_intervals',
    name: 'Follow-up Intervals (Days)',
    description: 'Automatic follow-up intervals for leads',
    module: ConfigurationModule.CRM,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.ARRAY,
    defaultValue: '[1, 3, 7, 14, 30]',
    uiComponent: 'TAGS',
    uiGroup: 'Lead Management',
    uiOrder: 4,
  },

  // Sales Process
  {
    key: 'crm.sales.pipeline_stages',
    name: 'Sales Pipeline Stages',
    description: 'Stages in the sales pipeline (JSON)',
    module: ConfigurationModule.CRM,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.JSON,
    defaultValue: '["PROSPECTING", "QUALIFICATION", "PROPOSAL", "NEGOTIATION", "CLOSING", "WON", "LOST"]',
    uiComponent: 'JSON_EDITOR',
    uiGroup: 'Sales Process',
    uiOrder: 1,
  },
  {
    key: 'crm.sales.stage_probabilities',
    name: 'Stage Win Probabilities',
    description: 'Win probability for each pipeline stage (JSON)',
    module: ConfigurationModule.CRM,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.JSON,
    defaultValue: '{"PROSPECTING": 10, "QUALIFICATION": 25, "PROPOSAL": 50, "NEGOTIATION": 75, "CLOSING": 90}',
    uiComponent: 'JSON_EDITOR',
    uiGroup: 'Sales Process',
    uiOrder: 2,
  },
  {
    key: 'crm.sales.auto_create_opportunities',
    name: 'Auto-Create Opportunities from Qualified Leads',
    description: 'Automatically create opportunities when leads are qualified',
    module: ConfigurationModule.CRM,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.BOOLEAN,
    defaultValue: 'true',
    uiComponent: 'CHECKBOX',
    uiGroup: 'Sales Process',
    uiOrder: 3,
  },
  {
    key: 'crm.sales.forecast_method',
    name: 'Sales Forecast Method',
    description: 'Method for calculating sales forecasts',
    module: ConfigurationModule.CRM,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.STRING,
    defaultValue: 'PROBABILITY_WEIGHTED',
    allowedValues: ['PROBABILITY_WEIGHTED', 'BEST_CASE', 'WORST_CASE', 'COMMITTED_ONLY'],
    uiComponent: 'SELECT',
    uiGroup: 'Sales Process',
    uiOrder: 4,
  },

  // Loyalty Program
  {
    key: 'crm.loyalty.program_enabled',
    name: 'Enable Loyalty Program',
    description: 'Enable customer loyalty program',
    module: ConfigurationModule.CRM,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.BOOLEAN,
    defaultValue: 'true',
    uiComponent: 'CHECKBOX',
    uiGroup: 'Loyalty Program',
    uiOrder: 1,
  },
  {
    key: 'crm.loyalty.points_per_currency_unit',
    name: 'Points per Currency Unit',
    description: 'Loyalty points earned per currency unit spent',
    module: ConfigurationModule.CRM,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.NUMBER,
    defaultValue: '1',
    minValue: 0.1,
    maxValue: 10,
    uiComponent: 'NUMBER',
    uiGroup: 'Loyalty Program',
    uiOrder: 2,
  },
  {
    key: 'crm.loyalty.tier_thresholds',
    name: 'Loyalty Tier Thresholds',
    description: 'Points required for each loyalty tier (JSON)',
    module: ConfigurationModule.CRM,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.JSON,
    defaultValue: '{"BRONZE": 1000, "SILVER": 5000, "GOLD": 25000, "PLATINUM": 100000}',
    uiComponent: 'JSON_EDITOR',
    uiGroup: 'Loyalty Program',
    uiOrder: 3,
  },
  {
    key: 'crm.loyalty.points_expiry_months',
    name: 'Points Expiry (Months)',
    description: 'Number of months before loyalty points expire',
    module: ConfigurationModule.CRM,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.NUMBER,
    defaultValue: '24',
    minValue: 6,
    maxValue: 60,
    uiComponent: 'NUMBER',
    uiGroup: 'Loyalty Program',
    uiOrder: 4,
  },
  {
    key: 'crm.loyalty.redemption_minimum',
    name: 'Minimum Points for Redemption',
    description: 'Minimum points required for redemption',
    module: ConfigurationModule.CRM,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.NUMBER,
    defaultValue: '100',
    minValue: 10,
    uiComponent: 'NUMBER',
    uiGroup: 'Loyalty Program',
    uiOrder: 5,
  },

  // Customer Service
  {
    key: 'crm.support.auto_ticket_assignment',
    name: 'Auto-Assign Support Tickets',
    description: 'Automatically assign support tickets to agents',
    module: ConfigurationModule.CRM,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.BOOLEAN,
    defaultValue: 'true',
    uiComponent: 'CHECKBOX',
    uiGroup: 'Customer Service',
    uiOrder: 1,
  },
  {
    key: 'crm.support.sla_response_hours',
    name: 'SLA Response Time (Hours)',
    description: 'Standard response time for support tickets',
    module: ConfigurationModule.CRM,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.JSON,
    defaultValue: '{"LOW": 48, "MEDIUM": 24, "HIGH": 8, "CRITICAL": 2}',
    uiComponent: 'JSON_EDITOR',
    uiGroup: 'Customer Service',
    uiOrder: 2,
  },
  {
    key: 'crm.support.escalation_enabled',
    name: 'Enable Ticket Escalation',
    description: 'Automatically escalate overdue tickets',
    module: ConfigurationModule.CRM,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.BOOLEAN,
    defaultValue: 'true',
    uiComponent: 'CHECKBOX',
    uiGroup: 'Customer Service',
    uiOrder: 3,
  },
  {
    key: 'crm.support.satisfaction_survey',
    name: 'Send Satisfaction Surveys',
    description: 'Send customer satisfaction surveys after ticket resolution',
    module: ConfigurationModule.CRM,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.BOOLEAN,
    defaultValue: 'true',
    uiComponent: 'CHECKBOX',
    uiGroup: 'Customer Service',
    uiOrder: 4,
  },

  // Analytics and Reporting
  {
    key: 'crm.analytics.churn_prediction_enabled',
    name: 'Enable Churn Prediction',
    description: 'Use AI to predict customer churn',
    module: ConfigurationModule.CRM,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.BOOLEAN,
    defaultValue: 'true',
    uiComponent: 'CHECKBOX',
    uiGroup: 'Analytics',
    uiOrder: 1,
  },
  {
    key: 'crm.analytics.clv_calculation_method',
    name: 'CLV Calculation Method',
    description: 'Method for calculating customer lifetime value',
    module: ConfigurationModule.CRM,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.STRING,
    defaultValue: 'PREDICTIVE',
    allowedValues: ['HISTORICAL', 'PREDICTIVE', 'TRADITIONAL'],
    uiComponent: 'SELECT',
    uiGroup: 'Analytics',
    uiOrder: 2,
  },
  {
    key: 'crm.analytics.rfm_weights',
    name: 'RFM Analysis Weights',
    description: 'Weights for Recency, Frequency, Monetary analysis (JSON)',
    module: ConfigurationModule.CRM,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.JSON,
    defaultValue: '{"recency": 0.33, "frequency": 0.33, "monetary": 0.34}',
    uiComponent: 'JSON_EDITOR',
    uiGroup: 'Analytics',
    uiOrder: 3,
  },
  {
    key: 'crm.analytics.dashboard_refresh_minutes',
    name: 'Dashboard Refresh Interval (Minutes)',
    description: 'How often to refresh CRM dashboards',
    module: ConfigurationModule.CRM,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.NUMBER,
    defaultValue: '15',
    minValue: 5,
    maxValue: 60,
    uiComponent: 'NUMBER',
    uiGroup: 'Analytics',
    uiOrder: 4,
  },

  // Data Management
  {
    key: 'crm.data.duplicate_merge_auto',
    name: 'Auto-Merge Duplicate Customers',
    description: 'Automatically merge duplicate customer records',
    module: ConfigurationModule.CRM,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.BOOLEAN,
    defaultValue: 'false',
    uiComponent: 'CHECKBOX',
    uiGroup: 'Data Management',
    uiOrder: 1,
  },
  {
    key: 'crm.data.duplicate_confidence_threshold',
    name: 'Duplicate Confidence Threshold',
    description: 'Confidence threshold for duplicate detection (0-100)',
    module: ConfigurationModule.CRM,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.NUMBER,
    defaultValue: '85',
    minValue: 50,
    maxValue: 100,
    uiComponent: 'SLIDER',
    uiGroup: 'Data Management',
    uiOrder: 2,
  },
  {
    key: 'crm.data.data_quality_score_enabled',
    name: 'Enable Data Quality Scoring',
    description: 'Calculate data quality scores for customers',
    module: ConfigurationModule.CRM,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.BOOLEAN,
    defaultValue: 'true',
    uiComponent: 'CHECKBOX',
    uiGroup: 'Data Management',
    uiOrder: 3,
  },
  {
    key: 'crm.data.inactive_customer_months',
    name: 'Inactive Customer Period (Months)',
    description: 'Months without activity to mark customer as inactive',
    module: ConfigurationModule.CRM,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.NUMBER,
    defaultValue: '12',
    minValue: 3,
    maxValue: 36,
    uiComponent: 'NUMBER',
    uiGroup: 'Data Management',
    uiOrder: 4,
  },

  // Privacy and Compliance
  {
    key: 'crm.privacy.gdpr_enabled',
    name: 'Enable GDPR Compliance',
    description: 'Enable GDPR compliance features',
    module: ConfigurationModule.CRM,
    type: ConfigurationType.SYSTEM,
    dataType: ConfigurationDataType.BOOLEAN,
    defaultValue: 'true',
    uiComponent: 'CHECKBOX',
    uiGroup: 'Privacy & Compliance',
    uiOrder: 1,
  },
  {
    key: 'crm.privacy.consent_required',
    name: 'Require Marketing Consent',
    description: 'Require explicit consent for marketing communications',
    module: ConfigurationModule.CRM,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.BOOLEAN,
    defaultValue: 'true',
    uiComponent: 'CHECKBOX',
    uiGroup: 'Privacy & Compliance',
    uiOrder: 2,
  },
  {
    key: 'crm.privacy.data_retention_years',
    name: 'Customer Data Retention (Years)',
    description: 'Years to retain customer data after last interaction',
    module: ConfigurationModule.CRM,
    type: ConfigurationType.SYSTEM,
    dataType: ConfigurationDataType.NUMBER,
    defaultValue: '7',
    minValue: 1,
    maxValue: 20,
    uiComponent: 'NUMBER',
    uiGroup: 'Privacy & Compliance',
    uiOrder: 3,
  },

  // Mobile App Integration
  {
    key: 'crm.mobile.customer_app_enabled',
    name: 'Enable Customer Mobile App',
    description: 'Enable mobile app for customers',
    module: ConfigurationModule.CRM,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.BOOLEAN,
    defaultValue: 'true',
    uiComponent: 'CHECKBOX',
    uiGroup: 'Mobile Integration',
    uiOrder: 1,
  },
  {
    key: 'crm.mobile.push_notifications_enabled',
    name: 'Enable Push Notifications',
    description: 'Send push notifications to customer mobile app',
    module: ConfigurationModule.CRM,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.BOOLEAN,
    defaultValue: 'true',
    uiComponent: 'CHECKBOX',
    uiGroup: 'Mobile Integration',
    uiOrder: 2,
  },
  {
    key: 'crm.mobile.location_tracking',
    name: 'Enable Location Tracking',
    description: 'Track customer locations for nearby services',
    module: ConfigurationModule.CRM,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.BOOLEAN,
    defaultValue: 'false',
    uiComponent: 'CHECKBOX',
    uiGroup: 'Mobile Integration',
    uiOrder: 3,
  },

  // Territory Management
  {
    key: 'crm.territory.auto_assignment',
    name: 'Auto-Assign Territories',
    description: 'Automatically assign customers to territories based on location',
    module: ConfigurationModule.CRM,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.BOOLEAN,
    defaultValue: 'true',
    uiComponent: 'CHECKBOX',
    uiGroup: 'Territory Management',
    uiOrder: 1,
  },
  {
    key: 'crm.territory.assignment_criteria',
    name: 'Territory Assignment Criteria',
    description: 'Criteria for territory assignment (JSON)',
    module: ConfigurationModule.CRM,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.JSON,
    defaultValue: '{"primaryField": "region", "secondaryField": "district", "fallbackField": "city"}',
    uiComponent: 'JSON_EDITOR',
    uiGroup: 'Territory Management',
    uiOrder: 2,
  },
];