"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DealerConfigurationSchema = void 0;
const configuration_entity_1 = require("../entities/configuration.entity");
exports.DealerConfigurationSchema = [
    // General Dealer Configuration
    {
        key: 'dealer.general.auto_onboarding_enabled',
        name: 'Auto Dealer Onboarding Enabled',
        description: 'Enable automated dealer onboarding process',
        module: configuration_entity_1.ConfigurationModule.DEALER_MANAGEMENT,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.BOOLEAN,
        defaultValue: 'false',
        uiComponent: 'CHECKBOX',
        uiGroup: 'General',
        uiOrder: 1,
        impactLevel: 'HIGH',
    },
    {
        key: 'dealer.general.default_dealer_type',
        name: 'Default Dealer Type',
        description: 'Default type for new dealers',
        module: configuration_entity_1.ConfigurationModule.DEALER_MANAGEMENT,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.STRING,
        defaultValue: 'RETAIL',
        allowedValues: ['RETAIL', 'WHOLESALE', 'INDUSTRIAL', 'MARINE', 'AVIATION'],
        uiComponent: 'SELECT',
        uiGroup: 'General',
        uiOrder: 2,
    },
    {
        key: 'dealer.general.dealer_code_format',
        name: 'Dealer Code Format',
        description: 'Format for generating dealer codes (A=Alpha, N=Numeric)',
        module: configuration_entity_1.ConfigurationModule.DEALER_MANAGEMENT,
        type: configuration_entity_1.ConfigurationType.SYSTEM,
        dataType: configuration_entity_1.ConfigurationDataType.STRING,
        defaultValue: 'DLR-NNNNN',
        regexPattern: '^[A-Z-N]+$',
        uiComponent: 'INPUT',
        uiGroup: 'General',
        uiOrder: 3,
    },
    {
        key: 'dealer.general.auto_generate_dealer_codes',
        name: 'Auto Generate Dealer Codes',
        description: 'Automatically generate dealer codes',
        module: configuration_entity_1.ConfigurationModule.DEALER_MANAGEMENT,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.BOOLEAN,
        defaultValue: 'true',
        uiComponent: 'CHECKBOX',
        uiGroup: 'General',
        uiOrder: 4,
    },
    {
        key: 'dealer.general.require_gps_coordinates',
        name: 'Require GPS Coordinates',
        description: 'Require GPS coordinates for dealer locations',
        module: configuration_entity_1.ConfigurationModule.DEALER_MANAGEMENT,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.BOOLEAN,
        defaultValue: 'true',
        uiComponent: 'CHECKBOX',
        uiGroup: 'General',
        uiOrder: 5,
    },
    // Dealer Registration Configuration
    {
        key: 'dealer.registration.require_tin_number',
        name: 'Require TIN Number',
        description: 'Require Tax Identification Number for dealer registration',
        module: configuration_entity_1.ConfigurationModule.DEALER_MANAGEMENT,
        type: configuration_entity_1.ConfigurationType.SYSTEM,
        dataType: configuration_entity_1.ConfigurationDataType.BOOLEAN,
        defaultValue: 'true',
        isRequired: true,
        uiComponent: 'CHECKBOX',
        uiGroup: 'Registration',
        uiOrder: 1,
    },
    {
        key: 'dealer.registration.require_business_registration',
        name: 'Require Business Registration',
        description: 'Require business registration certificate',
        module: configuration_entity_1.ConfigurationModule.DEALER_MANAGEMENT,
        type: configuration_entity_1.ConfigurationType.SYSTEM,
        dataType: configuration_entity_1.ConfigurationDataType.BOOLEAN,
        defaultValue: 'true',
        uiComponent: 'CHECKBOX',
        uiGroup: 'Registration',
        uiOrder: 2,
    },
    {
        key: 'dealer.registration.require_npa_license',
        name: 'Require NPA License',
        description: 'Require valid NPA retail license',
        module: configuration_entity_1.ConfigurationModule.DEALER_MANAGEMENT,
        type: configuration_entity_1.ConfigurationType.SYSTEM,
        dataType: configuration_entity_1.ConfigurationDataType.BOOLEAN,
        defaultValue: 'true',
        uiComponent: 'CHECKBOX',
        uiGroup: 'Registration',
        uiOrder: 3,
    },
    {
        key: 'dealer.registration.require_fire_certificate',
        name: 'Require Fire Certificate',
        description: 'Require fire safety certificate',
        module: configuration_entity_1.ConfigurationModule.DEALER_MANAGEMENT,
        type: configuration_entity_1.ConfigurationType.SYSTEM,
        dataType: configuration_entity_1.ConfigurationDataType.BOOLEAN,
        defaultValue: 'true',
        uiComponent: 'CHECKBOX',
        uiGroup: 'Registration',
        uiOrder: 4,
    },
    {
        key: 'dealer.registration.require_environmental_permit',
        name: 'Require Environmental Permit',
        description: 'Require environmental protection permit',
        module: configuration_entity_1.ConfigurationModule.DEALER_MANAGEMENT,
        type: configuration_entity_1.ConfigurationType.SYSTEM,
        dataType: configuration_entity_1.ConfigurationDataType.BOOLEAN,
        defaultValue: 'true',
        uiComponent: 'CHECKBOX',
        uiGroup: 'Registration',
        uiOrder: 5,
    },
    {
        key: 'dealer.registration.document_expiry_reminder_days',
        name: 'Document Expiry Reminder (Days)',
        description: 'Days before document expiry to send reminders',
        module: configuration_entity_1.ConfigurationModule.DEALER_MANAGEMENT,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.NUMBER,
        defaultValue: '30',
        minValue: 7,
        maxValue: 90,
        uiComponent: 'NUMBER',
        uiGroup: 'Registration',
        uiOrder: 6,
    },
    {
        key: 'dealer.registration.auto_suspend_on_expiry',
        name: 'Auto Suspend on Document Expiry',
        description: 'Automatically suspend dealer when documents expire',
        module: configuration_entity_1.ConfigurationModule.DEALER_MANAGEMENT,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.BOOLEAN,
        defaultValue: 'true',
        uiComponent: 'CHECKBOX',
        uiGroup: 'Registration',
        uiOrder: 7,
    },
    // Credit Management Configuration
    {
        key: 'dealer.credit.enable_credit_limits',
        name: 'Enable Credit Limits',
        description: 'Enable credit limit management for dealers',
        module: configuration_entity_1.ConfigurationModule.DEALER_MANAGEMENT,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.BOOLEAN,
        defaultValue: 'true',
        uiComponent: 'CHECKBOX',
        uiGroup: 'Credit Management',
        uiOrder: 1,
    },
    {
        key: 'dealer.credit.default_credit_limit',
        name: 'Default Credit Limit (GHS)',
        description: 'Default credit limit for new dealers',
        module: configuration_entity_1.ConfigurationModule.DEALER_MANAGEMENT,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.NUMBER,
        defaultValue: '50000.00',
        minValue: 0,
        maxValue: 10000000,
        uiComponent: 'NUMBER',
        uiGroup: 'Credit Management',
        uiOrder: 2,
    },
    {
        key: 'dealer.credit.credit_assessment_period_days',
        name: 'Credit Assessment Period (Days)',
        description: 'Period for initial credit assessment',
        module: configuration_entity_1.ConfigurationModule.DEALER_MANAGEMENT,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.NUMBER,
        defaultValue: '30',
        minValue: 7,
        maxValue: 90,
        uiComponent: 'NUMBER',
        uiGroup: 'Credit Management',
        uiOrder: 3,
    },
    {
        key: 'dealer.credit.credit_review_frequency_months',
        name: 'Credit Review Frequency (Months)',
        description: 'How often to review credit limits',
        module: configuration_entity_1.ConfigurationModule.DEALER_MANAGEMENT,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.NUMBER,
        defaultValue: '6',
        minValue: 1,
        maxValue: 24,
        uiComponent: 'NUMBER',
        uiGroup: 'Credit Management',
        uiOrder: 4,
    },
    {
        key: 'dealer.credit.credit_utilization_alert_threshold',
        name: 'Credit Utilization Alert Threshold (%)',
        description: 'Credit utilization percentage to trigger alerts',
        module: configuration_entity_1.ConfigurationModule.DEALER_MANAGEMENT,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.NUMBER,
        defaultValue: '80.0',
        minValue: 50,
        maxValue: 99,
        uiComponent: 'NUMBER',
        uiGroup: 'Credit Management',
        uiOrder: 5,
    },
    {
        key: 'dealer.credit.credit_stop_threshold',
        name: 'Credit Stop Threshold (%)',
        description: 'Credit utilization percentage to stop further credit',
        module: configuration_entity_1.ConfigurationModule.DEALER_MANAGEMENT,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.NUMBER,
        defaultValue: '95.0',
        minValue: 80,
        maxValue: 100,
        uiComponent: 'NUMBER',
        uiGroup: 'Credit Management',
        uiOrder: 6,
    },
    {
        key: 'dealer.credit.require_guarantor_above_limit',
        name: 'Credit Limit Requiring Guarantor (GHS)',
        description: 'Credit limit above which guarantor is required',
        module: configuration_entity_1.ConfigurationModule.DEALER_MANAGEMENT,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.NUMBER,
        defaultValue: '200000.00',
        minValue: 0,
        maxValue: 10000000,
        uiComponent: 'NUMBER',
        uiGroup: 'Credit Management',
        uiOrder: 7,
    },
    // Payment Terms Configuration
    {
        key: 'dealer.payment.default_payment_terms_days',
        name: 'Default Payment Terms (Days)',
        description: 'Default payment terms for new dealers',
        module: configuration_entity_1.ConfigurationModule.DEALER_MANAGEMENT,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.NUMBER,
        defaultValue: '30',
        minValue: 0,
        maxValue: 90,
        uiComponent: 'NUMBER',
        uiGroup: 'Payment Terms',
        uiOrder: 1,
    },
    {
        key: 'dealer.payment.cash_dealer_discount_percentage',
        name: 'Cash Dealer Discount (%)',
        description: 'Discount percentage for cash-only dealers',
        module: configuration_entity_1.ConfigurationModule.DEALER_MANAGEMENT,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.NUMBER,
        defaultValue: '0.5',
        minValue: 0,
        maxValue: 5,
        uiComponent: 'NUMBER',
        uiGroup: 'Payment Terms',
        uiOrder: 2,
    },
    {
        key: 'dealer.payment.early_payment_discount_days',
        name: 'Early Payment Discount Period (Days)',
        description: 'Days within which payment qualifies for early discount',
        module: configuration_entity_1.ConfigurationModule.DEALER_MANAGEMENT,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.NUMBER,
        defaultValue: '10',
        minValue: 1,
        maxValue: 30,
        uiComponent: 'NUMBER',
        uiGroup: 'Payment Terms',
        uiOrder: 3,
    },
    {
        key: 'dealer.payment.early_payment_discount_percentage',
        name: 'Early Payment Discount (%)',
        description: 'Discount percentage for early payments',
        module: configuration_entity_1.ConfigurationModule.DEALER_MANAGEMENT,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.NUMBER,
        defaultValue: '2.0',
        minValue: 0,
        maxValue: 10,
        uiComponent: 'NUMBER',
        uiGroup: 'Payment Terms',
        uiOrder: 4,
    },
    {
        key: 'dealer.payment.overdue_interest_rate_annual',
        name: 'Overdue Interest Rate (Annual %)',
        description: 'Annual interest rate for overdue payments',
        module: configuration_entity_1.ConfigurationModule.DEALER_MANAGEMENT,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.NUMBER,
        defaultValue: '18.0',
        minValue: 0,
        maxValue: 50,
        uiComponent: 'NUMBER',
        uiGroup: 'Payment Terms',
        uiOrder: 5,
    },
    {
        key: 'dealer.payment.grace_period_days',
        name: 'Payment Grace Period (Days)',
        description: 'Grace period after due date before penalties apply',
        module: configuration_entity_1.ConfigurationModule.DEALER_MANAGEMENT,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.NUMBER,
        defaultValue: '5',
        minValue: 0,
        maxValue: 15,
        uiComponent: 'NUMBER',
        uiGroup: 'Payment Terms',
        uiOrder: 6,
    },
    // Performance Monitoring Configuration
    {
        key: 'dealer.performance.enable_performance_monitoring',
        name: 'Enable Performance Monitoring',
        description: 'Enable dealer performance monitoring and scoring',
        module: configuration_entity_1.ConfigurationModule.DEALER_MANAGEMENT,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.BOOLEAN,
        defaultValue: 'true',
        uiComponent: 'CHECKBOX',
        uiGroup: 'Performance',
        uiOrder: 1,
    },
    {
        key: 'dealer.performance.sales_target_review_frequency',
        name: 'Sales Target Review Frequency',
        description: 'How often to review dealer sales targets',
        module: configuration_entity_1.ConfigurationModule.DEALER_MANAGEMENT,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.STRING,
        defaultValue: 'MONTHLY',
        allowedValues: ['WEEKLY', 'MONTHLY', 'QUARTERLY', 'ANNUALLY'],
        uiComponent: 'SELECT',
        uiGroup: 'Performance',
        uiOrder: 2,
    },
    {
        key: 'dealer.performance.minimum_monthly_volume_litres',
        name: 'Minimum Monthly Volume (Litres)',
        description: 'Minimum monthly volume required to maintain active status',
        module: configuration_entity_1.ConfigurationModule.DEALER_MANAGEMENT,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.NUMBER,
        defaultValue: '10000',
        minValue: 1000,
        maxValue: 1000000,
        uiComponent: 'NUMBER',
        uiGroup: 'Performance',
        uiOrder: 3,
    },
    {
        key: 'dealer.performance.performance_score_weight_sales',
        name: 'Performance Score Weight - Sales (%)',
        description: 'Weight of sales performance in overall score',
        module: configuration_entity_1.ConfigurationModule.DEALER_MANAGEMENT,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.NUMBER,
        defaultValue: '40.0',
        minValue: 0,
        maxValue: 100,
        uiComponent: 'NUMBER',
        uiGroup: 'Performance',
        uiOrder: 4,
    },
    {
        key: 'dealer.performance.performance_score_weight_payment',
        name: 'Performance Score Weight - Payment (%)',
        description: 'Weight of payment performance in overall score',
        module: configuration_entity_1.ConfigurationModule.DEALER_MANAGEMENT,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.NUMBER,
        defaultValue: '30.0',
        minValue: 0,
        maxValue: 100,
        uiComponent: 'NUMBER',
        uiGroup: 'Performance',
        uiOrder: 5,
    },
    {
        key: 'dealer.performance.performance_score_weight_compliance',
        name: 'Performance Score Weight - Compliance (%)',
        description: 'Weight of compliance performance in overall score',
        module: configuration_entity_1.ConfigurationModule.DEALER_MANAGEMENT,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.NUMBER,
        defaultValue: '30.0',
        minValue: 0,
        maxValue: 100,
        uiComponent: 'NUMBER',
        uiGroup: 'Performance',
        uiOrder: 6,
    },
    {
        key: 'dealer.performance.poor_performance_threshold',
        name: 'Poor Performance Threshold (%)',
        description: 'Performance score threshold for poor performance',
        module: configuration_entity_1.ConfigurationModule.DEALER_MANAGEMENT,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.NUMBER,
        defaultValue: '60.0',
        minValue: 0,
        maxValue: 100,
        uiComponent: 'NUMBER',
        uiGroup: 'Performance',
        uiOrder: 7,
    },
    // Incentive and Commission Configuration
    {
        key: 'dealer.incentive.enable_volume_incentives',
        name: 'Enable Volume Incentives',
        description: 'Enable volume-based incentive programs for dealers',
        module: configuration_entity_1.ConfigurationModule.DEALER_MANAGEMENT,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.BOOLEAN,
        defaultValue: 'true',
        uiComponent: 'CHECKBOX',
        uiGroup: 'Incentives',
        uiOrder: 1,
    },
    {
        key: 'dealer.incentive.tier1_volume_threshold_litres',
        name: 'Tier 1 Volume Threshold (Litres)',
        description: 'Monthly volume threshold for tier 1 incentives',
        module: configuration_entity_1.ConfigurationModule.DEALER_MANAGEMENT,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.NUMBER,
        defaultValue: '50000',
        minValue: 10000,
        maxValue: 1000000,
        uiComponent: 'NUMBER',
        uiGroup: 'Incentives',
        uiOrder: 2,
    },
    {
        key: 'dealer.incentive.tier1_incentive_per_litre',
        name: 'Tier 1 Incentive (GHS per Litre)',
        description: 'Incentive amount per litre for tier 1 volume',
        module: configuration_entity_1.ConfigurationModule.DEALER_MANAGEMENT,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.NUMBER,
        defaultValue: '0.02',
        minValue: 0,
        maxValue: 1,
        uiComponent: 'NUMBER',
        uiGroup: 'Incentives',
        uiOrder: 3,
    },
    {
        key: 'dealer.incentive.tier2_volume_threshold_litres',
        name: 'Tier 2 Volume Threshold (Litres)',
        description: 'Monthly volume threshold for tier 2 incentives',
        module: configuration_entity_1.ConfigurationModule.DEALER_MANAGEMENT,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.NUMBER,
        defaultValue: '100000',
        minValue: 50000,
        maxValue: 2000000,
        uiComponent: 'NUMBER',
        uiGroup: 'Incentives',
        uiOrder: 4,
    },
    {
        key: 'dealer.incentive.tier2_incentive_per_litre',
        name: 'Tier 2 Incentive (GHS per Litre)',
        description: 'Incentive amount per litre for tier 2 volume',
        module: configuration_entity_1.ConfigurationModule.DEALER_MANAGEMENT,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.NUMBER,
        defaultValue: '0.05',
        minValue: 0,
        maxValue: 1,
        uiComponent: 'NUMBER',
        uiGroup: 'Incentives',
        uiOrder: 5,
    },
    {
        key: 'dealer.incentive.loyalty_bonus_months',
        name: 'Loyalty Bonus Qualification (Months)',
        description: 'Months of consistent performance for loyalty bonus',
        module: configuration_entity_1.ConfigurationModule.DEALER_MANAGEMENT,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.NUMBER,
        defaultValue: '12',
        minValue: 6,
        maxValue: 36,
        uiComponent: 'NUMBER',
        uiGroup: 'Incentives',
        uiOrder: 6,
    },
    {
        key: 'dealer.incentive.loyalty_bonus_percentage',
        name: 'Loyalty Bonus Percentage',
        description: 'Additional bonus percentage for loyal dealers',
        module: configuration_entity_1.ConfigurationModule.DEALER_MANAGEMENT,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.NUMBER,
        defaultValue: '5.0',
        minValue: 0,
        maxValue: 20,
        uiComponent: 'NUMBER',
        uiGroup: 'Incentives',
        uiOrder: 7,
    },
    // Territory Management Configuration
    {
        key: 'dealer.territory.enable_territory_management',
        name: 'Enable Territory Management',
        description: 'Enable dealer territory assignment and management',
        module: configuration_entity_1.ConfigurationModule.DEALER_MANAGEMENT,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.BOOLEAN,
        defaultValue: 'true',
        uiComponent: 'CHECKBOX',
        uiGroup: 'Territory',
        uiOrder: 1,
    },
    {
        key: 'dealer.territory.exclusive_territory_radius_km',
        name: 'Exclusive Territory Radius (KM)',
        description: 'Radius for exclusive dealer territories in kilometers',
        module: configuration_entity_1.ConfigurationModule.DEALER_MANAGEMENT,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.NUMBER,
        defaultValue: '5.0',
        minValue: 1,
        maxValue: 50,
        uiComponent: 'NUMBER',
        uiGroup: 'Territory',
        uiOrder: 2,
    },
    {
        key: 'dealer.territory.allow_territory_overlap',
        name: 'Allow Territory Overlap',
        description: 'Allow overlapping dealer territories',
        module: configuration_entity_1.ConfigurationModule.DEALER_MANAGEMENT,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.BOOLEAN,
        defaultValue: 'false',
        uiComponent: 'CHECKBOX',
        uiGroup: 'Territory',
        uiOrder: 3,
    },
    {
        key: 'dealer.territory.territory_violation_penalty',
        name: 'Territory Violation Penalty (GHS)',
        description: 'Penalty amount for territory violations',
        module: configuration_entity_1.ConfigurationModule.DEALER_MANAGEMENT,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.NUMBER,
        defaultValue: '5000.00',
        minValue: 0,
        maxValue: 100000,
        uiComponent: 'NUMBER',
        uiGroup: 'Territory',
        uiOrder: 4,
    },
    // Reporting and Analytics Configuration
    {
        key: 'dealer.reporting.auto_generate_monthly_reports',
        name: 'Auto Generate Monthly Reports',
        description: 'Automatically generate monthly dealer reports',
        module: configuration_entity_1.ConfigurationModule.DEALER_MANAGEMENT,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.BOOLEAN,
        defaultValue: 'true',
        uiComponent: 'CHECKBOX',
        uiGroup: 'Reporting',
        uiOrder: 1,
    },
    {
        key: 'dealer.reporting.include_performance_metrics',
        name: 'Include Performance Metrics',
        description: 'Include detailed performance metrics in reports',
        module: configuration_entity_1.ConfigurationModule.DEALER_MANAGEMENT,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.BOOLEAN,
        defaultValue: 'true',
        uiComponent: 'CHECKBOX',
        uiGroup: 'Reporting',
        uiOrder: 2,
    },
    {
        key: 'dealer.reporting.include_financial_summary',
        name: 'Include Financial Summary',
        description: 'Include financial summary in dealer reports',
        module: configuration_entity_1.ConfigurationModule.DEALER_MANAGEMENT,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.BOOLEAN,
        defaultValue: 'true',
        uiComponent: 'CHECKBOX',
        uiGroup: 'Reporting',
        uiOrder: 3,
    },
    {
        key: 'dealer.reporting.report_retention_months',
        name: 'Report Retention (Months)',
        description: 'Number of months to retain dealer reports',
        module: configuration_entity_1.ConfigurationModule.DEALER_MANAGEMENT,
        type: configuration_entity_1.ConfigurationType.SYSTEM,
        dataType: configuration_entity_1.ConfigurationDataType.NUMBER,
        defaultValue: '36',
        minValue: 12,
        maxValue: 120,
        uiComponent: 'NUMBER',
        uiGroup: 'Reporting',
        uiOrder: 4,
    },
    // Notification Configuration
    {
        key: 'dealer.notifications.new_dealer_registration',
        name: 'New Dealer Registration Notifications',
        description: 'Send notifications for new dealer registrations',
        module: configuration_entity_1.ConfigurationModule.DEALER_MANAGEMENT,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.BOOLEAN,
        defaultValue: 'true',
        uiComponent: 'CHECKBOX',
        uiGroup: 'Notifications',
        uiOrder: 1,
    },
    {
        key: 'dealer.notifications.credit_limit_exceeded',
        name: 'Credit Limit Exceeded Notifications',
        description: 'Send notifications when credit limits are exceeded',
        module: configuration_entity_1.ConfigurationModule.DEALER_MANAGEMENT,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.BOOLEAN,
        defaultValue: 'true',
        uiComponent: 'CHECKBOX',
        uiGroup: 'Notifications',
        uiOrder: 2,
    },
    {
        key: 'dealer.notifications.document_expiry_reminder',
        name: 'Document Expiry Reminders',
        description: 'Send reminders for expiring dealer documents',
        module: configuration_entity_1.ConfigurationModule.DEALER_MANAGEMENT,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.BOOLEAN,
        defaultValue: 'true',
        uiComponent: 'CHECKBOX',
        uiGroup: 'Notifications',
        uiOrder: 3,
    },
    {
        key: 'dealer.notifications.poor_performance_alerts',
        name: 'Poor Performance Alerts',
        description: 'Send alerts for dealers with poor performance',
        module: configuration_entity_1.ConfigurationModule.DEALER_MANAGEMENT,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.BOOLEAN,
        defaultValue: 'true',
        uiComponent: 'CHECKBOX',
        uiGroup: 'Notifications',
        uiOrder: 4,
    },
    {
        key: 'dealer.notifications.email_recipients',
        name: 'Notification Email Recipients',
        description: 'Email addresses for dealer management notifications',
        module: configuration_entity_1.ConfigurationModule.DEALER_MANAGEMENT,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.ARRAY,
        defaultValue: '[]',
        uiComponent: 'MULTI_INPUT',
        uiGroup: 'Notifications',
        uiOrder: 5,
    },
    // Security and Compliance Configuration
    {
        key: 'dealer.security.require_2fa_for_high_value',
        name: 'Require 2FA for High Value Transactions',
        description: 'Require two-factor authentication for high-value dealer transactions',
        module: configuration_entity_1.ConfigurationModule.DEALER_MANAGEMENT,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.BOOLEAN,
        defaultValue: 'true',
        uiComponent: 'CHECKBOX',
        uiGroup: 'Security',
        uiOrder: 1,
    },
    {
        key: 'dealer.security.high_value_transaction_threshold',
        name: 'High Value Transaction Threshold (GHS)',
        description: 'Transaction amount requiring additional security',
        module: configuration_entity_1.ConfigurationModule.DEALER_MANAGEMENT,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.NUMBER,
        defaultValue: '100000.00',
        minValue: 10000,
        maxValue: 1000000,
        uiComponent: 'NUMBER',
        uiGroup: 'Security',
        uiOrder: 2,
    },
    {
        key: 'dealer.security.audit_all_dealer_changes',
        name: 'Audit All Dealer Changes',
        description: 'Log all changes to dealer information',
        module: configuration_entity_1.ConfigurationModule.DEALER_MANAGEMENT,
        type: configuration_entity_1.ConfigurationType.SYSTEM,
        dataType: configuration_entity_1.ConfigurationDataType.BOOLEAN,
        defaultValue: 'true',
        uiComponent: 'CHECKBOX',
        uiGroup: 'Security',
        uiOrder: 3,
    },
    {
        key: 'dealer.security.session_timeout_minutes',
        name: 'Dealer Portal Session Timeout (Minutes)',
        description: 'Session timeout for dealer portal access',
        module: configuration_entity_1.ConfigurationModule.DEALER_MANAGEMENT,
        type: configuration_entity_1.ConfigurationType.SYSTEM,
        dataType: configuration_entity_1.ConfigurationDataType.NUMBER,
        defaultValue: '30',
        minValue: 10,
        maxValue: 480,
        uiComponent: 'NUMBER',
        uiGroup: 'Security',
        uiOrder: 4,
    },
    // Integration Configuration
    {
        key: 'dealer.integration.enable_npa_sync',
        name: 'Enable NPA Dealer Sync',
        description: 'Synchronize dealer information with NPA database',
        module: configuration_entity_1.ConfigurationModule.DEALER_MANAGEMENT,
        type: configuration_entity_1.ConfigurationType.SYSTEM,
        dataType: configuration_entity_1.ConfigurationDataType.BOOLEAN,
        defaultValue: 'true',
        uiComponent: 'CHECKBOX',
        uiGroup: 'Integration',
        uiOrder: 1,
    },
    {
        key: 'dealer.integration.sync_frequency_hours',
        name: 'Sync Frequency (Hours)',
        description: 'Frequency for syncing dealer data with external systems',
        module: configuration_entity_1.ConfigurationModule.DEALER_MANAGEMENT,
        type: configuration_entity_1.ConfigurationType.SYSTEM,
        dataType: configuration_entity_1.ConfigurationDataType.NUMBER,
        defaultValue: '24',
        minValue: 1,
        maxValue: 168,
        uiComponent: 'NUMBER',
        uiGroup: 'Integration',
        uiOrder: 2,
    },
    {
        key: 'dealer.integration.enable_mobile_app_integration',
        name: 'Enable Mobile App Integration',
        description: 'Enable integration with dealer mobile applications',
        module: configuration_entity_1.ConfigurationModule.DEALER_MANAGEMENT,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.BOOLEAN,
        defaultValue: 'true',
        uiComponent: 'CHECKBOX',
        uiGroup: 'Integration',
        uiOrder: 3,
    },
    {
        key: 'dealer.integration.enable_pos_integration',
        name: 'Enable POS Integration',
        description: 'Enable integration with dealer point-of-sale systems',
        module: configuration_entity_1.ConfigurationModule.DEALER_MANAGEMENT,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.BOOLEAN,
        defaultValue: 'true',
        uiComponent: 'CHECKBOX',
        uiGroup: 'Integration',
        uiOrder: 4,
    },
    // Data Management Configuration
    {
        key: 'dealer.data.enable_data_archiving',
        name: 'Enable Data Archiving',
        description: 'Enable automatic archiving of old dealer data',
        module: configuration_entity_1.ConfigurationModule.DEALER_MANAGEMENT,
        type: configuration_entity_1.ConfigurationType.SYSTEM,
        dataType: configuration_entity_1.ConfigurationDataType.BOOLEAN,
        defaultValue: 'true',
        uiComponent: 'CHECKBOX',
        uiGroup: 'Data Management',
        uiOrder: 1,
    },
    {
        key: 'dealer.data.archive_after_months',
        name: 'Archive Data After (Months)',
        description: 'Number of months after which to archive dealer data',
        module: configuration_entity_1.ConfigurationModule.DEALER_MANAGEMENT,
        type: configuration_entity_1.ConfigurationType.SYSTEM,
        dataType: configuration_entity_1.ConfigurationDataType.NUMBER,
        defaultValue: '60',
        minValue: 12,
        maxValue: 120,
        uiComponent: 'NUMBER',
        uiGroup: 'Data Management',
        uiOrder: 2,
    },
    {
        key: 'dealer.data.backup_frequency_days',
        name: 'Data Backup Frequency (Days)',
        description: 'Frequency for backing up dealer data',
        module: configuration_entity_1.ConfigurationModule.DEALER_MANAGEMENT,
        type: configuration_entity_1.ConfigurationType.SYSTEM,
        dataType: configuration_entity_1.ConfigurationDataType.NUMBER,
        defaultValue: '1',
        minValue: 1,
        maxValue: 30,
        uiComponent: 'NUMBER',
        uiGroup: 'Data Management',
        uiOrder: 3,
    },
    {
        key: 'dealer.data.data_retention_years',
        name: 'Data Retention Period (Years)',
        description: 'Number of years to retain dealer data',
        module: configuration_entity_1.ConfigurationModule.DEALER_MANAGEMENT,
        type: configuration_entity_1.ConfigurationType.SYSTEM,
        dataType: configuration_entity_1.ConfigurationDataType.NUMBER,
        defaultValue: '7',
        minValue: 5,
        maxValue: 20,
        uiComponent: 'NUMBER',
        uiGroup: 'Data Management',
        uiOrder: 4,
    },
];
//# sourceMappingURL=dealer-config.schema.js.map