import { ConfigurationModule, ConfigurationType, ConfigurationDataType } from '../entities/configuration.entity';

export const PricingConfigurationSchema = [
  // General Pricing Configuration
  {
    key: 'pricing.general.pricing_method',
    name: 'Pricing Method',
    description: 'Primary pricing method for fuel products',
    module: ConfigurationModule.PRICING_BUILDUP,
    type: ConfigurationType.SYSTEM,
    dataType: ConfigurationDataType.STRING,
    defaultValue: 'DEREGULATED',
    allowedValues: ['REGULATED', 'DEREGULATED', 'HYBRID'],
    isRequired: true,
    uiComponent: 'SELECT',
    uiGroup: 'General',
    uiOrder: 1,
    impactLevel: 'CRITICAL',
  },
  {
    key: 'pricing.general.base_currency',
    name: 'Pricing Base Currency',
    description: 'Base currency for all pricing calculations',
    module: ConfigurationModule.PRICING_BUILDUP,
    type: ConfigurationType.SYSTEM,
    dataType: ConfigurationDataType.STRING,
    defaultValue: 'GHS',
    allowedValues: ['GHS', 'USD'],
    isRequired: true,
    uiComponent: 'SELECT',
    uiGroup: 'General',
    uiOrder: 2,
  },
  {
    key: 'pricing.general.decimal_places',
    name: 'Price Decimal Places',
    description: 'Number of decimal places for pricing calculations',
    module: ConfigurationModule.PRICING_BUILDUP,
    type: ConfigurationType.SYSTEM,
    dataType: ConfigurationDataType.NUMBER,
    defaultValue: '4',
    minValue: 2,
    maxValue: 8,
    uiComponent: 'NUMBER',
    uiGroup: 'General',
    uiOrder: 3,
  },
  {
    key: 'pricing.general.rounding_method',
    name: 'Price Rounding Method',
    description: 'Method for rounding final prices',
    module: ConfigurationModule.PRICING_BUILDUP,
    type: ConfigurationType.SYSTEM,
    dataType: ConfigurationDataType.STRING,
    defaultValue: 'ROUND_HALF_UP',
    allowedValues: ['ROUND_HALF_UP', 'ROUND_HALF_DOWN', 'ROUND_UP', 'ROUND_DOWN'],
    uiComponent: 'SELECT',
    uiGroup: 'General',
    uiOrder: 4,
  },
  {
    key: 'pricing.general.auto_pricing_enabled',
    name: 'Auto Pricing Enabled',
    description: 'Enable automatic pricing calculations',
    module: ConfigurationModule.PRICING_BUILDUP,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.BOOLEAN,
    defaultValue: 'true',
    uiComponent: 'CHECKBOX',
    uiGroup: 'General',
    uiOrder: 5,
  },
  {
    key: 'pricing.general.pricing_frequency',
    name: 'Pricing Update Frequency',
    description: 'How often to update pricing calculations',
    module: ConfigurationModule.PRICING_BUILDUP,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.STRING,
    defaultValue: 'DAILY',
    allowedValues: ['REAL_TIME', 'HOURLY', 'DAILY', 'WEEKLY', 'MANUAL'],
    uiComponent: 'SELECT',
    uiGroup: 'General',
    uiOrder: 6,
  },

  // Import Pricing Configuration
  {
    key: 'pricing.import.fob_price_source',
    name: 'FOB Price Source',
    description: 'Source for Free on Board (FOB) pricing data',
    module: ConfigurationModule.PRICING_BUILDUP,
    type: ConfigurationType.SYSTEM,
    dataType: ConfigurationDataType.STRING,
    defaultValue: 'PLATTS',
    allowedValues: ['PLATTS', 'ARGUS', 'REUTERS', 'MANUAL', 'API'],
    uiComponent: 'SELECT',
    uiGroup: 'Import Pricing',
    uiOrder: 1,
  },
  {
    key: 'pricing.import.freight_rate_per_mt',
    name: 'Freight Rate per MT',
    description: 'Freight rate per metric tonne (USD)',
    module: ConfigurationModule.PRICING_BUILDUP,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.NUMBER,
    defaultValue: '45.00',
    minValue: 0,
    maxValue: 200,
    uiComponent: 'NUMBER',
    uiGroup: 'Import Pricing',
    uiOrder: 2,
  },
  {
    key: 'pricing.import.insurance_rate_percentage',
    name: 'Insurance Rate Percentage',
    description: 'Insurance rate as percentage of FOB value',
    module: ConfigurationModule.PRICING_BUILDUP,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.NUMBER,
    defaultValue: '0.125',
    minValue: 0,
    maxValue: 2,
    uiComponent: 'NUMBER',
    uiGroup: 'Import Pricing',
    uiOrder: 3,
  },
  {
    key: 'pricing.import.port_charges_per_mt',
    name: 'Port Charges per MT',
    description: 'Port handling charges per metric tonne (GHS)',
    module: ConfigurationModule.PRICING_BUILDUP,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.NUMBER,
    defaultValue: '25.00',
    minValue: 0,
    maxValue: 100,
    uiComponent: 'NUMBER',
    uiGroup: 'Import Pricing',
    uiOrder: 4,
  },
  {
    key: 'pricing.import.demurrage_rate_per_day',
    name: 'Demurrage Rate per Day',
    description: 'Demurrage charges per day (USD)',
    module: ConfigurationModule.PRICING_BUILDUP,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.NUMBER,
    defaultValue: '15000.00',
    minValue: 0,
    maxValue: 50000,
    uiComponent: 'NUMBER',
    uiGroup: 'Import Pricing',
    uiOrder: 5,
  },
  {
    key: 'pricing.import.storage_cost_per_litre_per_day',
    name: 'Storage Cost per Litre per Day',
    description: 'Storage cost per litre per day (GHS)',
    module: ConfigurationModule.PRICING_BUILDUP,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.NUMBER,
    defaultValue: '0.0015',
    minValue: 0,
    maxValue: 0.01,
    uiComponent: 'NUMBER',
    uiGroup: 'Import Pricing',
    uiOrder: 6,
  },
  {
    key: 'pricing.import.finance_cost_rate_annual',
    name: 'Finance Cost Rate (Annual %)',
    description: 'Annual finance cost rate for imported products',
    module: ConfigurationModule.PRICING_BUILDUP,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.NUMBER,
    defaultValue: '12.5',
    minValue: 0,
    maxValue: 50,
    uiComponent: 'NUMBER',
    uiGroup: 'Import Pricing',
    uiOrder: 7,
  },
  {
    key: 'pricing.import.working_capital_days',
    name: 'Working Capital Days',
    description: 'Number of days for working capital calculation',
    module: ConfigurationModule.PRICING_BUILDUP,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.NUMBER,
    defaultValue: '30',
    minValue: 7,
    maxValue: 180,
    uiComponent: 'NUMBER',
    uiGroup: 'Import Pricing',
    uiOrder: 8,
  },

  // Tax and Levy Configuration
  {
    key: 'pricing.taxes.import_duty_rate',
    name: 'Import Duty Rate (%)',
    description: 'Import duty rate percentage',
    module: ConfigurationModule.PRICING_BUILDUP,
    type: ConfigurationType.SYSTEM,
    dataType: ConfigurationDataType.NUMBER,
    defaultValue: '0.00',
    minValue: 0,
    maxValue: 50,
    uiComponent: 'NUMBER',
    uiGroup: 'Taxes & Levies',
    uiOrder: 1,
  },
  {
    key: 'pricing.taxes.excise_duty_per_litre',
    name: 'Excise Duty per Litre',
    description: 'Excise duty in pesewas per litre',
    module: ConfigurationModule.PRICING_BUILDUP,
    type: ConfigurationType.SYSTEM,
    dataType: ConfigurationDataType.NUMBER,
    defaultValue: '17.50',
    minValue: 0,
    maxValue: 100,
    uiComponent: 'NUMBER',
    uiGroup: 'Taxes & Levies',
    uiOrder: 2,
  },
  {
    key: 'pricing.taxes.road_fund_levy_per_litre',
    name: 'Road Fund Levy per Litre',
    description: 'Road fund levy in pesewas per litre',
    module: ConfigurationModule.PRICING_BUILDUP,
    type: ConfigurationType.SYSTEM,
    dataType: ConfigurationDataType.NUMBER,
    defaultValue: '18.00',
    minValue: 0,
    maxValue: 100,
    uiComponent: 'NUMBER',
    uiGroup: 'Taxes & Levies',
    uiOrder: 3,
  },
  {
    key: 'pricing.taxes.energy_sector_levy_per_litre',
    name: 'Energy Sector Levy per Litre',
    description: 'Energy sector levy in pesewas per litre',
    module: ConfigurationModule.PRICING_BUILDUP,
    type: ConfigurationType.SYSTEM,
    dataType: ConfigurationDataType.NUMBER,
    defaultValue: '5.00',
    minValue: 0,
    maxValue: 50,
    uiComponent: 'NUMBER',
    uiGroup: 'Taxes & Levies',
    uiOrder: 4,
  },
  {
    key: 'pricing.taxes.primary_product_levy_per_litre',
    name: 'Primary Product Levy per Litre',
    description: 'Primary product levy in pesewas per litre',
    module: ConfigurationModule.PRICING_BUILDUP,
    type: ConfigurationType.SYSTEM,
    dataType: ConfigurationDataType.NUMBER,
    defaultValue: '1.00',
    minValue: 0,
    maxValue: 20,
    uiComponent: 'NUMBER',
    uiGroup: 'Taxes & Levies',
    uiOrder: 5,
  },
  {
    key: 'pricing.taxes.bost_margin_per_litre',
    name: 'BOST Margin per Litre',
    description: 'BOST (Bulk Oil Storage and Transportation) margin in pesewas per litre',
    module: ConfigurationModule.PRICING_BUILDUP,
    type: ConfigurationType.SYSTEM,
    dataType: ConfigurationDataType.NUMBER,
    defaultValue: '3.00',
    minValue: 0,
    maxValue: 20,
    uiComponent: 'NUMBER',
    uiGroup: 'Taxes & Levies',
    uiOrder: 6,
  },
  {
    key: 'pricing.taxes.npa_margin_per_litre',
    name: 'NPA Margin per Litre',
    description: 'NPA (National Petroleum Authority) margin in pesewas per litre',
    module: ConfigurationModule.PRICING_BUILDUP,
    type: ConfigurationType.SYSTEM,
    dataType: ConfigurationDataType.NUMBER,
    defaultValue: '1.00',
    minValue: 0,
    maxValue: 10,
    uiComponent: 'NUMBER',
    uiGroup: 'Taxes & Levies',
    uiOrder: 7,
  },
  {
    key: 'pricing.taxes.unified_petroleum_price_fund_per_litre',
    name: 'UPPF per Litre',
    description: 'Unified Petroleum Price Fund levy in pesewas per litre',
    module: ConfigurationModule.PRICING_BUILDUP,
    type: ConfigurationType.SYSTEM,
    dataType: ConfigurationDataType.NUMBER,
    defaultValue: '16.00',
    minValue: 0,
    maxValue: 50,
    uiComponent: 'NUMBER',
    uiGroup: 'Taxes & Levies',
    uiOrder: 8,
  },
  {
    key: 'pricing.taxes.price_stabilisation_levy_per_litre',
    name: 'Price Stabilisation Levy per Litre',
    description: 'Price stabilisation levy in pesewas per litre',
    module: ConfigurationModule.PRICING_BUILDUP,
    type: ConfigurationType.SYSTEM,
    dataType: ConfigurationDataType.NUMBER,
    defaultValue: '0.00',
    minValue: -50,
    maxValue: 50,
    uiComponent: 'NUMBER',
    uiGroup: 'Taxes & Levies',
    uiOrder: 9,
  },
  {
    key: 'pricing.taxes.sanitation_levy_per_litre',
    name: 'Sanitation Levy per Litre',
    description: 'Sanitation levy in pesewas per litre',
    module: ConfigurationModule.PRICING_BUILDUP,
    type: ConfigurationType.SYSTEM,
    dataType: ConfigurationDataType.NUMBER,
    defaultValue: '10.00',
    minValue: 0,
    maxValue: 30,
    uiComponent: 'NUMBER',
    uiGroup: 'Taxes & Levies',
    uiOrder: 10,
  },

  // Margin Configuration
  {
    key: 'pricing.margins.bdc_margin_per_litre',
    name: 'BDC Margin per Litre',
    description: 'Bulk Distribution Company margin in pesewas per litre',
    module: ConfigurationModule.PRICING_BUILDUP,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.NUMBER,
    defaultValue: '7.46',
    minValue: 0,
    maxValue: 50,
    uiComponent: 'NUMBER',
    uiGroup: 'Margins',
    uiOrder: 1,
  },
  {
    key: 'pricing.margins.omc_margin_per_litre',
    name: 'OMC Margin per Litre',
    description: 'Oil Marketing Company margin in pesewas per litre',
    module: ConfigurationModule.PRICING_BUILDUP,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.NUMBER,
    defaultValue: '15.75',
    minValue: 0,
    maxValue: 100,
    uiComponent: 'NUMBER',
    uiGroup: 'Margins',
    uiOrder: 2,
  },
  {
    key: 'pricing.margins.dealer_margin_per_litre',
    name: 'Dealer Margin per Litre',
    description: 'Retail dealer margin in pesewas per litre',
    module: ConfigurationModule.PRICING_BUILDUP,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.NUMBER,
    defaultValue: '19.46',
    minValue: 0,
    maxValue: 100,
    uiComponent: 'NUMBER',
    uiGroup: 'Margins',
    uiOrder: 3,
  },
  {
    key: 'pricing.margins.transportation_margin_per_litre',
    name: 'Transportation Margin per Litre',
    description: 'Transportation margin in pesewas per litre',
    module: ConfigurationModule.PRICING_BUILDUP,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.NUMBER,
    defaultValue: '7.00',
    minValue: 0,
    maxValue: 50,
    uiComponent: 'NUMBER',
    uiGroup: 'Margins',
    uiOrder: 4,
  },
  {
    key: 'pricing.margins.marketing_margin_per_litre',
    name: 'Marketing Margin per Litre',
    description: 'Marketing and promotion margin in pesewas per litre',
    module: ConfigurationModule.PRICING_BUILDUP,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.NUMBER,
    defaultValue: '2.00',
    minValue: 0,
    maxValue: 20,
    uiComponent: 'NUMBER',
    uiGroup: 'Margins',
    uiOrder: 5,
  },
  {
    key: 'pricing.margins.credit_loss_provision_percentage',
    name: 'Credit Loss Provision (%)',
    description: 'Credit loss provision as percentage of total cost',
    module: ConfigurationModule.PRICING_BUILDUP,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.NUMBER,
    defaultValue: '0.5',
    minValue: 0,
    maxValue: 5,
    uiComponent: 'NUMBER',
    uiGroup: 'Margins',
    uiOrder: 6,
  },

  // Product Specific Configuration
  {
    key: 'pricing.products.petrol.density_kg_per_litre',
    name: 'Petrol Density (kg/L)',
    description: 'Density of petrol in kilograms per litre',
    module: ConfigurationModule.PRICING_BUILDUP,
    type: ConfigurationType.SYSTEM,
    dataType: ConfigurationDataType.NUMBER,
    defaultValue: '0.740',
    minValue: 0.7,
    maxValue: 0.8,
    uiComponent: 'NUMBER',
    uiGroup: 'Product Specifications',
    uiOrder: 1,
  },
  {
    key: 'pricing.products.diesel.density_kg_per_litre',
    name: 'Diesel Density (kg/L)',
    description: 'Density of diesel in kilograms per litre',
    module: ConfigurationModule.PRICING_BUILDUP,
    type: ConfigurationType.SYSTEM,
    dataType: ConfigurationDataType.NUMBER,
    defaultValue: '0.845',
    minValue: 0.8,
    maxValue: 0.9,
    uiComponent: 'NUMBER',
    uiGroup: 'Product Specifications',
    uiOrder: 2,
  },
  {
    key: 'pricing.products.kerosene.density_kg_per_litre',
    name: 'Kerosene Density (kg/L)',
    description: 'Density of kerosene in kilograms per litre',
    module: ConfigurationModule.PRICING_BUILDUP,
    type: ConfigurationType.SYSTEM,
    dataType: ConfigurationDataType.NUMBER,
    defaultValue: '0.810',
    minValue: 0.78,
    maxValue: 0.84,
    uiComponent: 'NUMBER',
    uiGroup: 'Product Specifications',
    uiOrder: 3,
  },
  {
    key: 'pricing.products.lpg.density_kg_per_litre',
    name: 'LPG Density (kg/L)',
    description: 'Density of LPG in kilograms per litre',
    module: ConfigurationModule.PRICING_BUILDUP,
    type: ConfigurationType.SYSTEM,
    dataType: ConfigurationDataType.NUMBER,
    defaultValue: '0.540',
    minValue: 0.5,
    maxValue: 0.6,
    uiComponent: 'NUMBER',
    uiGroup: 'Product Specifications',
    uiOrder: 4,
  },
  {
    key: 'pricing.products.ifa.density_kg_per_litre',
    name: 'IFA Density (kg/L)',
    description: 'Density of IFA (Intermediate Fuel Oil) in kilograms per litre',
    module: ConfigurationModule.PRICING_BUILDUP,
    type: ConfigurationType.SYSTEM,
    dataType: ConfigurationDataType.NUMBER,
    defaultValue: '0.920',
    minValue: 0.85,
    maxValue: 0.98,
    uiComponent: 'NUMBER',
    uiGroup: 'Product Specifications',
    uiOrder: 5,
  },

  // Exchange Rate Configuration
  {
    key: 'pricing.exchange_rate.auto_update_enabled',
    name: 'Auto Update Exchange Rates',
    description: 'Automatically update exchange rates for pricing',
    module: ConfigurationModule.PRICING_BUILDUP,
    type: ConfigurationType.SYSTEM,
    dataType: ConfigurationDataType.BOOLEAN,
    defaultValue: 'true',
    uiComponent: 'CHECKBOX',
    uiGroup: 'Exchange Rates',
    uiOrder: 1,
  },
  {
    key: 'pricing.exchange_rate.source',
    name: 'Exchange Rate Source',
    description: 'Source for exchange rate data',
    module: ConfigurationModule.PRICING_BUILDUP,
    type: ConfigurationType.SYSTEM,
    dataType: ConfigurationDataType.STRING,
    defaultValue: 'BANK_OF_GHANA',
    allowedValues: ['BANK_OF_GHANA', 'FIXER_IO', 'OPEN_EXCHANGE_RATES', 'MANUAL'],
    uiComponent: 'SELECT',
    uiGroup: 'Exchange Rates',
    uiOrder: 2,
  },
  {
    key: 'pricing.exchange_rate.update_frequency',
    name: 'Exchange Rate Update Frequency',
    description: 'How often to update exchange rates',
    module: ConfigurationModule.PRICING_BUILDUP,
    type: ConfigurationType.SYSTEM,
    dataType: ConfigurationDataType.STRING,
    defaultValue: 'DAILY',
    allowedValues: ['REAL_TIME', 'HOURLY', 'DAILY', 'WEEKLY'],
    uiComponent: 'SELECT',
    uiGroup: 'Exchange Rates',
    uiOrder: 3,
  },
  {
    key: 'pricing.exchange_rate.fallback_rate_usd_ghs',
    name: 'Fallback USD/GHS Rate',
    description: 'Fallback exchange rate if source is unavailable',
    module: ConfigurationModule.PRICING_BUILDUP,
    type: ConfigurationType.SYSTEM,
    dataType: ConfigurationDataType.NUMBER,
    defaultValue: '12.00',
    minValue: 1,
    maxValue: 50,
    uiComponent: 'NUMBER',
    uiGroup: 'Exchange Rates',
    uiOrder: 4,
  },
  {
    key: 'pricing.exchange_rate.variance_threshold_percentage',
    name: 'Rate Variance Threshold (%)',
    description: 'Threshold for rate variance alerts',
    module: ConfigurationModule.PRICING_BUILDUP,
    type: ConfigurationType.SYSTEM,
    dataType: ConfigurationDataType.NUMBER,
    defaultValue: '5.0',
    minValue: 1,
    maxValue: 20,
    uiComponent: 'NUMBER',
    uiGroup: 'Exchange Rates',
    uiOrder: 5,
  },

  // Price Window Configuration
  {
    key: 'pricing.window.automatic_pricing_enabled',
    name: 'Automatic Pricing Window Enabled',
    description: 'Enable automatic pricing window calculations',
    module: ConfigurationModule.PRICING_BUILDUP,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.BOOLEAN,
    defaultValue: 'true',
    uiComponent: 'CHECKBOX',
    uiGroup: 'Pricing Window',
    uiOrder: 1,
  },
  {
    key: 'pricing.window.window_period_days',
    name: 'Pricing Window Period (Days)',
    description: 'Number of days for pricing window validity',
    module: ConfigurationModule.PRICING_BUILDUP,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.NUMBER,
    defaultValue: '14',
    minValue: 1,
    maxValue: 90,
    uiComponent: 'NUMBER',
    uiGroup: 'Pricing Window',
    uiOrder: 2,
  },
  {
    key: 'pricing.window.review_frequency_days',
    name: 'Price Review Frequency (Days)',
    description: 'How often to review and update price windows',
    module: ConfigurationModule.PRICING_BUILDUP,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.NUMBER,
    defaultValue: '7',
    minValue: 1,
    maxValue: 30,
    uiComponent: 'NUMBER',
    uiGroup: 'Pricing Window',
    uiOrder: 3,
  },
  {
    key: 'pricing.window.max_price_variance_percentage',
    name: 'Max Price Variance (%)',
    description: 'Maximum allowed price variance within window',
    module: ConfigurationModule.PRICING_BUILDUP,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.NUMBER,
    defaultValue: '15.0',
    minValue: 5,
    maxValue: 50,
    uiComponent: 'NUMBER',
    uiGroup: 'Pricing Window',
    uiOrder: 4,
  },
  {
    key: 'pricing.window.emergency_adjustment_threshold',
    name: 'Emergency Adjustment Threshold (%)',
    description: 'Threshold for emergency price adjustments',
    module: ConfigurationModule.PRICING_BUILDUP,
    type: ConfigurationType.SYSTEM,
    dataType: ConfigurationDataType.NUMBER,
    defaultValue: '25.0',
    minValue: 10,
    maxValue: 100,
    uiComponent: 'NUMBER',
    uiGroup: 'Pricing Window',
    uiOrder: 5,
  },

  // Regional Pricing Configuration
  {
    key: 'pricing.regional.enable_regional_pricing',
    name: 'Enable Regional Pricing',
    description: 'Enable different pricing for different regions',
    module: ConfigurationModule.PRICING_BUILDUP,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.BOOLEAN,
    defaultValue: 'false',
    uiComponent: 'CHECKBOX',
    uiGroup: 'Regional Pricing',
    uiOrder: 1,
  },
  {
    key: 'pricing.regional.transport_cost_adjustment_per_km',
    name: 'Transport Cost per KM',
    description: 'Additional transport cost per kilometer (GHS per litre)',
    module: ConfigurationModule.PRICING_BUILDUP,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.NUMBER,
    defaultValue: '0.002',
    minValue: 0,
    maxValue: 0.1,
    uiComponent: 'NUMBER',
    uiGroup: 'Regional Pricing',
    uiOrder: 2,
  },
  {
    key: 'pricing.regional.northern_region_discount_percentage',
    name: 'Northern Region Discount (%)',
    description: 'Discount percentage for Northern regions',
    module: ConfigurationModule.PRICING_BUILDUP,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.NUMBER,
    defaultValue: '0.0',
    minValue: 0,
    maxValue: 10,
    uiComponent: 'NUMBER',
    uiGroup: 'Regional Pricing',
    uiOrder: 3,
  },
  {
    key: 'pricing.regional.remote_area_surcharge_percentage',
    name: 'Remote Area Surcharge (%)',
    description: 'Surcharge percentage for remote areas',
    module: ConfigurationModule.PRICING_BUILDUP,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.NUMBER,
    defaultValue: '2.0',
    minValue: 0,
    maxValue: 15,
    uiComponent: 'NUMBER',
    uiGroup: 'Regional Pricing',
    uiOrder: 4,
  },

  // Volume-based Pricing Configuration
  {
    key: 'pricing.volume.enable_volume_discounts',
    name: 'Enable Volume Discounts',
    description: 'Enable volume-based discount pricing',
    module: ConfigurationModule.PRICING_BUILDUP,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.BOOLEAN,
    defaultValue: 'true',
    uiComponent: 'CHECKBOX',
    uiGroup: 'Volume Pricing',
    uiOrder: 1,
  },
  {
    key: 'pricing.volume.tier1_minimum_litres',
    name: 'Tier 1 Minimum Volume (Litres)',
    description: 'Minimum volume for tier 1 discount',
    module: ConfigurationModule.PRICING_BUILDUP,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.NUMBER,
    defaultValue: '5000',
    minValue: 1000,
    maxValue: 50000,
    uiComponent: 'NUMBER',
    uiGroup: 'Volume Pricing',
    uiOrder: 2,
  },
  {
    key: 'pricing.volume.tier1_discount_percentage',
    name: 'Tier 1 Discount Percentage',
    description: 'Discount percentage for tier 1 volume',
    module: ConfigurationModule.PRICING_BUILDUP,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.NUMBER,
    defaultValue: '1.0',
    minValue: 0,
    maxValue: 10,
    uiComponent: 'NUMBER',
    uiGroup: 'Volume Pricing',
    uiOrder: 3,
  },
  {
    key: 'pricing.volume.tier2_minimum_litres',
    name: 'Tier 2 Minimum Volume (Litres)',
    description: 'Minimum volume for tier 2 discount',
    module: ConfigurationModule.PRICING_BUILDUP,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.NUMBER,
    defaultValue: '20000',
    minValue: 10000,
    maxValue: 200000,
    uiComponent: 'NUMBER',
    uiGroup: 'Volume Pricing',
    uiOrder: 4,
  },
  {
    key: 'pricing.volume.tier2_discount_percentage',
    name: 'Tier 2 Discount Percentage',
    description: 'Discount percentage for tier 2 volume',
    module: ConfigurationModule.PRICING_BUILDUP,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.NUMBER,
    defaultValue: '2.0',
    minValue: 0,
    maxValue: 15,
    uiComponent: 'NUMBER',
    uiGroup: 'Volume Pricing',
    uiOrder: 5,
  },
  {
    key: 'pricing.volume.tier3_minimum_litres',
    name: 'Tier 3 Minimum Volume (Litres)',
    description: 'Minimum volume for tier 3 discount',
    module: ConfigurationModule.PRICING_BUILDUP,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.NUMBER,
    defaultValue: '100000',
    minValue: 50000,
    maxValue: 1000000,
    uiComponent: 'NUMBER',
    uiGroup: 'Volume Pricing',
    uiOrder: 6,
  },
  {
    key: 'pricing.volume.tier3_discount_percentage',
    name: 'Tier 3 Discount Percentage',
    description: 'Discount percentage for tier 3 volume',
    module: ConfigurationModule.PRICING_BUILDUP,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.NUMBER,
    defaultValue: '3.5',
    minValue: 0,
    maxValue: 20,
    uiComponent: 'NUMBER',
    uiGroup: 'Volume Pricing',
    uiOrder: 7,
  },

  // Customer Category Pricing
  {
    key: 'pricing.customer.industrial_discount_percentage',
    name: 'Industrial Customer Discount (%)',
    description: 'Discount percentage for industrial customers',
    module: ConfigurationModule.PRICING_BUILDUP,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.NUMBER,
    defaultValue: '2.5',
    minValue: 0,
    maxValue: 15,
    uiComponent: 'NUMBER',
    uiGroup: 'Customer Pricing',
    uiOrder: 1,
  },
  {
    key: 'pricing.customer.government_discount_percentage',
    name: 'Government Discount (%)',
    description: 'Discount percentage for government customers',
    module: ConfigurationModule.PRICING_BUILDUP,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.NUMBER,
    defaultValue: '1.5',
    minValue: 0,
    maxValue: 10,
    uiComponent: 'NUMBER',
    uiGroup: 'Customer Pricing',
    uiOrder: 2,
  },
  {
    key: 'pricing.customer.mining_discount_percentage',
    name: 'Mining Company Discount (%)',
    description: 'Discount percentage for mining companies',
    module: ConfigurationModule.PRICING_BUILDUP,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.NUMBER,
    defaultValue: '3.0',
    minValue: 0,
    maxValue: 20,
    uiComponent: 'NUMBER',
    uiGroup: 'Customer Pricing',
    uiOrder: 3,
  },
  {
    key: 'pricing.customer.transport_discount_percentage',
    name: 'Transport Company Discount (%)',
    description: 'Discount percentage for transport companies',
    module: ConfigurationModule.PRICING_BUILDUP,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.NUMBER,
    defaultValue: '1.0',
    minValue: 0,
    maxValue: 10,
    uiComponent: 'NUMBER',
    uiGroup: 'Customer Pricing',
    uiOrder: 4,
  },

  // Validation and Control Configuration
  {
    key: 'pricing.validation.max_price_increase_percentage_per_day',
    name: 'Max Daily Price Increase (%)',
    description: 'Maximum allowed daily price increase percentage',
    module: ConfigurationModule.PRICING_BUILDUP,
    type: ConfigurationType.SYSTEM,
    dataType: ConfigurationDataType.NUMBER,
    defaultValue: '5.0',
    minValue: 1,
    maxValue: 25,
    uiComponent: 'NUMBER',
    uiGroup: 'Validation',
    uiOrder: 1,
  },
  {
    key: 'pricing.validation.max_price_decrease_percentage_per_day',
    name: 'Max Daily Price Decrease (%)',
    description: 'Maximum allowed daily price decrease percentage',
    module: ConfigurationModule.PRICING_BUILDUP,
    type: ConfigurationType.SYSTEM,
    dataType: ConfigurationDataType.NUMBER,
    defaultValue: '10.0',
    minValue: 1,
    maxValue: 50,
    uiComponent: 'NUMBER',
    uiGroup: 'Validation',
    uiOrder: 2,
  },
  {
    key: 'pricing.validation.minimum_retail_price_ghs',
    name: 'Minimum Retail Price (GHS)',
    description: 'Minimum allowed retail price per litre',
    module: ConfigurationModule.PRICING_BUILDUP,
    type: ConfigurationType.SYSTEM,
    dataType: ConfigurationDataType.NUMBER,
    defaultValue: '4.00',
    minValue: 1,
    maxValue: 20,
    uiComponent: 'NUMBER',
    uiGroup: 'Validation',
    uiOrder: 3,
  },
  {
    key: 'pricing.validation.maximum_retail_price_ghs',
    name: 'Maximum Retail Price (GHS)',
    description: 'Maximum allowed retail price per litre',
    module: ConfigurationModule.PRICING_BUILDUP,
    type: ConfigurationType.SYSTEM,
    dataType: ConfigurationDataType.NUMBER,
    defaultValue: '25.00',
    minValue: 10,
    maxValue: 100,
    uiComponent: 'NUMBER',
    uiGroup: 'Validation',
    uiOrder: 4,
  },
  {
    key: 'pricing.validation.require_approval_for_price_changes',
    name: 'Require Approval for Price Changes',
    description: 'Require management approval for price changes',
    module: ConfigurationModule.PRICING_BUILDUP,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.BOOLEAN,
    defaultValue: 'true',
    uiComponent: 'CHECKBOX',
    uiGroup: 'Validation',
    uiOrder: 5,
  },
  {
    key: 'pricing.validation.price_change_approval_threshold_percentage',
    name: 'Price Change Approval Threshold (%)',
    description: 'Percentage change requiring approval',
    module: ConfigurationModule.PRICING_BUILDUP,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.NUMBER,
    defaultValue: '3.0',
    minValue: 1,
    maxValue: 20,
    uiComponent: 'NUMBER',
    uiGroup: 'Validation',
    uiOrder: 6,
  },

  // Notification Configuration
  {
    key: 'pricing.notifications.price_change_alerts',
    name: 'Price Change Alerts',
    description: 'Send alerts when prices change',
    module: ConfigurationModule.PRICING_BUILDUP,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.BOOLEAN,
    defaultValue: 'true',
    uiComponent: 'CHECKBOX',
    uiGroup: 'Notifications',
    uiOrder: 1,
  },
  {
    key: 'pricing.notifications.threshold_breach_alerts',
    name: 'Threshold Breach Alerts',
    description: 'Send alerts when price thresholds are breached',
    module: ConfigurationModule.PRICING_BUILDUP,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.BOOLEAN,
    defaultValue: 'true',
    uiComponent: 'CHECKBOX',
    uiGroup: 'Notifications',
    uiOrder: 2,
  },
  {
    key: 'pricing.notifications.calculation_failure_alerts',
    name: 'Calculation Failure Alerts',
    description: 'Send alerts when pricing calculations fail',
    module: ConfigurationModule.PRICING_BUILDUP,
    type: ConfigurationType.SYSTEM,
    dataType: ConfigurationDataType.BOOLEAN,
    defaultValue: 'true',
    uiComponent: 'CHECKBOX',
    uiGroup: 'Notifications',
    uiOrder: 3,
  },
  {
    key: 'pricing.notifications.daily_price_summary',
    name: 'Daily Price Summary',
    description: 'Send daily price summary notifications',
    module: ConfigurationModule.PRICING_BUILDUP,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.BOOLEAN,
    defaultValue: 'true',
    uiComponent: 'CHECKBOX',
    uiGroup: 'Notifications',
    uiOrder: 4,
  },
  {
    key: 'pricing.notifications.email_recipients',
    name: 'Pricing Notification Recipients',
    description: 'Email addresses for pricing notifications',
    module: ConfigurationModule.PRICING_BUILDUP,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.ARRAY,
    defaultValue: '[]',
    uiComponent: 'MULTI_INPUT',
    uiGroup: 'Notifications',
    uiOrder: 5,
  },

  // Reporting Configuration
  {
    key: 'pricing.reporting.auto_generate_daily_reports',
    name: 'Auto Generate Daily Reports',
    description: 'Automatically generate daily pricing reports',
    module: ConfigurationModule.PRICING_BUILDUP,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.BOOLEAN,
    defaultValue: 'true',
    uiComponent: 'CHECKBOX',
    uiGroup: 'Reporting',
    uiOrder: 1,
  },
  {
    key: 'pricing.reporting.include_cost_breakdown',
    name: 'Include Cost Breakdown',
    description: 'Include detailed cost breakdown in reports',
    module: ConfigurationModule.PRICING_BUILDUP,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.BOOLEAN,
    defaultValue: 'true',
    uiComponent: 'CHECKBOX',
    uiGroup: 'Reporting',
    uiOrder: 2,
  },
  {
    key: 'pricing.reporting.include_competitor_analysis',
    name: 'Include Competitor Analysis',
    description: 'Include competitor price analysis in reports',
    module: ConfigurationModule.PRICING_BUILDUP,
    type: ConfigurationType.TENANT,
    dataType: ConfigurationDataType.BOOLEAN,
    defaultValue: 'false',
    uiComponent: 'CHECKBOX',
    uiGroup: 'Reporting',
    uiOrder: 3,
  },
  {
    key: 'pricing.reporting.report_retention_months',
    name: 'Report Retention (Months)',
    description: 'Number of months to retain pricing reports',
    module: ConfigurationModule.PRICING_BUILDUP,
    type: ConfigurationType.SYSTEM,
    dataType: ConfigurationDataType.NUMBER,
    defaultValue: '24',
    minValue: 12,
    maxValue: 60,
    uiComponent: 'NUMBER',
    uiGroup: 'Reporting',
    uiOrder: 4,
  },

  // Performance Configuration
  {
    key: 'pricing.performance.enable_calculation_caching',
    name: 'Enable Calculation Caching',
    description: 'Enable caching of pricing calculations',
    module: ConfigurationModule.PRICING_BUILDUP,
    type: ConfigurationType.SYSTEM,
    dataType: ConfigurationDataType.BOOLEAN,
    defaultValue: 'true',
    uiComponent: 'CHECKBOX',
    uiGroup: 'Performance',
    uiOrder: 1,
  },
  {
    key: 'pricing.performance.cache_ttl_minutes',
    name: 'Cache TTL (Minutes)',
    description: 'Time-to-live for cached pricing data',
    module: ConfigurationModule.PRICING_BUILDUP,
    type: ConfigurationType.SYSTEM,
    dataType: ConfigurationDataType.NUMBER,
    defaultValue: '15',
    minValue: 1,
    maxValue: 1440,
    uiComponent: 'NUMBER',
    uiGroup: 'Performance',
    uiOrder: 2,
  },
  {
    key: 'pricing.performance.max_concurrent_calculations',
    name: 'Max Concurrent Calculations',
    description: 'Maximum number of concurrent pricing calculations',
    module: ConfigurationModule.PRICING_BUILDUP,
    type: ConfigurationType.SYSTEM,
    dataType: ConfigurationDataType.NUMBER,
    defaultValue: '10',
    minValue: 1,
    maxValue: 50,
    uiComponent: 'NUMBER',
    uiGroup: 'Performance',
    uiOrder: 3,
  },
  {
    key: 'pricing.performance.calculation_timeout_seconds',
    name: 'Calculation Timeout (Seconds)',
    description: 'Timeout for pricing calculations in seconds',
    module: ConfigurationModule.PRICING_BUILDUP,
    type: ConfigurationType.SYSTEM,
    dataType: ConfigurationDataType.NUMBER,
    defaultValue: '30',
    minValue: 5,
    maxValue: 300,
    uiComponent: 'NUMBER',
    uiGroup: 'Performance',
    uiOrder: 4,
  },

  // Integration Configuration
  {
    key: 'pricing.integration.enable_external_data_feeds',
    name: 'Enable External Data Feeds',
    description: 'Enable integration with external pricing data feeds',
    module: ConfigurationModule.PRICING_BUILDUP,
    type: ConfigurationType.SYSTEM,
    dataType: ConfigurationDataType.BOOLEAN,
    defaultValue: 'true',
    uiComponent: 'CHECKBOX',
    uiGroup: 'Integration',
    uiOrder: 1,
  },
  {
    key: 'pricing.integration.platts_api_enabled',
    name: 'Platts API Enabled',
    description: 'Enable Platts pricing data integration',
    module: ConfigurationModule.PRICING_BUILDUP,
    type: ConfigurationType.SYSTEM,
    dataType: ConfigurationDataType.BOOLEAN,
    defaultValue: 'false',
    uiComponent: 'CHECKBOX',
    uiGroup: 'Integration',
    uiOrder: 2,
  },
  {
    key: 'pricing.integration.reuters_api_enabled',
    name: 'Reuters API Enabled',
    description: 'Enable Reuters pricing data integration',
    module: ConfigurationModule.PRICING_BUILDUP,
    type: ConfigurationType.SYSTEM,
    dataType: ConfigurationDataType.BOOLEAN,
    defaultValue: 'false',
    uiComponent: 'CHECKBOX',
    uiGroup: 'Integration',
    uiOrder: 3,
  },
  {
    key: 'pricing.integration.npa_price_sync_enabled',
    name: 'NPA Price Sync Enabled',
    description: 'Enable synchronization with NPA pricing data',
    module: ConfigurationModule.PRICING_BUILDUP,
    type: ConfigurationType.SYSTEM,
    dataType: ConfigurationDataType.BOOLEAN,
    defaultValue: 'true',
    uiComponent: 'CHECKBOX',
    uiGroup: 'Integration',
    uiOrder: 4,
  },
  {
    key: 'pricing.integration.sync_frequency_minutes',
    name: 'Data Sync Frequency (Minutes)',
    description: 'Frequency for syncing external pricing data',
    module: ConfigurationModule.PRICING_BUILDUP,
    type: ConfigurationType.SYSTEM,
    dataType: ConfigurationDataType.NUMBER,
    defaultValue: '60',
    minValue: 15,
    maxValue: 1440,
    uiComponent: 'NUMBER',
    uiGroup: 'Integration',
    uiOrder: 5,
  },
];