import { ConfigurationModule, ConfigurationType, ConfigurationDataType } from '../entities/configuration.entity';
export declare const SupplyChainConfigurationSchema: ({
    key: string;
    name: string;
    description: string;
    module: ConfigurationModule;
    type: ConfigurationType;
    dataType: ConfigurationDataType;
    defaultValue: string;
    uiComponent: string;
    uiGroup: string;
    uiOrder: number;
    minValue?: undefined;
    allowedValues?: undefined;
    maxValue?: undefined;
    regexPattern?: undefined;
} | {
    key: string;
    name: string;
    description: string;
    module: ConfigurationModule;
    type: ConfigurationType;
    dataType: ConfigurationDataType;
    defaultValue: string;
    minValue: number;
    uiComponent: string;
    uiGroup: string;
    uiOrder: number;
    allowedValues?: undefined;
    maxValue?: undefined;
    regexPattern?: undefined;
} | {
    key: string;
    name: string;
    description: string;
    module: ConfigurationModule;
    type: ConfigurationType;
    dataType: ConfigurationDataType;
    defaultValue: string;
    allowedValues: string[];
    uiComponent: string;
    uiGroup: string;
    uiOrder: number;
    minValue?: undefined;
    maxValue?: undefined;
    regexPattern?: undefined;
} | {
    key: string;
    name: string;
    description: string;
    module: ConfigurationModule;
    type: ConfigurationType;
    dataType: ConfigurationDataType;
    defaultValue: string;
    minValue: number;
    maxValue: number;
    uiComponent: string;
    uiGroup: string;
    uiOrder: number;
    allowedValues?: undefined;
    regexPattern?: undefined;
} | {
    key: string;
    name: string;
    description: string;
    module: ConfigurationModule;
    type: ConfigurationType;
    dataType: ConfigurationDataType;
    defaultValue: string;
    regexPattern: string;
    uiComponent: string;
    uiGroup: string;
    uiOrder: number;
    minValue?: undefined;
    allowedValues?: undefined;
    maxValue?: undefined;
})[];
//# sourceMappingURL=supply-chain-config.schema.d.ts.map