"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SupplyChainConfigurationSchema = void 0;
const configuration_entity_1 = require("../entities/configuration.entity");
exports.SupplyChainConfigurationSchema = [
    // Order Management
    {
        key: 'supply_chain.orders.auto_numbering',
        name: 'Auto Order Number Generation',
        description: 'Automatically generate order numbers',
        module: configuration_entity_1.ConfigurationModule.SUPPLY_CHAIN,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.BOOLEAN,
        defaultValue: 'true',
        uiComponent: 'CHECKBOX',
        uiGroup: 'Order Management',
        uiOrder: 1,
    },
    {
        key: 'supply_chain.orders.number_prefix',
        name: 'Order Number Prefix',
        description: 'Prefix for order numbers',
        module: configuration_entity_1.ConfigurationModule.SUPPLY_CHAIN,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.STRING,
        defaultValue: 'ORD',
        uiComponent: 'INPUT',
        uiGroup: 'Order Management',
        uiOrder: 2,
    },
    {
        key: 'supply_chain.orders.approval_required',
        name: 'Require Order Approval',
        description: 'All orders must be approved before processing',
        module: configuration_entity_1.ConfigurationModule.SUPPLY_CHAIN,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.BOOLEAN,
        defaultValue: 'true',
        uiComponent: 'CHECKBOX',
        uiGroup: 'Order Management',
        uiOrder: 3,
    },
    {
        key: 'supply_chain.orders.approval_threshold',
        name: 'Order Approval Threshold',
        description: 'Minimum order value requiring approval (in base currency)',
        module: configuration_entity_1.ConfigurationModule.SUPPLY_CHAIN,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.NUMBER,
        defaultValue: '50000',
        minValue: 0,
        uiComponent: 'NUMBER',
        uiGroup: 'Order Management',
        uiOrder: 4,
    },
    {
        key: 'supply_chain.orders.emergency_threshold',
        name: 'Emergency Order Threshold',
        description: 'Order value that triggers emergency processing',
        module: configuration_entity_1.ConfigurationModule.SUPPLY_CHAIN,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.NUMBER,
        defaultValue: '500000',
        minValue: 0,
        uiComponent: 'NUMBER',
        uiGroup: 'Order Management',
        uiOrder: 5,
    },
    {
        key: 'supply_chain.orders.auto_allocation',
        name: 'Auto Inventory Allocation',
        description: 'Automatically allocate inventory when order is approved',
        module: configuration_entity_1.ConfigurationModule.SUPPLY_CHAIN,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.BOOLEAN,
        defaultValue: 'true',
        uiComponent: 'CHECKBOX',
        uiGroup: 'Order Management',
        uiOrder: 6,
    },
    // Inventory Management
    {
        key: 'supply_chain.inventory.reorder_point_calculation',
        name: 'Reorder Point Calculation Method',
        description: 'Method for calculating reorder points',
        module: configuration_entity_1.ConfigurationModule.SUPPLY_CHAIN,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.STRING,
        defaultValue: 'DEMAND_BASED',
        allowedValues: ['DEMAND_BASED', 'TIME_BASED', 'MANUAL', 'AI_OPTIMIZED'],
        uiComponent: 'SELECT',
        uiGroup: 'Inventory Management',
        uiOrder: 1,
    },
    {
        key: 'supply_chain.inventory.safety_stock_days',
        name: 'Safety Stock Days',
        description: 'Number of days of demand to maintain as safety stock',
        module: configuration_entity_1.ConfigurationModule.SUPPLY_CHAIN,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.NUMBER,
        defaultValue: '7',
        minValue: 1,
        maxValue: 90,
        uiComponent: 'NUMBER',
        uiGroup: 'Inventory Management',
        uiOrder: 2,
    },
    {
        key: 'supply_chain.inventory.lead_time_days',
        name: 'Default Lead Time Days',
        description: 'Default lead time for inventory replenishment',
        module: configuration_entity_1.ConfigurationModule.SUPPLY_CHAIN,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.NUMBER,
        defaultValue: '14',
        minValue: 1,
        maxValue: 365,
        uiComponent: 'NUMBER',
        uiGroup: 'Inventory Management',
        uiOrder: 3,
    },
    {
        key: 'supply_chain.inventory.abc_analysis_enabled',
        name: 'Enable ABC Analysis',
        description: 'Perform ABC analysis for inventory classification',
        module: configuration_entity_1.ConfigurationModule.SUPPLY_CHAIN,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.BOOLEAN,
        defaultValue: 'true',
        uiComponent: 'CHECKBOX',
        uiGroup: 'Inventory Management',
        uiOrder: 4,
    },
    {
        key: 'supply_chain.inventory.abc_thresholds',
        name: 'ABC Analysis Thresholds',
        description: 'Thresholds for ABC classification (JSON)',
        module: configuration_entity_1.ConfigurationModule.SUPPLY_CHAIN,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.JSON,
        defaultValue: '{"A": 80, "B": 95}',
        uiComponent: 'JSON_EDITOR',
        uiGroup: 'Inventory Management',
        uiOrder: 5,
    },
    {
        key: 'supply_chain.inventory.negative_stock_allowed',
        name: 'Allow Negative Stock',
        description: 'Allow inventory to go negative',
        module: configuration_entity_1.ConfigurationModule.SUPPLY_CHAIN,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.BOOLEAN,
        defaultValue: 'false',
        uiComponent: 'CHECKBOX',
        uiGroup: 'Inventory Management',
        uiOrder: 6,
    },
    {
        key: 'supply_chain.inventory.valuation_method',
        name: 'Inventory Valuation Method',
        description: 'Method for inventory valuation',
        module: configuration_entity_1.ConfigurationModule.SUPPLY_CHAIN,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.STRING,
        defaultValue: 'WEIGHTED_AVERAGE',
        allowedValues: ['FIFO', 'LIFO', 'WEIGHTED_AVERAGE', 'STANDARD_COST'],
        uiComponent: 'SELECT',
        uiGroup: 'Inventory Management',
        uiOrder: 7,
    },
    // Stock Movement and Transfers
    {
        key: 'supply_chain.movement.auto_confirmation',
        name: 'Auto-Confirm Stock Movements',
        description: 'Automatically confirm stock movements',
        module: configuration_entity_1.ConfigurationModule.SUPPLY_CHAIN,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.BOOLEAN,
        defaultValue: 'false',
        uiComponent: 'CHECKBOX',
        uiGroup: 'Stock Movement',
        uiOrder: 1,
    },
    {
        key: 'supply_chain.movement.require_reason',
        name: 'Require Movement Reason',
        description: 'Require reason for all stock movements',
        module: configuration_entity_1.ConfigurationModule.SUPPLY_CHAIN,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.BOOLEAN,
        defaultValue: 'true',
        uiComponent: 'CHECKBOX',
        uiGroup: 'Stock Movement',
        uiOrder: 2,
    },
    {
        key: 'supply_chain.transfers.approval_required',
        name: 'Require Transfer Approval',
        description: 'Stock transfers require approval',
        module: configuration_entity_1.ConfigurationModule.SUPPLY_CHAIN,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.BOOLEAN,
        defaultValue: 'true',
        uiComponent: 'CHECKBOX',
        uiGroup: 'Stock Movement',
        uiOrder: 3,
    },
    {
        key: 'supply_chain.transfers.approval_threshold',
        name: 'Transfer Approval Threshold',
        description: 'Value threshold requiring approval for transfers',
        module: configuration_entity_1.ConfigurationModule.SUPPLY_CHAIN,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.NUMBER,
        defaultValue: '100000',
        minValue: 0,
        uiComponent: 'NUMBER',
        uiGroup: 'Stock Movement',
        uiOrder: 4,
    },
    // Alerts and Notifications
    {
        key: 'supply_chain.alerts.low_stock_enabled',
        name: 'Enable Low Stock Alerts',
        description: 'Send alerts when stock levels are low',
        module: configuration_entity_1.ConfigurationModule.SUPPLY_CHAIN,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.BOOLEAN,
        defaultValue: 'true',
        uiComponent: 'CHECKBOX',
        uiGroup: 'Alerts & Notifications',
        uiOrder: 1,
    },
    {
        key: 'supply_chain.alerts.low_stock_threshold',
        name: 'Low Stock Alert Threshold',
        description: 'Percentage of reorder point to trigger low stock alert',
        module: configuration_entity_1.ConfigurationModule.SUPPLY_CHAIN,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.NUMBER,
        defaultValue: '80',
        minValue: 10,
        maxValue: 100,
        uiComponent: 'SLIDER',
        uiGroup: 'Alerts & Notifications',
        uiOrder: 2,
    },
    {
        key: 'supply_chain.alerts.expiry_warning_days',
        name: 'Expiry Warning Days',
        description: 'Days before expiry to send warning alerts',
        module: configuration_entity_1.ConfigurationModule.SUPPLY_CHAIN,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.NUMBER,
        defaultValue: '30',
        minValue: 1,
        maxValue: 365,
        uiComponent: 'NUMBER',
        uiGroup: 'Alerts & Notifications',
        uiOrder: 3,
    },
    {
        key: 'supply_chain.alerts.overstock_threshold',
        name: 'Overstock Alert Threshold',
        description: 'Percentage of max stock to trigger overstock alert',
        module: configuration_entity_1.ConfigurationModule.SUPPLY_CHAIN,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.NUMBER,
        defaultValue: '90',
        minValue: 50,
        maxValue: 100,
        uiComponent: 'SLIDER',
        uiGroup: 'Alerts & Notifications',
        uiOrder: 4,
    },
    {
        key: 'supply_chain.alerts.notification_channels',
        name: 'Alert Notification Channels',
        description: 'Channels for sending supply chain alerts',
        module: configuration_entity_1.ConfigurationModule.SUPPLY_CHAIN,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.ARRAY,
        defaultValue: '["EMAIL", "SMS", "IN_APP"]',
        allowedValues: ['EMAIL', 'SMS', 'WHATSAPP', 'IN_APP', 'SLACK'],
        uiComponent: 'MULTI_SELECT',
        uiGroup: 'Alerts & Notifications',
        uiOrder: 5,
    },
    // Ghana Specific - NPA Compliance
    {
        key: 'supply_chain.npa.stock_reporting_enabled',
        name: 'Enable NPA Stock Reporting',
        description: 'Automatically submit daily stock reports to NPA',
        module: configuration_entity_1.ConfigurationModule.SUPPLY_CHAIN,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.BOOLEAN,
        defaultValue: 'true',
        uiComponent: 'CHECKBOX',
        uiGroup: 'NPA Compliance',
        uiOrder: 1,
    },
    {
        key: 'supply_chain.npa.reporting_time',
        name: 'NPA Reporting Time',
        description: 'Daily time for NPA stock reporting (24-hour format)',
        module: configuration_entity_1.ConfigurationModule.SUPPLY_CHAIN,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.STRING,
        defaultValue: '23:30',
        regexPattern: '^([0-1]?[0-9]|2[0-3]):[0-5][0-9]$',
        uiComponent: 'TIME',
        uiGroup: 'NPA Compliance',
        uiOrder: 2,
    },
    {
        key: 'supply_chain.npa.strategic_stock_percentage',
        name: 'Strategic Stock Percentage',
        description: 'Percentage of total stock designated as strategic reserve',
        module: configuration_entity_1.ConfigurationModule.SUPPLY_CHAIN,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.NUMBER,
        defaultValue: '15',
        minValue: 0,
        maxValue: 50,
        uiComponent: 'SLIDER',
        uiGroup: 'NPA Compliance',
        uiOrder: 3,
    },
    {
        key: 'supply_chain.npa.license_validation',
        name: 'Validate NPA Licenses',
        description: 'Validate supplier NPA licenses before orders',
        module: configuration_entity_1.ConfigurationModule.SUPPLY_CHAIN,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.BOOLEAN,
        defaultValue: 'true',
        uiComponent: 'CHECKBOX',
        uiGroup: 'NPA Compliance',
        uiOrder: 4,
    },
    // BOST Integration
    {
        key: 'supply_chain.bost.allocation_tracking',
        name: 'Track BOST Allocations',
        description: 'Track and manage BOST allocation balances',
        module: configuration_entity_1.ConfigurationModule.SUPPLY_CHAIN,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.BOOLEAN,
        defaultValue: 'true',
        uiComponent: 'CHECKBOX',
        uiGroup: 'BOST Integration',
        uiOrder: 1,
    },
    {
        key: 'supply_chain.bost.auto_allocation_check',
        name: 'Auto Check BOST Allocations',
        description: 'Automatically check BOST allocation availability',
        module: configuration_entity_1.ConfigurationModule.SUPPLY_CHAIN,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.BOOLEAN,
        defaultValue: 'true',
        uiComponent: 'CHECKBOX',
        uiGroup: 'BOST Integration',
        uiOrder: 2,
    },
    {
        key: 'supply_chain.bost.allocation_buffer',
        name: 'BOST Allocation Buffer Percentage',
        description: 'Buffer percentage for BOST allocations',
        module: configuration_entity_1.ConfigurationModule.SUPPLY_CHAIN,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.NUMBER,
        defaultValue: '5',
        minValue: 0,
        maxValue: 20,
        uiComponent: 'SLIDER',
        uiGroup: 'BOST Integration',
        uiOrder: 3,
    },
    // Quality Control
    {
        key: 'supply_chain.quality.inspection_required',
        name: 'Mandatory Quality Inspection',
        description: 'Require quality inspection for all receipts',
        module: configuration_entity_1.ConfigurationModule.SUPPLY_CHAIN,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.BOOLEAN,
        defaultValue: 'true',
        uiComponent: 'CHECKBOX',
        uiGroup: 'Quality Control',
        uiOrder: 1,
    },
    {
        key: 'supply_chain.quality.inspection_sampling',
        name: 'Quality Inspection Sampling Rate',
        description: 'Percentage of receipts to inspect (random sampling)',
        module: configuration_entity_1.ConfigurationModule.SUPPLY_CHAIN,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.NUMBER,
        defaultValue: '10',
        minValue: 1,
        maxValue: 100,
        uiComponent: 'SLIDER',
        uiGroup: 'Quality Control',
        uiOrder: 2,
    },
    {
        key: 'supply_chain.quality.certificate_required',
        name: 'Require Quality Certificates',
        description: 'Require quality certificates from suppliers',
        module: configuration_entity_1.ConfigurationModule.SUPPLY_CHAIN,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.BOOLEAN,
        defaultValue: 'true',
        uiComponent: 'CHECKBOX',
        uiGroup: 'Quality Control',
        uiOrder: 3,
    },
    {
        key: 'supply_chain.quality.batch_tracking',
        name: 'Enable Batch Tracking',
        description: 'Track product batches for quality control',
        module: configuration_entity_1.ConfigurationModule.SUPPLY_CHAIN,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.BOOLEAN,
        defaultValue: 'true',
        uiComponent: 'CHECKBOX',
        uiGroup: 'Quality Control',
        uiOrder: 4,
    },
    // Demand Forecasting
    {
        key: 'supply_chain.forecasting.enabled',
        name: 'Enable Demand Forecasting',
        description: 'Use AI for demand forecasting',
        module: configuration_entity_1.ConfigurationModule.SUPPLY_CHAIN,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.BOOLEAN,
        defaultValue: 'true',
        uiComponent: 'CHECKBOX',
        uiGroup: 'Demand Forecasting',
        uiOrder: 1,
    },
    {
        key: 'supply_chain.forecasting.method',
        name: 'Forecasting Method',
        description: 'Algorithm for demand forecasting',
        module: configuration_entity_1.ConfigurationModule.SUPPLY_CHAIN,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.STRING,
        defaultValue: 'ENSEMBLE',
        allowedValues: ['MOVING_AVERAGE', 'EXPONENTIAL_SMOOTHING', 'ARIMA', 'MACHINE_LEARNING', 'ENSEMBLE'],
        uiComponent: 'SELECT',
        uiGroup: 'Demand Forecasting',
        uiOrder: 2,
    },
    {
        key: 'supply_chain.forecasting.horizon_days',
        name: 'Forecasting Horizon (Days)',
        description: 'Number of days to forecast ahead',
        module: configuration_entity_1.ConfigurationModule.SUPPLY_CHAIN,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.NUMBER,
        defaultValue: '90',
        minValue: 7,
        maxValue: 365,
        uiComponent: 'NUMBER',
        uiGroup: 'Demand Forecasting',
        uiOrder: 3,
    },
    {
        key: 'supply_chain.forecasting.update_frequency',
        name: 'Forecast Update Frequency',
        description: 'How often to update demand forecasts',
        module: configuration_entity_1.ConfigurationModule.SUPPLY_CHAIN,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.STRING,
        defaultValue: 'WEEKLY',
        allowedValues: ['DAILY', 'WEEKLY', 'MONTHLY'],
        uiComponent: 'SELECT',
        uiGroup: 'Demand Forecasting',
        uiOrder: 4,
    },
    // Supplier Management
    {
        key: 'supply_chain.suppliers.performance_tracking',
        name: 'Track Supplier Performance',
        description: 'Automatically track supplier performance metrics',
        module: configuration_entity_1.ConfigurationModule.SUPPLY_CHAIN,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.BOOLEAN,
        defaultValue: 'true',
        uiComponent: 'CHECKBOX',
        uiGroup: 'Supplier Management',
        uiOrder: 1,
    },
    {
        key: 'supply_chain.suppliers.rating_criteria',
        name: 'Supplier Rating Criteria',
        description: 'Criteria for supplier performance rating (JSON)',
        module: configuration_entity_1.ConfigurationModule.SUPPLY_CHAIN,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.JSON,
        defaultValue: '{"quality": 40, "delivery": 30, "price": 20, "service": 10}',
        uiComponent: 'JSON_EDITOR',
        uiGroup: 'Supplier Management',
        uiOrder: 2,
    },
    {
        key: 'supply_chain.suppliers.blacklist_threshold',
        name: 'Supplier Blacklist Threshold',
        description: 'Performance score below which suppliers are blacklisted',
        module: configuration_entity_1.ConfigurationModule.SUPPLY_CHAIN,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.NUMBER,
        defaultValue: '30',
        minValue: 0,
        maxValue: 100,
        uiComponent: 'SLIDER',
        uiGroup: 'Supplier Management',
        uiOrder: 3,
    },
    // Pricing and Cost Management
    {
        key: 'supply_chain.pricing.cost_update_method',
        name: 'Inventory Cost Update Method',
        description: 'How to update inventory costs',
        module: configuration_entity_1.ConfigurationModule.SUPPLY_CHAIN,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.STRING,
        defaultValue: 'WEIGHTED_AVERAGE',
        allowedValues: ['LAST_COST', 'WEIGHTED_AVERAGE', 'STANDARD_COST'],
        uiComponent: 'SELECT',
        uiGroup: 'Pricing & Costs',
        uiOrder: 1,
    },
    {
        key: 'supply_chain.pricing.landed_cost_calculation',
        name: 'Include Landed Costs',
        description: 'Include transportation and other costs in inventory valuation',
        module: configuration_entity_1.ConfigurationModule.SUPPLY_CHAIN,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.BOOLEAN,
        defaultValue: 'true',
        uiComponent: 'CHECKBOX',
        uiGroup: 'Pricing & Costs',
        uiOrder: 2,
    },
    {
        key: 'supply_chain.pricing.currency_hedging',
        name: 'Enable Currency Hedging',
        description: 'Track currency hedging for foreign purchases',
        module: configuration_entity_1.ConfigurationModule.SUPPLY_CHAIN,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.BOOLEAN,
        defaultValue: 'true',
        uiComponent: 'CHECKBOX',
        uiGroup: 'Pricing & Costs',
        uiOrder: 3,
    },
    // Environmental Compliance
    {
        key: 'supply_chain.environmental.epa_reporting',
        name: 'Enable EPA Environmental Reporting',
        description: 'Generate reports for Environmental Protection Agency',
        module: configuration_entity_1.ConfigurationModule.SUPPLY_CHAIN,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.BOOLEAN,
        defaultValue: 'true',
        uiComponent: 'CHECKBOX',
        uiGroup: 'Environmental Compliance',
        uiOrder: 1,
    },
    {
        key: 'supply_chain.environmental.carbon_tracking',
        name: 'Track Carbon Footprint',
        description: 'Track carbon footprint of supply chain operations',
        module: configuration_entity_1.ConfigurationModule.SUPPLY_CHAIN,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.BOOLEAN,
        defaultValue: 'true',
        uiComponent: 'CHECKBOX',
        uiGroup: 'Environmental Compliance',
        uiOrder: 2,
    },
    {
        key: 'supply_chain.environmental.waste_tracking',
        name: 'Track Waste Generation',
        description: 'Track and report waste generation',
        module: configuration_entity_1.ConfigurationModule.SUPPLY_CHAIN,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.BOOLEAN,
        defaultValue: 'true',
        uiComponent: 'CHECKBOX',
        uiGroup: 'Environmental Compliance',
        uiOrder: 3,
    },
    // Performance and Analytics
    {
        key: 'supply_chain.analytics.kpi_dashboard',
        name: 'Enable KPI Dashboard',
        description: 'Show supply chain KPI dashboard',
        module: configuration_entity_1.ConfigurationModule.SUPPLY_CHAIN,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.BOOLEAN,
        defaultValue: 'true',
        uiComponent: 'CHECKBOX',
        uiGroup: 'Analytics & Performance',
        uiOrder: 1,
    },
    {
        key: 'supply_chain.analytics.refresh_interval',
        name: 'Analytics Refresh Interval (Minutes)',
        description: 'How often to refresh supply chain analytics',
        module: configuration_entity_1.ConfigurationModule.SUPPLY_CHAIN,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.NUMBER,
        defaultValue: '15',
        minValue: 5,
        maxValue: 60,
        uiComponent: 'NUMBER',
        uiGroup: 'Analytics & Performance',
        uiOrder: 2,
    },
    {
        key: 'supply_chain.analytics.benchmark_enabled',
        name: 'Enable Industry Benchmarking',
        description: 'Compare performance against industry benchmarks',
        module: configuration_entity_1.ConfigurationModule.SUPPLY_CHAIN,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.BOOLEAN,
        defaultValue: 'true',
        uiComponent: 'CHECKBOX',
        uiGroup: 'Analytics & Performance',
        uiOrder: 3,
    },
];
//# sourceMappingURL=supply-chain-config.schema.js.map