"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.UPPFConfigurationSchema = void 0;
const configuration_entity_1 = require("../entities/configuration.entity");
exports.UPPFConfigurationSchema = [
    // UPPF General Configuration
    {
        key: 'uppf.general.scheme_enabled',
        name: 'UPPF Scheme Enabled',
        description: 'Enable Universal Petroleum Price Fund scheme',
        module: configuration_entity_1.ConfigurationModule.UPPF_CLAIMS,
        type: configuration_entity_1.ConfigurationType.SYSTEM,
        dataType: configuration_entity_1.ConfigurationDataType.BOOLEAN,
        defaultValue: 'true',
        isRequired: true,
        uiComponent: 'CHECKBOX',
        uiGroup: 'General',
        uiOrder: 1,
        impactLevel: 'CRITICAL',
    },
    {
        key: 'uppf.general.base_currency',
        name: 'UPPF Base Currency',
        description: 'Base currency for UPPF calculations',
        module: configuration_entity_1.ConfigurationModule.UPPF_CLAIMS,
        type: configuration_entity_1.ConfigurationType.SYSTEM,
        dataType: configuration_entity_1.ConfigurationDataType.STRING,
        defaultValue: 'GHS',
        allowedValues: ['GHS', 'USD'],
        isRequired: true,
        uiComponent: 'SELECT',
        uiGroup: 'General',
        uiOrder: 2,
    },
    {
        key: 'uppf.general.decimal_places',
        name: 'UPPF Decimal Places',
        description: 'Decimal places for UPPF amount calculations',
        module: configuration_entity_1.ConfigurationModule.UPPF_CLAIMS,
        type: configuration_entity_1.ConfigurationType.SYSTEM,
        dataType: configuration_entity_1.ConfigurationDataType.NUMBER,
        defaultValue: '4',
        minValue: 2,
        maxValue: 8,
        uiComponent: 'NUMBER',
        uiGroup: 'General',
        uiOrder: 3,
    },
    {
        key: 'uppf.general.rounding_method',
        name: 'UPPF Rounding Method',
        description: 'Method for rounding UPPF calculations',
        module: configuration_entity_1.ConfigurationModule.UPPF_CLAIMS,
        type: configuration_entity_1.ConfigurationType.SYSTEM,
        dataType: configuration_entity_1.ConfigurationDataType.STRING,
        defaultValue: 'ROUND_HALF_UP',
        allowedValues: ['ROUND_HALF_UP', 'ROUND_HALF_DOWN', 'ROUND_UP', 'ROUND_DOWN'],
        uiComponent: 'SELECT',
        uiGroup: 'General',
        uiOrder: 4,
    },
    // UPPF Rate Configuration
    {
        key: 'uppf.rates.petrol_levy_per_litre',
        name: 'Petrol UPPF Levy (per litre)',
        description: 'UPPF levy rate for petrol in pesewas per litre',
        module: configuration_entity_1.ConfigurationModule.UPPF_CLAIMS,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.NUMBER,
        defaultValue: '16.0000',
        minValue: 0,
        maxValue: 100,
        uiComponent: 'NUMBER',
        uiGroup: 'Levy Rates',
        uiOrder: 1,
        changeFrequency: 0,
        requiresRestart: false,
    },
    {
        key: 'uppf.rates.diesel_levy_per_litre',
        name: 'Diesel UPPF Levy (per litre)',
        description: 'UPPF levy rate for diesel in pesewas per litre',
        module: configuration_entity_1.ConfigurationModule.UPPF_CLAIMS,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.NUMBER,
        defaultValue: '14.0000',
        minValue: 0,
        maxValue: 100,
        uiComponent: 'NUMBER',
        uiGroup: 'Levy Rates',
        uiOrder: 2,
    },
    {
        key: 'uppf.rates.kerosene_levy_per_litre',
        name: 'Kerosene UPPF Levy (per litre)',
        description: 'UPPF levy rate for kerosene in pesewas per litre',
        module: configuration_entity_1.ConfigurationModule.UPPF_CLAIMS,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.NUMBER,
        defaultValue: '0.0000',
        minValue: 0,
        maxValue: 100,
        uiComponent: 'NUMBER',
        uiGroup: 'Levy Rates',
        uiOrder: 3,
    },
    {
        key: 'uppf.rates.lpg_levy_per_kg',
        name: 'LPG UPPF Levy (per kg)',
        description: 'UPPF levy rate for LPG in pesewas per kilogram',
        module: configuration_entity_1.ConfigurationModule.UPPF_CLAIMS,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.NUMBER,
        defaultValue: '0.0000',
        minValue: 0,
        maxValue: 100,
        uiComponent: 'NUMBER',
        uiGroup: 'Levy Rates',
        uiOrder: 4,
    },
    {
        key: 'uppf.rates.effective_date',
        name: 'Levy Rates Effective Date',
        description: 'Date when current levy rates become effective',
        module: configuration_entity_1.ConfigurationModule.UPPF_CLAIMS,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.DATE,
        defaultValue: '2024-01-01',
        uiComponent: 'DATE',
        uiGroup: 'Levy Rates',
        uiOrder: 5,
    },
    {
        key: 'uppf.rates.rate_change_notification_days',
        name: 'Rate Change Notification Period',
        description: 'Days before rate change to notify stakeholders',
        module: configuration_entity_1.ConfigurationModule.UPPF_CLAIMS,
        type: configuration_entity_1.ConfigurationType.SYSTEM,
        dataType: configuration_entity_1.ConfigurationDataType.NUMBER,
        defaultValue: '7',
        minValue: 1,
        maxValue: 30,
        uiComponent: 'NUMBER',
        uiGroup: 'Levy Rates',
        uiOrder: 6,
    },
    // Claims Processing Configuration
    {
        key: 'uppf.claims.auto_calculation_enabled',
        name: 'Auto Calculate Claims',
        description: 'Automatically calculate UPPF claims from sales data',
        module: configuration_entity_1.ConfigurationModule.UPPF_CLAIMS,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.BOOLEAN,
        defaultValue: 'true',
        uiComponent: 'CHECKBOX',
        uiGroup: 'Claims Processing',
        uiOrder: 1,
    },
    {
        key: 'uppf.claims.calculation_frequency',
        name: 'Claims Calculation Frequency',
        description: 'How often to calculate UPPF claims',
        module: configuration_entity_1.ConfigurationModule.UPPF_CLAIMS,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.STRING,
        defaultValue: 'DAILY',
        allowedValues: ['REAL_TIME', 'HOURLY', 'DAILY', 'WEEKLY', 'MONTHLY', 'MANUAL'],
        uiComponent: 'SELECT',
        uiGroup: 'Claims Processing',
        uiOrder: 2,
    },
    {
        key: 'uppf.claims.batch_size',
        name: 'Claims Batch Processing Size',
        description: 'Number of transactions to process in each batch',
        module: configuration_entity_1.ConfigurationModule.UPPF_CLAIMS,
        type: configuration_entity_1.ConfigurationType.SYSTEM,
        dataType: configuration_entity_1.ConfigurationDataType.NUMBER,
        defaultValue: '10000',
        minValue: 100,
        maxValue: 100000,
        uiComponent: 'NUMBER',
        uiGroup: 'Claims Processing',
        uiOrder: 3,
    },
    {
        key: 'uppf.claims.min_claim_amount',
        name: 'Minimum Claim Amount',
        description: 'Minimum amount required to submit UPPF claim',
        module: configuration_entity_1.ConfigurationModule.UPPF_CLAIMS,
        type: configuration_entity_1.ConfigurationType.SYSTEM,
        dataType: configuration_entity_1.ConfigurationDataType.NUMBER,
        defaultValue: '100.00',
        minValue: 0,
        uiComponent: 'NUMBER',
        uiGroup: 'Claims Processing',
        uiOrder: 4,
    },
    {
        key: 'uppf.claims.max_claim_amount',
        name: 'Maximum Claim Amount',
        description: 'Maximum amount allowed for single UPPF claim',
        module: configuration_entity_1.ConfigurationModule.UPPF_CLAIMS,
        type: configuration_entity_1.ConfigurationType.SYSTEM,
        dataType: configuration_entity_1.ConfigurationDataType.NUMBER,
        defaultValue: '10000000.00',
        minValue: 1000,
        uiComponent: 'NUMBER',
        uiGroup: 'Claims Processing',
        uiOrder: 5,
    },
    {
        key: 'uppf.claims.require_manual_approval',
        name: 'Require Manual Approval',
        description: 'All claims must be manually approved before submission',
        module: configuration_entity_1.ConfigurationModule.UPPF_CLAIMS,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.BOOLEAN,
        defaultValue: 'true',
        uiComponent: 'CHECKBOX',
        uiGroup: 'Claims Processing',
        uiOrder: 6,
    },
    {
        key: 'uppf.claims.approval_threshold',
        name: 'Approval Threshold Amount',
        description: 'Claims above this amount require additional approval',
        module: configuration_entity_1.ConfigurationModule.UPPF_CLAIMS,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.NUMBER,
        defaultValue: '50000.00',
        minValue: 0,
        uiComponent: 'NUMBER',
        uiGroup: 'Claims Processing',
        uiOrder: 7,
    },
    {
        key: 'uppf.claims.dual_approval_required',
        name: 'Dual Approval Required',
        description: 'Claims require approval from two authorized persons',
        module: configuration_entity_1.ConfigurationModule.UPPF_CLAIMS,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.BOOLEAN,
        defaultValue: 'true',
        uiComponent: 'CHECKBOX',
        uiGroup: 'Claims Processing',
        uiOrder: 8,
    },
    // Submission Configuration
    {
        key: 'uppf.submission.auto_submit_enabled',
        name: 'Auto Submit Claims',
        description: 'Automatically submit approved claims to NPA',
        module: configuration_entity_1.ConfigurationModule.UPPF_CLAIMS,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.BOOLEAN,
        defaultValue: 'false',
        uiComponent: 'CHECKBOX',
        uiGroup: 'Submission',
        uiOrder: 1,
    },
    {
        key: 'uppf.submission.submission_frequency',
        name: 'Submission Frequency',
        description: 'How often to submit claims to NPA',
        module: configuration_entity_1.ConfigurationModule.UPPF_CLAIMS,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.STRING,
        defaultValue: 'MONTHLY',
        allowedValues: ['DAILY', 'WEEKLY', 'MONTHLY', 'QUARTERLY', 'MANUAL'],
        uiComponent: 'SELECT',
        uiGroup: 'Submission',
        uiOrder: 2,
    },
    {
        key: 'uppf.submission.submission_day_of_month',
        name: 'Monthly Submission Day',
        description: 'Day of month to submit monthly claims (1-28)',
        module: configuration_entity_1.ConfigurationModule.UPPF_CLAIMS,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.NUMBER,
        defaultValue: '15',
        minValue: 1,
        maxValue: 28,
        uiComponent: 'NUMBER',
        uiGroup: 'Submission',
        uiOrder: 3,
    },
    {
        key: 'uppf.submission.deadline_days_before_month_end',
        name: 'Submission Deadline (Days Before Month End)',
        description: 'Days before month end when submission is due',
        module: configuration_entity_1.ConfigurationModule.UPPF_CLAIMS,
        type: configuration_entity_1.ConfigurationType.SYSTEM,
        dataType: configuration_entity_1.ConfigurationDataType.NUMBER,
        defaultValue: '5',
        minValue: 1,
        maxValue: 15,
        uiComponent: 'NUMBER',
        uiGroup: 'Submission',
        uiOrder: 4,
    },
    {
        key: 'uppf.submission.retry_attempts',
        name: 'Submission Retry Attempts',
        description: 'Number of times to retry failed submissions',
        module: configuration_entity_1.ConfigurationModule.UPPF_CLAIMS,
        type: configuration_entity_1.ConfigurationType.SYSTEM,
        dataType: configuration_entity_1.ConfigurationDataType.NUMBER,
        defaultValue: '3',
        minValue: 1,
        maxValue: 10,
        uiComponent: 'NUMBER',
        uiGroup: 'Submission',
        uiOrder: 5,
    },
    {
        key: 'uppf.submission.retry_delay_minutes',
        name: 'Retry Delay (Minutes)',
        description: 'Minutes to wait between submission retry attempts',
        module: configuration_entity_1.ConfigurationModule.UPPF_CLAIMS,
        type: configuration_entity_1.ConfigurationType.SYSTEM,
        dataType: configuration_entity_1.ConfigurationDataType.NUMBER,
        defaultValue: '30',
        minValue: 5,
        maxValue: 1440,
        uiComponent: 'NUMBER',
        uiGroup: 'Submission',
        uiOrder: 6,
    },
    // NPA Integration Configuration
    {
        key: 'uppf.npa.api_endpoint',
        name: 'NPA API Endpoint',
        description: 'NPA UPPF claims submission API endpoint',
        module: configuration_entity_1.ConfigurationModule.UPPF_CLAIMS,
        type: configuration_entity_1.ConfigurationType.SYSTEM,
        dataType: configuration_entity_1.ConfigurationDataType.STRING,
        defaultValue: 'https://api.npa.gov.gh/uppf/claims',
        isRequired: true,
        isSensitive: true,
        uiComponent: 'INPUT',
        uiGroup: 'NPA Integration',
        uiOrder: 1,
    },
    {
        key: 'uppf.npa.api_key',
        name: 'NPA API Key',
        description: 'API key for NPA integration',
        module: configuration_entity_1.ConfigurationModule.UPPF_CLAIMS,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.ENCRYPTED,
        isRequired: true,
        isSensitive: true,
        isEncrypted: true,
        uiComponent: 'PASSWORD',
        uiGroup: 'NPA Integration',
        uiOrder: 2,
    },
    {
        key: 'uppf.npa.connection_timeout_seconds',
        name: 'NPA Connection Timeout (Seconds)',
        description: 'Timeout for NPA API connections in seconds',
        module: configuration_entity_1.ConfigurationModule.UPPF_CLAIMS,
        type: configuration_entity_1.ConfigurationType.SYSTEM,
        dataType: configuration_entity_1.ConfigurationDataType.NUMBER,
        defaultValue: '30',
        minValue: 5,
        maxValue: 300,
        uiComponent: 'NUMBER',
        uiGroup: 'NPA Integration',
        uiOrder: 3,
    },
    {
        key: 'uppf.npa.read_timeout_seconds',
        name: 'NPA Read Timeout (Seconds)',
        description: 'Read timeout for NPA API responses in seconds',
        module: configuration_entity_1.ConfigurationModule.UPPF_CLAIMS,
        type: configuration_entity_1.ConfigurationType.SYSTEM,
        dataType: configuration_entity_1.ConfigurationDataType.NUMBER,
        defaultValue: '60',
        minValue: 10,
        maxValue: 600,
        uiComponent: 'NUMBER',
        uiGroup: 'NPA Integration',
        uiOrder: 4,
    },
    {
        key: 'uppf.npa.ssl_verification_enabled',
        name: 'SSL Verification Enabled',
        description: 'Enable SSL certificate verification for NPA API',
        module: configuration_entity_1.ConfigurationModule.UPPF_CLAIMS,
        type: configuration_entity_1.ConfigurationType.SYSTEM,
        dataType: configuration_entity_1.ConfigurationDataType.BOOLEAN,
        defaultValue: 'true',
        uiComponent: 'CHECKBOX',
        uiGroup: 'NPA Integration',
        uiOrder: 5,
    },
    {
        key: 'uppf.npa.response_format',
        name: 'NPA Response Format',
        description: 'Expected format for NPA API responses',
        module: configuration_entity_1.ConfigurationModule.UPPF_CLAIMS,
        type: configuration_entity_1.ConfigurationType.SYSTEM,
        dataType: configuration_entity_1.ConfigurationDataType.STRING,
        defaultValue: 'JSON',
        allowedValues: ['JSON', 'XML'],
        uiComponent: 'SELECT',
        uiGroup: 'NPA Integration',
        uiOrder: 6,
    },
    // Validation Configuration
    {
        key: 'uppf.validation.sales_data_required_fields',
        name: 'Required Sales Data Fields',
        description: 'Fields required in sales data for UPPF calculations',
        module: configuration_entity_1.ConfigurationModule.UPPF_CLAIMS,
        type: configuration_entity_1.ConfigurationType.SYSTEM,
        dataType: configuration_entity_1.ConfigurationDataType.ARRAY,
        defaultValue: '["transaction_date", "product_code", "quantity", "unit_price", "customer_id"]',
        uiComponent: 'MULTI_SELECT',
        uiGroup: 'Validation',
        uiOrder: 1,
    },
    {
        key: 'uppf.validation.transaction_date_range_days',
        name: 'Valid Transaction Date Range (Days)',
        description: 'Number of days back to accept transaction dates',
        module: configuration_entity_1.ConfigurationModule.UPPF_CLAIMS,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.NUMBER,
        defaultValue: '90',
        minValue: 30,
        maxValue: 365,
        uiComponent: 'NUMBER',
        uiGroup: 'Validation',
        uiOrder: 2,
    },
    {
        key: 'uppf.validation.allow_future_transactions',
        name: 'Allow Future Transactions',
        description: 'Allow transactions with future dates for UPPF claims',
        module: configuration_entity_1.ConfigurationModule.UPPF_CLAIMS,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.BOOLEAN,
        defaultValue: 'false',
        uiComponent: 'CHECKBOX',
        uiGroup: 'Validation',
        uiOrder: 3,
    },
    {
        key: 'uppf.validation.max_quantity_per_transaction',
        name: 'Maximum Quantity Per Transaction',
        description: 'Maximum quantity allowed in single transaction (litres/kg)',
        module: configuration_entity_1.ConfigurationModule.UPPF_CLAIMS,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.NUMBER,
        defaultValue: '50000',
        minValue: 1,
        maxValue: 1000000,
        uiComponent: 'NUMBER',
        uiGroup: 'Validation',
        uiOrder: 4,
    },
    {
        key: 'uppf.validation.min_unit_price',
        name: 'Minimum Unit Price',
        description: 'Minimum unit price for products (GHS)',
        module: configuration_entity_1.ConfigurationModule.UPPF_CLAIMS,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.NUMBER,
        defaultValue: '0.50',
        minValue: 0,
        uiComponent: 'NUMBER',
        uiGroup: 'Validation',
        uiOrder: 5,
    },
    {
        key: 'uppf.validation.max_unit_price',
        name: 'Maximum Unit Price',
        description: 'Maximum unit price for products (GHS)',
        module: configuration_entity_1.ConfigurationModule.UPPF_CLAIMS,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.NUMBER,
        defaultValue: '20.00',
        minValue: 1,
        uiComponent: 'NUMBER',
        uiGroup: 'Validation',
        uiOrder: 6,
    },
    // Reporting Configuration
    {
        key: 'uppf.reporting.auto_generate_reports',
        name: 'Auto Generate Reports',
        description: 'Automatically generate UPPF reports',
        module: configuration_entity_1.ConfigurationModule.UPPF_CLAIMS,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.BOOLEAN,
        defaultValue: 'true',
        uiComponent: 'CHECKBOX',
        uiGroup: 'Reporting',
        uiOrder: 1,
    },
    {
        key: 'uppf.reporting.report_frequency',
        name: 'Report Generation Frequency',
        description: 'How often to generate UPPF reports',
        module: configuration_entity_1.ConfigurationModule.UPPF_CLAIMS,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.STRING,
        defaultValue: 'MONTHLY',
        allowedValues: ['DAILY', 'WEEKLY', 'MONTHLY', 'QUARTERLY', 'ANNUALLY'],
        uiComponent: 'SELECT',
        uiGroup: 'Reporting',
        uiOrder: 2,
    },
    {
        key: 'uppf.reporting.include_zero_claims',
        name: 'Include Zero Value Claims',
        description: 'Include zero value claims in reports',
        module: configuration_entity_1.ConfigurationModule.UPPF_CLAIMS,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.BOOLEAN,
        defaultValue: 'false',
        uiComponent: 'CHECKBOX',
        uiGroup: 'Reporting',
        uiOrder: 3,
    },
    {
        key: 'uppf.reporting.default_format',
        name: 'Default Report Format',
        description: 'Default format for UPPF reports',
        module: configuration_entity_1.ConfigurationModule.UPPF_CLAIMS,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.STRING,
        defaultValue: 'PDF',
        allowedValues: ['PDF', 'EXCEL', 'CSV', 'JSON'],
        uiComponent: 'SELECT',
        uiGroup: 'Reporting',
        uiOrder: 4,
    },
    {
        key: 'uppf.reporting.report_retention_months',
        name: 'Report Retention Period (Months)',
        description: 'Number of months to retain generated reports',
        module: configuration_entity_1.ConfigurationModule.UPPF_CLAIMS,
        type: configuration_entity_1.ConfigurationType.SYSTEM,
        dataType: configuration_entity_1.ConfigurationDataType.NUMBER,
        defaultValue: '36',
        minValue: 12,
        maxValue: 120,
        uiComponent: 'NUMBER',
        uiGroup: 'Reporting',
        uiOrder: 5,
    },
    // Audit and Compliance Configuration
    {
        key: 'uppf.audit.enable_detailed_logging',
        name: 'Enable Detailed Logging',
        description: 'Enable detailed audit logging for UPPF operations',
        module: configuration_entity_1.ConfigurationModule.UPPF_CLAIMS,
        type: configuration_entity_1.ConfigurationType.SYSTEM,
        dataType: configuration_entity_1.ConfigurationDataType.BOOLEAN,
        defaultValue: 'true',
        uiComponent: 'CHECKBOX',
        uiGroup: 'Audit & Compliance',
        uiOrder: 1,
    },
    {
        key: 'uppf.audit.log_level',
        name: 'Audit Log Level',
        description: 'Level of detail for audit logging',
        module: configuration_entity_1.ConfigurationModule.UPPF_CLAIMS,
        type: configuration_entity_1.ConfigurationType.SYSTEM,
        dataType: configuration_entity_1.ConfigurationDataType.STRING,
        defaultValue: 'INFO',
        allowedValues: ['DEBUG', 'INFO', 'WARN', 'ERROR'],
        uiComponent: 'SELECT',
        uiGroup: 'Audit & Compliance',
        uiOrder: 2,
    },
    {
        key: 'uppf.audit.log_retention_days',
        name: 'Audit Log Retention (Days)',
        description: 'Number of days to retain audit logs',
        module: configuration_entity_1.ConfigurationModule.UPPF_CLAIMS,
        type: configuration_entity_1.ConfigurationType.SYSTEM,
        dataType: configuration_entity_1.ConfigurationDataType.NUMBER,
        defaultValue: '2555',
        minValue: 365,
        maxValue: 3650,
        uiComponent: 'NUMBER',
        uiGroup: 'Audit & Compliance',
        uiOrder: 3,
    },
    {
        key: 'uppf.audit.track_data_changes',
        name: 'Track Data Changes',
        description: 'Track all changes to UPPF data',
        module: configuration_entity_1.ConfigurationModule.UPPF_CLAIMS,
        type: configuration_entity_1.ConfigurationType.SYSTEM,
        dataType: configuration_entity_1.ConfigurationDataType.BOOLEAN,
        defaultValue: 'true',
        uiComponent: 'CHECKBOX',
        uiGroup: 'Audit & Compliance',
        uiOrder: 4,
    },
    {
        key: 'uppf.audit.require_change_justification',
        name: 'Require Change Justification',
        description: 'Require justification for all UPPF data changes',
        module: configuration_entity_1.ConfigurationModule.UPPF_CLAIMS,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.BOOLEAN,
        defaultValue: 'true',
        uiComponent: 'CHECKBOX',
        uiGroup: 'Audit & Compliance',
        uiOrder: 5,
    },
    // Notification Configuration
    {
        key: 'uppf.notifications.claim_submission_success',
        name: 'Notify on Successful Claim Submission',
        description: 'Send notifications when claims are successfully submitted',
        module: configuration_entity_1.ConfigurationModule.UPPF_CLAIMS,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.BOOLEAN,
        defaultValue: 'true',
        uiComponent: 'CHECKBOX',
        uiGroup: 'Notifications',
        uiOrder: 1,
    },
    {
        key: 'uppf.notifications.claim_submission_failure',
        name: 'Notify on Claim Submission Failure',
        description: 'Send notifications when claim submissions fail',
        module: configuration_entity_1.ConfigurationModule.UPPF_CLAIMS,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.BOOLEAN,
        defaultValue: 'true',
        uiComponent: 'CHECKBOX',
        uiGroup: 'Notifications',
        uiOrder: 2,
    },
    {
        key: 'uppf.notifications.approval_required',
        name: 'Notify When Approval Required',
        description: 'Send notifications when claims require approval',
        module: configuration_entity_1.ConfigurationModule.UPPF_CLAIMS,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.BOOLEAN,
        defaultValue: 'true',
        uiComponent: 'CHECKBOX',
        uiGroup: 'Notifications',
        uiOrder: 3,
    },
    {
        key: 'uppf.notifications.deadline_reminder_days',
        name: 'Deadline Reminder Days',
        description: 'Days before submission deadline to send reminders',
        module: configuration_entity_1.ConfigurationModule.UPPF_CLAIMS,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.NUMBER,
        defaultValue: '3',
        minValue: 1,
        maxValue: 30,
        uiComponent: 'NUMBER',
        uiGroup: 'Notifications',
        uiOrder: 4,
    },
    {
        key: 'uppf.notifications.email_recipients',
        name: 'Notification Email Recipients',
        description: 'Email addresses to receive UPPF notifications',
        module: configuration_entity_1.ConfigurationModule.UPPF_CLAIMS,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.ARRAY,
        defaultValue: '[]',
        uiComponent: 'MULTI_INPUT',
        uiGroup: 'Notifications',
        uiOrder: 5,
    },
    {
        key: 'uppf.notifications.sms_enabled',
        name: 'SMS Notifications Enabled',
        description: 'Enable SMS notifications for critical UPPF events',
        module: configuration_entity_1.ConfigurationModule.UPPF_CLAIMS,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.BOOLEAN,
        defaultValue: 'false',
        uiComponent: 'CHECKBOX',
        uiGroup: 'Notifications',
        uiOrder: 6,
    },
    // Performance and Caching Configuration
    {
        key: 'uppf.performance.enable_caching',
        name: 'Enable UPPF Data Caching',
        description: 'Enable caching for UPPF calculations and data',
        module: configuration_entity_1.ConfigurationModule.UPPF_CLAIMS,
        type: configuration_entity_1.ConfigurationType.SYSTEM,
        dataType: configuration_entity_1.ConfigurationDataType.BOOLEAN,
        defaultValue: 'true',
        uiComponent: 'CHECKBOX',
        uiGroup: 'Performance',
        uiOrder: 1,
    },
    {
        key: 'uppf.performance.cache_ttl_minutes',
        name: 'Cache TTL (Minutes)',
        description: 'Time-to-live for cached UPPF data in minutes',
        module: configuration_entity_1.ConfigurationModule.UPPF_CLAIMS,
        type: configuration_entity_1.ConfigurationType.SYSTEM,
        dataType: configuration_entity_1.ConfigurationDataType.NUMBER,
        defaultValue: '30',
        minValue: 5,
        maxValue: 1440,
        uiComponent: 'NUMBER',
        uiGroup: 'Performance',
        uiOrder: 2,
    },
    {
        key: 'uppf.performance.max_concurrent_calculations',
        name: 'Max Concurrent Calculations',
        description: 'Maximum number of concurrent UPPF calculations',
        module: configuration_entity_1.ConfigurationModule.UPPF_CLAIMS,
        type: configuration_entity_1.ConfigurationType.SYSTEM,
        dataType: configuration_entity_1.ConfigurationDataType.NUMBER,
        defaultValue: '5',
        minValue: 1,
        maxValue: 20,
        uiComponent: 'NUMBER',
        uiGroup: 'Performance',
        uiOrder: 3,
    },
    {
        key: 'uppf.performance.calculation_timeout_minutes',
        name: 'Calculation Timeout (Minutes)',
        description: 'Timeout for UPPF calculations in minutes',
        module: configuration_entity_1.ConfigurationModule.UPPF_CLAIMS,
        type: configuration_entity_1.ConfigurationType.SYSTEM,
        dataType: configuration_entity_1.ConfigurationDataType.NUMBER,
        defaultValue: '60',
        minValue: 5,
        maxValue: 300,
        uiComponent: 'NUMBER',
        uiGroup: 'Performance',
        uiOrder: 4,
    },
    // Data Backup and Recovery Configuration
    {
        key: 'uppf.backup.auto_backup_enabled',
        name: 'Auto Backup Enabled',
        description: 'Enable automatic backup of UPPF data',
        module: configuration_entity_1.ConfigurationModule.UPPF_CLAIMS,
        type: configuration_entity_1.ConfigurationType.SYSTEM,
        dataType: configuration_entity_1.ConfigurationDataType.BOOLEAN,
        defaultValue: 'true',
        uiComponent: 'CHECKBOX',
        uiGroup: 'Backup & Recovery',
        uiOrder: 1,
    },
    {
        key: 'uppf.backup.backup_frequency',
        name: 'Backup Frequency',
        description: 'Frequency for automatic UPPF data backups',
        module: configuration_entity_1.ConfigurationModule.UPPF_CLAIMS,
        type: configuration_entity_1.ConfigurationType.SYSTEM,
        dataType: configuration_entity_1.ConfigurationDataType.STRING,
        defaultValue: 'DAILY',
        allowedValues: ['HOURLY', 'DAILY', 'WEEKLY', 'MONTHLY'],
        uiComponent: 'SELECT',
        uiGroup: 'Backup & Recovery',
        uiOrder: 2,
    },
    {
        key: 'uppf.backup.retention_days',
        name: 'Backup Retention Days',
        description: 'Number of days to retain backup files',
        module: configuration_entity_1.ConfigurationModule.UPPF_CLAIMS,
        type: configuration_entity_1.ConfigurationType.SYSTEM,
        dataType: configuration_entity_1.ConfigurationDataType.NUMBER,
        defaultValue: '90',
        minValue: 7,
        maxValue: 2555,
        uiComponent: 'NUMBER',
        uiGroup: 'Backup & Recovery',
        uiOrder: 3,
    },
    {
        key: 'uppf.backup.compression_enabled',
        name: 'Backup Compression Enabled',
        description: 'Enable compression for backup files',
        module: configuration_entity_1.ConfigurationModule.UPPF_CLAIMS,
        type: configuration_entity_1.ConfigurationType.SYSTEM,
        dataType: configuration_entity_1.ConfigurationDataType.BOOLEAN,
        defaultValue: 'true',
        uiComponent: 'CHECKBOX',
        uiGroup: 'Backup & Recovery',
        uiOrder: 4,
    },
    // Security Configuration
    {
        key: 'uppf.security.data_encryption_enabled',
        name: 'Data Encryption Enabled',
        description: 'Enable encryption for sensitive UPPF data',
        module: configuration_entity_1.ConfigurationModule.UPPF_CLAIMS,
        type: configuration_entity_1.ConfigurationType.SYSTEM,
        dataType: configuration_entity_1.ConfigurationDataType.BOOLEAN,
        defaultValue: 'true',
        isRequired: true,
        uiComponent: 'CHECKBOX',
        uiGroup: 'Security',
        uiOrder: 1,
    },
    {
        key: 'uppf.security.require_2fa_for_submission',
        name: 'Require 2FA for Submission',
        description: 'Require two-factor authentication for claim submissions',
        module: configuration_entity_1.ConfigurationModule.UPPF_CLAIMS,
        type: configuration_entity_1.ConfigurationType.TENANT,
        dataType: configuration_entity_1.ConfigurationDataType.BOOLEAN,
        defaultValue: 'true',
        uiComponent: 'CHECKBOX',
        uiGroup: 'Security',
        uiOrder: 2,
    },
    {
        key: 'uppf.security.ip_whitelist_enabled',
        name: 'IP Whitelist Enabled',
        description: 'Enable IP whitelist for UPPF API access',
        module: configuration_entity_1.ConfigurationModule.UPPF_CLAIMS,
        type: configuration_entity_1.ConfigurationType.SYSTEM,
        dataType: configuration_entity_1.ConfigurationDataType.BOOLEAN,
        defaultValue: 'false',
        uiComponent: 'CHECKBOX',
        uiGroup: 'Security',
        uiOrder: 3,
    },
    {
        key: 'uppf.security.allowed_ip_addresses',
        name: 'Allowed IP Addresses',
        description: 'IP addresses allowed to access UPPF functionality',
        module: configuration_entity_1.ConfigurationModule.UPPF_CLAIMS,
        type: configuration_entity_1.ConfigurationType.SYSTEM,
        dataType: configuration_entity_1.ConfigurationDataType.ARRAY,
        defaultValue: '[]',
        uiComponent: 'MULTI_INPUT',
        uiGroup: 'Security',
        uiOrder: 4,
    },
    {
        key: 'uppf.security.session_timeout_minutes',
        name: 'Session Timeout (Minutes)',
        description: 'Session timeout for UPPF operations in minutes',
        module: configuration_entity_1.ConfigurationModule.UPPF_CLAIMS,
        type: configuration_entity_1.ConfigurationType.SYSTEM,
        dataType: configuration_entity_1.ConfigurationDataType.NUMBER,
        defaultValue: '30',
        minValue: 5,
        maxValue: 480,
        uiComponent: 'NUMBER',
        uiGroup: 'Security',
        uiOrder: 5,
    },
    // Integration Monitoring
    {
        key: 'uppf.monitoring.health_check_enabled',
        name: 'Health Check Enabled',
        description: 'Enable health checks for UPPF system components',
        module: configuration_entity_1.ConfigurationModule.UPPF_CLAIMS,
        type: configuration_entity_1.ConfigurationType.SYSTEM,
        dataType: configuration_entity_1.ConfigurationDataType.BOOLEAN,
        defaultValue: 'true',
        uiComponent: 'CHECKBOX',
        uiGroup: 'Monitoring',
        uiOrder: 1,
    },
    {
        key: 'uppf.monitoring.health_check_interval_minutes',
        name: 'Health Check Interval (Minutes)',
        description: 'Interval between health checks in minutes',
        module: configuration_entity_1.ConfigurationModule.UPPF_CLAIMS,
        type: configuration_entity_1.ConfigurationType.SYSTEM,
        dataType: configuration_entity_1.ConfigurationDataType.NUMBER,
        defaultValue: '5',
        minValue: 1,
        maxValue: 60,
        uiComponent: 'NUMBER',
        uiGroup: 'Monitoring',
        uiOrder: 2,
    },
    {
        key: 'uppf.monitoring.alert_on_failure',
        name: 'Alert on System Failure',
        description: 'Send alerts when UPPF system failures are detected',
        module: configuration_entity_1.ConfigurationModule.UPPF_CLAIMS,
        type: configuration_entity_1.ConfigurationType.SYSTEM,
        dataType: configuration_entity_1.ConfigurationDataType.BOOLEAN,
        defaultValue: 'true',
        uiComponent: 'CHECKBOX',
        uiGroup: 'Monitoring',
        uiOrder: 3,
    },
    {
        key: 'uppf.monitoring.performance_metrics_enabled',
        name: 'Performance Metrics Enabled',
        description: 'Enable collection of performance metrics for UPPF operations',
        module: configuration_entity_1.ConfigurationModule.UPPF_CLAIMS,
        type: configuration_entity_1.ConfigurationType.SYSTEM,
        dataType: configuration_entity_1.ConfigurationDataType.BOOLEAN,
        defaultValue: 'true',
        uiComponent: 'CHECKBOX',
        uiGroup: 'Monitoring',
        uiOrder: 4,
    },
];
//# sourceMappingURL=uppf-config.schema.js.map