"use strict";
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};
var __metadata = (this && this.__metadata) || function (k, v) {
    if (typeof Reflect === "object" && typeof Reflect.metadata === "function") return Reflect.metadata(k, v);
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.GenerateCustomerInvoiceDto = exports.GenerateSupplierInvoiceDto = void 0;
const class_validator_1 = require("class-validator");
const swagger_1 = require("@nestjs/swagger");
class GenerateSupplierInvoiceDto {
    deliveryId;
    generatedBy;
    invoiceDate;
    dueDate;
    comments;
    forceGeneration;
}
exports.GenerateSupplierInvoiceDto = GenerateSupplierInvoiceDto;
__decorate([
    (0, swagger_1.ApiProperty)({ description: 'Delivery ID' }),
    (0, class_validator_1.IsUUID)(),
    __metadata("design:type", String)
], GenerateSupplierInvoiceDto.prototype, "deliveryId", void 0);
__decorate([
    (0, swagger_1.ApiProperty)({ description: 'Generated by user ID' }),
    (0, class_validator_1.IsUUID)(),
    __metadata("design:type", String)
], GenerateSupplierInvoiceDto.prototype, "generatedBy", void 0);
__decorate([
    (0, swagger_1.ApiPropertyOptional)({ description: 'Invoice date override' }),
    (0, class_validator_1.IsOptional)(),
    (0, class_validator_1.IsDateString)(),
    __metadata("design:type", String)
], GenerateSupplierInvoiceDto.prototype, "invoiceDate", void 0);
__decorate([
    (0, swagger_1.ApiPropertyOptional)({ description: 'Due date override' }),
    (0, class_validator_1.IsOptional)(),
    (0, class_validator_1.IsDateString)(),
    __metadata("design:type", String)
], GenerateSupplierInvoiceDto.prototype, "dueDate", void 0);
__decorate([
    (0, swagger_1.ApiPropertyOptional)({ description: 'Additional invoice comments' }),
    (0, class_validator_1.IsOptional)(),
    (0, class_validator_1.IsString)(),
    __metadata("design:type", String)
], GenerateSupplierInvoiceDto.prototype, "comments", void 0);
__decorate([
    (0, swagger_1.ApiPropertyOptional)({ description: 'Force invoice generation even if validation fails' }),
    (0, class_validator_1.IsOptional)(),
    (0, class_validator_1.IsBoolean)(),
    __metadata("design:type", Boolean)
], GenerateSupplierInvoiceDto.prototype, "forceGeneration", void 0);
class GenerateCustomerInvoiceDto {
    deliveryId;
    generatedBy;
    invoiceDate;
    dueDate;
    comments;
    applyDiscount;
    forceGeneration;
}
exports.GenerateCustomerInvoiceDto = GenerateCustomerInvoiceDto;
__decorate([
    (0, swagger_1.ApiProperty)({ description: 'Delivery ID' }),
    (0, class_validator_1.IsUUID)(),
    __metadata("design:type", String)
], GenerateCustomerInvoiceDto.prototype, "deliveryId", void 0);
__decorate([
    (0, swagger_1.ApiProperty)({ description: 'Generated by user ID' }),
    (0, class_validator_1.IsUUID)(),
    __metadata("design:type", String)
], GenerateCustomerInvoiceDto.prototype, "generatedBy", void 0);
__decorate([
    (0, swagger_1.ApiPropertyOptional)({ description: 'Invoice date override' }),
    (0, class_validator_1.IsOptional)(),
    (0, class_validator_1.IsDateString)(),
    __metadata("design:type", String)
], GenerateCustomerInvoiceDto.prototype, "invoiceDate", void 0);
__decorate([
    (0, swagger_1.ApiPropertyOptional)({ description: 'Due date override' }),
    (0, class_validator_1.IsOptional)(),
    (0, class_validator_1.IsDateString)(),
    __metadata("design:type", String)
], GenerateCustomerInvoiceDto.prototype, "dueDate", void 0);
__decorate([
    (0, swagger_1.ApiPropertyOptional)({ description: 'Additional invoice comments' }),
    (0, class_validator_1.IsOptional)(),
    (0, class_validator_1.IsString)(),
    __metadata("design:type", String)
], GenerateCustomerInvoiceDto.prototype, "comments", void 0);
__decorate([
    (0, swagger_1.ApiPropertyOptional)({ description: 'Apply customer discount' }),
    (0, class_validator_1.IsOptional)(),
    (0, class_validator_1.IsBoolean)(),
    __metadata("design:type", Boolean)
], GenerateCustomerInvoiceDto.prototype, "applyDiscount", void 0);
__decorate([
    (0, swagger_1.ApiPropertyOptional)({ description: 'Force invoice generation even if validation fails' }),
    (0, class_validator_1.IsOptional)(),
    (0, class_validator_1.IsBoolean)(),
    __metadata("design:type", Boolean)
], GenerateCustomerInvoiceDto.prototype, "forceGeneration", void 0);
//# sourceMappingURL=invoice-generation.dto.js.map