import { IsUUID, IsOptional, IsString, IsDateString, IsBoolean } from 'class-validator';
import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';

export class GenerateSupplierInvoiceDto {
  @ApiProperty({ description: 'Delivery ID' })
  @IsUUID()
  deliveryId: string;

  @ApiProperty({ description: 'Generated by user ID' })
  @IsUUID()
  generatedBy: string;

  @ApiPropertyOptional({ description: 'Invoice date override' })
  @IsOptional()
  @IsDateString()
  invoiceDate?: string;

  @ApiPropertyOptional({ description: 'Due date override' })
  @IsOptional()
  @IsDateString()
  dueDate?: string;

  @ApiPropertyOptional({ description: 'Additional invoice comments' })
  @IsOptional()
  @IsString()
  comments?: string;

  @ApiPropertyOptional({ description: 'Force invoice generation even if validation fails' })
  @IsOptional()
  @IsBoolean()
  forceGeneration?: boolean;
}

export class GenerateCustomerInvoiceDto {
  @ApiProperty({ description: 'Delivery ID' })
  @IsUUID()
  deliveryId: string;

  @ApiProperty({ description: 'Generated by user ID' })
  @IsUUID()
  generatedBy: string;

  @ApiPropertyOptional({ description: 'Invoice date override' })
  @IsOptional()
  @IsDateString()
  invoiceDate?: string;

  @ApiPropertyOptional({ description: 'Due date override' })
  @IsOptional()
  @IsDateString()
  dueDate?: string;

  @ApiPropertyOptional({ description: 'Additional invoice comments' })
  @IsOptional()
  @IsString()
  comments?: string;

  @ApiPropertyOptional({ description: 'Apply customer discount' })
  @IsOptional()
  @IsBoolean()
  applyDiscount?: boolean;

  @ApiPropertyOptional({ description: 'Force invoice generation even if validation fails' })
  @IsOptional()
  @IsBoolean()
  forceGeneration?: boolean;
}